### ISSUE TITLE
Authentication for GET request raises exception if wrong credentials provided

### ISSUE THREAD

**Issue by mwittig** [pimatic/pimatic#1002]
Steps to repoduce:

```
curl -X GET --user "user:wrongPassword" https://hostnameOrIP/api/devices/someDeviceId
```

This will raise the following exception (**sent via response body**, no log message!!!):

```
TypeError: Cannot read property 'set' of undefined
    at unauthorized (/home/pi/pimatic-dev/node_modules/pimatic/lib/framework.coffee:336:14)
    at /home/pi/pimatic-dev/node_modules/pimatic/lib/framework.coffee:357:11
    at Layer.handle [as handle_request] (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:312:13)
    at /home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:330:12)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:271:10)
    at _cookieSession (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/cookie-session/index.js:124:5)
    at Layer.handle [as handle_request] (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
...
```

**Comment by mwittig** [comment]
@sweetpi Can you please review the suggested fix? Thanks

**Comment by mwittig** [comment]
May be we should also add some log messages for the various auth-case, like "missing autentication" and "authentication faliure"

**Comment by sweetpi** [comment]
Thanks for filling the issue. Should be fixed in current master.

**Comment by mwittig** [comment]
I am re-opening this one as we should add auth failure log messages to support external security tools like fail2ban. See also https://forum.pimatic.org/topic/743/pimatic-and-fail2ban
