### ISSUE TITLE
[pimatic-rflink] Bug report: TypeError: undefined is not a function

### ISSUE THREAD

**Issue by FrankyB1983** [pimatic/pimatic#1009]
error [pimatic]: A uncaught exception occured: TypeError: undefined is not a function
    at Board._handleAcknowledge (/usr/local/pimatic-app/node_modules/pimatic-rflink/lib/board.coffee:183:5)
    at Board._processData (/usr/local/pimatic-app/node_modules/pimatic-rflink/lib/board.coffee:128:38)
    at SerialPortDriver.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic-rflink/lib/board.coffee:43:8)
    at SerialPortDriver.EventEmitter.emit (events.js:95:17)
    at SerialPort.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic-rflink/lib/serialport.coffee:37:8)
    at SerialPort.EventEmitter.emit (events.js:95:17)
    at /usr/local/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport/lib/parsers.js:24:17
    at Array.forEach (native)
    at Object.parser (/usr/local/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport/lib/parsers.js:23:13)
    at SerialPort.settings.dataCallback (/usr/local/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport/serialport.js:168:14)
    at SerialPort._emitData (/usr/local/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport/serialport.js:377:18)
    at afterRead (/usr/local/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport/serialport.js:356:16)
    at /usr/local/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport/serialport.js:370:7
    at Object.wrapper [as oncomplete] (fs.js:454:17)
 This is most probably a bug in pimatic or in a module, please report it!

**Comment by mwittig** [comment]
Seems to be the same issue as https://github.com/sirchia/pimatic-rflink/issues/14 eventhough the error message is slightly different it occurs on the same line. I am closing this issue now as  pimatic-rflink runs its own issue queue.
