### ISSUE TITLE
Error executing rule (since latest update it seems)

### ISSUE THREAD

**Issue by abmantis** [pimatic/pimatic#1022]

**Comment by mwittig** [comment]
Thanks for reporting. I can confirm this is a bug.
See also https://forum.pimatic.org/topic/2538/plugin-filter-bug

**Comment by wutu** [comment]
Hi, I have the same error with rules:
`when it is 00:00 then execute \"cp /home/wutu/pimatic-app/config.json /home/wutu/pimatic-app/`date +%Y-%m-%d`.json\"`

**Comment by sweetpi** [comment]
Hm diffcult to debug. Could you try to enable debugging and look for a stacktrace?

**Comment by wutu** [comment]
```
10:43:00.617 [] [ShellActionHandler] Error: Command failed: /bin/sh -c cp /home/wutu/pimatic-dev/config.json /home/wutu/pimatic-dev/date +%Y-%m-NaN.json
10:43:00.617 []>cp: target ‘+%Y-%m-%d.json’ is not a directory
10:43:00.617 []>
10:43:00.628 [pimatic] rule test-backup error executing an action: Array.isArray(tags)
10:43:00.637 [pimatic] AssertionError: Array.isArray(tags)
10:43:00.637 [pimatic]>    at Database.saveMessageEvent (/home/wutu/pimatic-dev/node_modules/pimatic/lib/database.coffee:477:7)
10:43:00.637 [pimatic]>    at Framework._this.framework.on._this.messageLoggedListener (/home/wutu/pimatic-dev/node_modules/pimatic/lib/database.coffee:114:12)
10:43:00.637 [pimatic]>    at emitOne (events.js:77:13)
10:43:00.637 [pimatic]>    at Framework.emit (events.js:169:7)
10:43:00.637 [pimatic]>    at Framework._emitMessageLoggedEvent (/home/wutu/pimatic-dev/node_modules/pimatic/lib/framework.coffee:667:8)
10:43:00.637 [pimatic]>    at null.<anonymous> (/home/wutu/pimatic-dev/node_modules/pimatic/lib/framework.coffee:49:10)
10:43:00.637 [pimatic]>    at emitThree (events.js:97:13)
10:43:00.637 [pimatic]>    at null.emit (events.js:175:7)
10:43:00.637 [pimatic]>    at finish (/home/wutu/pimatic-dev/node_modules/pimatic/node_modules/winston/lib/winston/logger.js:194:12)
10:43:00.637 [pimatic]>    at done (/home/wutu/pimatic-dev/node_modules/pimatic/node_modules/winston/node_modules/async/lib/async.js:167:19)
10:43:00.637 [pimatic]>    at /home/wutu/pimatic-dev/node_modules/pimatic/node_modules/winston/node_modules/async/lib/async.js:40:16
10:43:00.637 [pimatic]>    at /home/wutu/pimatic-dev/node_modules/pimatic/node_modules/winston/lib/winston/logger.js:242:7
10:43:00.637 [pimatic]>    at null.TaggedConsoleTarget.log (/home/wutu/pimatic-dev/node_modules/pimatic/lib/logger.coffee:63:3)
10:43:00.637 [pimatic]>    at transportLog (/home/wutu/pimatic-dev/node_modules/pimatic/node_modules/winston/lib/winston/logger.js:234:15)
10:43:00.637 [pimatic]>    at /home/wutu/pimatic-dev/node_modules/pimatic/node_modules/winston/node_modules/async/lib/async.js:157:13
10:43:00.637 [pimatic]>    at _each (/home/wutu/pimatic-dev/node_modules/pimatic/node_modules/winston/node_modules/async/lib/async.js:57:9)
10:43:00.637 [pimatic]>    at Object.async.each (/home/wutu/pimatic-dev/node_modules/pimatic/node_modules/winston/node_modules/async/lib/async.js:156:9)
10:43:00.637 [pimatic]>    at null.Logger.log (/home/wutu/pimatic-dev/node_modules/pimatic/node_modules/winston/lib/winston/logger.js:246:9)
10:43:00.637 [pimatic]>    at null.TaggedLogger.log (/home/wutu/pimatic-dev/node_modules/pimatic/lib/logger.coffee:73:11)
10:43:00.637 [pimatic]>    at null.TaggedLogger.error (/home/wutu/pimatic-dev/node_modules/pimatic/lib/logger.coffee:85:36)
10:43:00.637 [pimatic]>    at Object.members.error (/home/wutu/pimatic-dev/node_modules/pimatic-shell-execute/node_modules/pimatic-plugin-commons/lib/index.js:142:45)
10:43:00.637 [pimatic]>    at Object.members.rejectWithErrorString (/home/wutu/pimatic-dev/node_modules/pimatic-shell-execute/node_modules/pimatic-plugin-commons/lib/index.js:67:19)
10:43:00.637 [pimatic]>    at /home/wutu/pimatic-dev/node_modules/pimatic-shell-execute/shell-execute.coffee:277:19
10:43:00.637 [pimatic]>    at tryCatcher (/home/wutu/pimatic-dev/node_modules/pimatic/node_modules/bluebird/js/release/util.js:16:23)
10:43:00.637 [pimatic]>    at Promise._settlePromiseFromHandler (/home/wutu/pimatic-dev/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:510:31)
10:43:00.637 [pimatic]>    at Promise._settlePromise (/home/wutu/pimatic-dev/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:567:18)
10:43:00.637 [pimatic]>    at Promise._settlePromise0 (/home/wutu/pimatic-dev/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:612:10)
10:43:00.637 [pimatic]>    at Promise._settlePromises (/home/wutu/pimatic-dev/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:687:18)
10:43:00.637 [pimatic]>    at Async._drainQueue (/home/wutu/pimatic-dev/node_modules/pimatic/node_modules/bluebird/js/release/async.js:138:16)
10:43:00.637 [pimatic]>    at Async._drainQueues (/home/wutu/pimatic-dev/node_modules/pimatic/node_modules/bluebird/js/release/async.js:148:10)
10:43:00.637 [pimatic]>    at Immediate.Async.drainQueues [as _onImmediate] (/home/wutu/pimatic-dev/node_modules/pimatic/node_modules/bluebird/js/release/async.js:17:14)
10:43:00.637 [pimatic]>    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by mwittig** [comment]
@wuto can you please post the rule config (marked as Code)?

**Comment by wutu** [comment]
until recently worked this:

```"rule": "when its 10:43 then execute \"cp /home/wutu/pimatic-dev/config.json /home/wutu/pimatic-dev/date +%Y-%m-%d.json\""```

**Comment by mwittig** [comment]
Ok, strange. I am missing the backticks in your rule def. 
Please try `$(date +%Y-%m-%d.json)` instead (without backticks)

**Comment by wutu** [comment]
This keads to fall Pimatic:
```
14:00:58.191 [] Could not find an provider that provides the next action of "execute "cp /home/wutu/pimatic-dev/config.json /home/wutu/pimatic-dev/$(date +%Y-%m-NaN.json)"".
Fatal AssertionError: Array.isArray(tags)
    at Database.saveMessageEvent (/home/wutu/pimatic-dev/node_modules/pimatic/lib/database.coffee:477:7)
    at Framework._this.framework.on._this.messageLoggedListener (/home/wutu/pimatic-dev/node_modules/pimatic/lib/database.coffee:114:12)
    at emitOne (events.js:77:13)
    at Framework.emit (events.js:169:7)
    at Framework._emitMessageLoggedEvent (/home/wutu/pimatic-dev/node_modules/pimatic/lib/framework.coffee:667:8)
    at null.<anonymous> (/home/wutu/pimatic-dev/node_modules/pimatic/lib/framework.coffee:49:10)
    at emitThree (events.js:97:13)
    at null.emit (events.js:175:7)
    at finish (/home/wutu/pimatic-dev/node_modules/pimatic/node_modules/winston/lib/winston/logger.js:194:12)
    at done (/home/wutu/pimatic-dev/node_modules/pimatic/node_modules/winston/node_modules/async/lib/async.js:167:19)
    at /home/wutu/pimatic-dev/node_modules/pimatic/node_modules/winston/node_modules/async/lib/async.js:40:16
    at /home/wutu/pimatic-dev/node_modules/pimatic/node_modules/winston/lib/winston/logger.js:242:7
    at null.TaggedConsoleTarget.log (/home/wutu/pimatic-dev/node_modules/pimatic/lib/logger.coffee:63:3)
    at transportLog (/home/wutu/pimatic-dev/node_modules/pimatic/node_modules/winston/lib/winston/logger.js:234:15)
    at /home/wutu/pimatic-dev/node_modules/pimatic/node_modules/winston/node_modules/async/lib/async.js:157:13
    at _each (/home/wutu/pimatic-dev/node_modules/pimatic/node_modules/winston/node_modules/async/lib/async.js:57:9)
    at Object.async.each (/home/wutu/pimatic-dev/node_modules/pimatic/node_modules/winston/node_modules/async/lib/async.js:156:9)
    at null.Logger.log (/home/wutu/pimatic-dev/node_modules/pimatic/node_modules/winston/lib/winston/logger.js:246:9)
    at null.TaggedLogger.log (/home/wutu/pimatic-dev/node_modules/pimatic/lib/logger.coffee:73:11)
    at null.TaggedLogger.error (/home/wutu/pimatic-dev/node_modules/pimatic/lib/logger.coffee:85:36)
    at /home/wutu/pimatic-dev/node_modules/pimatic/lib/framework.coffee:948:22
    at /home/wutu/pimatic-dev/node_modules/pimatic/node_modules/decl-api/index.js:381:9
    at tryCatcher (/home/wutu/pimatic-dev/node_modules/pimatic/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/wutu/pimatic-dev/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/wutu/pimatic-dev/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/wutu/pimatic-dev/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/wutu/pimatic-dev/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/home/wutu/pimatic-dev/node_modules/pimatic/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/wutu/pimatic-dev/node_modules/pimatic/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/wutu/pimatic-dev/node_modules/pimatic/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by thost96** [comment]
Also getting `error [pimatic]: rule backup-config-and-database error executing an action: Array.isArray(tags)`

Here my rule: 
```
{
  "id": "backup-config-and-database",
   "name": "backup config and database",
    "rule": "when its 8:15 or pimatic-backup-btn is pressed then execute \"cp /home/pi/pimatic/config.json /pimatic/Backup/`date +%Y-%m-%d`_pi3_config.json \" and execute \"cp /home/pi/pimatic/pimatic-database.sqlite /pimatic/Backup/`date +%Y-%m-%d`_pi3_pimatic-database.sqlite\" after 5 seconds",
    "active": true,
    "logging": true
}
```

**Comment by incmve** [comment]
I'm on update current version is 0.9.36 and don't have the problem.
<code>
execute "cp /home/pi/pimatic-app/config.json /home/pi/Backup/`date +%Y-%m-%d`.json" and execute "ftp-upload -h 192.168.0.10 -u admin --password PASS -d /Backup_internal/Backup_pimatic/ /home/pi/Backup/`date +%Y-%m-%d`.json" after 1s and execute "rm /home/pi/Backup/`date +%Y-%m-%d`.json" after 5s
</code>

**Comment by thost96** [comment]
Anything new to this?
