### ISSUE TITLE
Unexpected string

### ISSUE THREAD

**Issue by thost96** [pimatic/pimatic#1024]
I updated my dev enviorment and started with a clean install of pimatic. I only using the default config with a password set. If i open the Plugins or Updates page, i get `[pimatic] Unexpected string`. 

Before i used pimatic@0.9.35 and it worked well. 

What is causing this error?

**Comment by sweetpi** [comment]
Could you enable debugging and post the full startup log?

**Comment by thost96** [comment]
Here is the debug output:

```
12:14:32.356 2016-11-30 Wednesday
12:14:34.012 [pimatic] Starting pimatic version 0.9.37
12:14:34.046 [pimatic] settings.debug is true, showing debug output for pimatic core.
12:14:34.587 [pimatic, ppm] 2.15.11
12:14:34.597 [pimatic] Loading plugin: "pimatic-cron" (0.8.8)
12:14:34.696 [pimatic] Loading plugin: "pimatic-mobile-frontend" (0.9.11)
12:14:34.852 [pimatic] Unexpected string
12:14:34.854 [pimatic] SyntaxError: Unexpected string
12:14:34.854 [pimatic]>    at Object.parse (native)
12:14:34.854 [pimatic]>    at PluginManager.getInstalledPackageInfo (/pimatic/Ent/node_modules/pimatic/lib/plugins.coffee:435:19)
12:14:34.854 [pimatic]>    at PluginManager.loadPlugin (/pimatic/Ent/node_modules/pimatic/lib/plugins.coffee:74:22)
12:14:34.854 [pimatic]>    at /pimatic/Ent/node_modules/pimatic/lib/plugins.coffee:477:25
12:14:34.854 [pimatic]>    at tryCatcher (/pimatic/Ent/node_modules/pimatic/node_modules/bluebird/js/release/util.js:16:23)
12:14:34.854 [pimatic]>    at Promise._settlePromiseFromHandler (/pimatic/Ent/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:510:31)
12:14:34.854 [pimatic]>    at Promise._settlePromise (/pimatic/Ent/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:567:18)
12:14:34.854 [pimatic]>    at Promise._settlePromiseCtx (/pimatic/Ent/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:604:10)
12:14:34.854 [pimatic]>    at Async._drainQueue (/pimatic/Ent/node_modules/pimatic/node_modules/bluebird/js/release/async.js:143:12)
12:14:34.854 [pimatic]>    at Async._drainQueues (/pimatic/Ent/node_modules/pimatic/node_modules/bluebird/js/release/async.js:148:10)
12:14:34.854 [pimatic]>    at Immediate.Async.drainQueues [as _onImmediate] (/pimatic/Ent/node_modules/pimatic/node_modules/bluebird/js/release/async.js:17:14)
12:14:34.854 [pimatic]>    at processImmediate [as _immediateCallback] (timers.js:383:17)
12:14:34.857 [pimatic-cron] the time is: Wed Nov 30 2016 12:14:34 GMT+0100 (CET)
12:14:34.956 [pimatic-mobile-frontend] packing static assets
12:14:35.097 [pimatic-mobile-frontend] packing static assets finished
12:14:35.099 [pimatic-mobile-frontend] rendering html
12:14:36.378 [pimatic-mobile-frontend] rendering html finished
12:14:36.387 [pimatic] Listening for HTTP-request on port 80...
12:15:59.635 [pimatic] Unexpected string
12:15:59.640 [pimatic] SyntaxError: Unexpected string
12:15:59.640 [pimatic]>    at Object.parse (native)
12:15:59.640 [pimatic]>    at PluginManager.getInstalledPackageInfo (/pimatic/Ent/node_modules/pimatic/lib/plugins.coffee:435:19)
12:15:59.640 [pimatic]>    at fn (/pimatic/Ent/node_modules/pimatic/lib/plugins.coffee:305:26)
12:15:59.640 [pimatic]>    at /pimatic/Ent/node_modules/pimatic/lib/plugins.coffee:456:13
12:15:59.640 [pimatic]>    at tryCatcher (/pimatic/Ent/node_modules/pimatic/node_modules/bluebird/js/release/util.js:16:23)
12:15:59.640 [pimatic]>    at Promise._settlePromiseFromHandler (/pimatic/Ent/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:510:31)
12:15:59.640 [pimatic]>    at Promise._settlePromise (/pimatic/Ent/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:567:18)
12:15:59.640 [pimatic]>    at Promise._settlePromise0 (/pimatic/Ent/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:612:10)
12:15:59.640 [pimatic]>    at Promise._settlePromises (/pimatic/Ent/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:691:18)
12:15:59.640 [pimatic]>    at Promise._fulfill (/pimatic/Ent/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:636:18)
12:15:59.640 [pimatic]>    at Promise._resolveCallback (/pimatic/Ent/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:431:57)
12:15:59.640 [pimatic]>    at Promise._settlePromiseFromHandler (/pimatic/Ent/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:522:17)
12:15:59.640 [pimatic]>    at Promise._settlePromise (/pimatic/Ent/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:567:18)
12:15:59.640 [pimatic]>    at Promise._settlePromise0 (/pimatic/Ent/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:612:10)
12:15:59.640 [pimatic]>    at Promise._settlePromises (/pimatic/Ent/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:691:18)
12:15:59.640 [pimatic]>    at Promise._fulfill (/pimatic/Ent/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:636:18)
12:15:59.640 [pimatic]>    at /pimatic/Ent/node_modules/pimatic/node_modules/bluebird/js/release/nodeback.js:42:21
12:15:59.640 [pimatic]>    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by thost96** [comment]
Okay installed pimatic@0.9.35 today again and getting the same error message. Maybe it's something with nodejs / npm?

`node -v => v4.6.2`
`npm -v => 2.15.11`

**Comment by mwittig** [comment]
The path `/pimatic/Ent/node_modules/pimatic/lib/plugins.coffee`looks strange to me. What is the full  path  to installation directory?

**Comment by thost96** [comment]
The path is correct. Pimatic is installed in `/pimatic/Ent/node_modules/pimatic` on a cifs share.

**Comment by mwittig** [comment]
ok. Just a wild guess: One of the package.json files is empty.

You can install the jq package (sudo apt-get install jq) and try the following in a root shell (assuming that your pimatic runs as root):

```
for p in ` ls /pimatic/Ent/node_modules/pimatic*/package.json`; do if [[ "`jq  '.version!=null' $p`" == "true" ]]; then echo "OK $p"; else echo "ERROR $p"; fi; done
```

**Comment by thost96** [comment]
Here is the output:
```
OK /pimatic/Ent/node_modules/pimatic-cron/package.json
OK /pimatic/Ent/node_modules/pimatic-mobile-frontend/package.json
OK /pimatic/Ent/node_modules/pimatic/package.json
```
All package.json files are normally filed. And yes, pimatic runs as root using `sudo node node_modules/pimatic/pimatic.js`

**Comment by mwittig** [comment]
Which plugins do you have in the "plugins" section of config.json?

**Comment by mwittig** [comment]
> Maybe it's something with nodejs / npm

I am using the same versions, btw.

**Comment by thost96** [comment]
Just the default ones:
```
"plugins": [
    {
      "plugin": "cron"
    },
    {
      "plugin": "mobile-frontend"
    }
  ],
```

**Comment by thost96** [comment]
I will test a fresh linux install with nodejs and npm. Maybe this helps.

**Comment by mwittig** [comment]
OK, I have no other idea at the moment.

**Comment by thost96** [comment]
A fresh linux install did the trick.
