### ISSUE TITLE
soap not working with pimatic

### ISSUE THREAD

**Issue by sharkds** [pimatic/pimatic#1045]
I'm trying to use SOAP client in plugin but pimatic failing with next error:

```
18:42:01.432 [pimatic] Listening for HTTP-request on port 80...
18:42:01.736 [pimatic] A uncaught exception occured: TypeError: callback is not a function
18:42:01.736 [pimatic]>    at /Users/shark/workspace/smarthome/pimatic-app/node_modules/pimatic-sms/node_modules/soap/lib/soap.js:58:5
18:42:01.736 [pimatic]>    at WSDL.callback (/Users/shark/workspace/smarthome/pimatic-app/node_modules/pimatic-sms/node_modules/soap/lib/soap.js:25:9)
18:42:01.736 [pimatic]>    at /Users/shark/workspace/smarthome/pimatic-app/node_modules/pimatic-sms/node_modules/soap/lib/wsdl.js:1073:12
18:42:01.736 [pimatic]>    at WSDL._processNextInclude (/Users/shark/workspace/smarthome/pimatic-app/node_modules/pimatic-sms/node_modules/soap/lib/wsdl.js:1148:12)
18:42:01.736 [pimatic]>    at WSDL.processIncludes (/Users/shark/workspace/smarthome/pimatic-app/node_modules/pimatic-sms/node_modules/soap/lib/wsdl.js:1191:8)
18:42:01.736 [pimatic]>    at /Users/shark/workspace/smarthome/pimatic-app/node_modules/pimatic-sms/node_modules/soap/lib/wsdl.js:1028:10
18:42:01.736 [pimatic]>    at _combinedTickCallback (internal/process/next_tick.js:67:7)
18:42:01.736 [pimatic]>    at process._tickCallback (internal/process/next_tick.js:98:9)
18:42:01.736 [pimatic]> This is most probably a bug in pimatic or in a module, please report it!
18:42:01.737 [pimatic] shutting pimatic down...
/Users/shark/workspace/smarthome/pimatic-app/node_modules/pimatic/startup.coffee:98
          return framework.destroy().then(function() {
                 ^

ReferenceError: framework is not defined
    at process.uncaughtException (/Users/shark/workspace/smarthome/pimatic-app/node_modules/pimatic/startup.coffee:85:9)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at processEmit [as emit] (/Users/shark/workspace/smarthome/pimatic-app/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/signal-exit/index.js:146:32)
    at process._fatalException (bootstrap_node.js:292:26)

**Comment by mwittig** [comment]
As far as I can see you have forked pimatic-sms and now you're trying to implement an extension of the service using some SOAP service interface. The error looks like a error in your code.  Is your code already on github. I am happy to check. Please re-open the ticket in case.

**Comment by sharkds** [comment]
The issue happens with this code:

      # require the SOAP module and create a client
      @client = require("soap");
      @client.createClient 'http://example.com/api/wsdl.html', (err, client) ->
        client.Auth({
          login: options.login,
          password: options.password})
        return

**Comment by mwittig** [comment]
I think the problem is that you forgot to provide the callback function for the client.Auth() invocation. I have tried the following code which is very close to your example. The code works for me up to the point where the authentication request returns. 

To progress on this it'll be helpful if you publish your development branch on github. I am happy to assist you further on this.

```
  # SMS Plugin
  class SMSPlugin extends env.plugins.Plugin

    # ####init()
    init: (app, @framework, @config) =>

      # ...

      @client = require("soap");
      @client.createClient 'https://www.smsglobal.com/mobileworks/soapserver.php?wsdl', (err, client) =>
        if err
          env.logger.error err
        else
          env.logger.info "starting authentication"
          client.apiValidateLogin({
              login: "demo",
              password: "demo1234"}, (err, result) =>
            if err
              env.logger.error err
            else
              env.logger.info result
          )
```

**Comment by sharkds** [comment]
Thanks for your help.
