### ISSUE TITLE
uncaught exception

### ISSUE THREAD

**Issue by passie** [pimatic/pimatic#1047]
Although everything is working. My logs are full with the following messages.
How to correct this ?

```
error [pimatic]: A uncaught exception occured: AssertionError: false == true
    at Socket.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic/node_modules/decl-api/index.js:469:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/socket.js:503:12
    at nextTickCallbackWith0Args (node.js:436:9)
    at process._tickCallback (node.js:365:13)
 This is most probably a bug in pimatic or in a module, please report it!

**Comment by mwittig** [comment]
Does this error occur repeatedly? 
Can you reproduce the error, i.e. does it happen if you perform certain funtions?

**Comment by mwittig** [comment]
No response. 
Closing this now. Please re-open if you wish to follow up on this
