### ISSUE TITLE
Pimatic on Odroid C2

### ISSUE THREAD

**Issue by hyp3rx** [pimatic/pimatic#1052]
Hello,
I'm using pimatic for a long time... (maybe 2 years by now?) ... still using a RP2.
So now i decided to switch to an faster Odroid C2, main reason is "gigabit ethernet" 
Btw, after trying to start Pimatic i get an ERROR as fallowing:

```
odroid@odroid64:~/pimatic-app$ sudo node_modules/pimatic/pimatic.js
22:46:20.945 2017-02-21 Tuesday
22:46:25.993 [pimatic] Starting pimatic version 0.9.38
Knex: run
$ npm install sqlite3 --save
Error: /home/odroid/pimatic-app/node_modules/sqlite3/lib/binding/node-v46-linux-arm/node_sqlite3.node: wrong ELF class: ELFCLASS64
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (/home/odroid/pimatic-app/node_modules/pimatic/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/odroid/pimatic-app/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (/home/odroid/pimatic-app/node_modules/pimatic/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Client_SQLite3._driver (/home/odroid/pimatic-app/node_modules/pimatic/node_modules/knex/lib/dialects/sqlite3/index.js:75:12)
    at Client_SQLite3.initializeDriver (/home/odroid/pimatic-app/node_modules/pimatic/node_modules/knex/lib/client.js:211:26)
    at Client_SQLite3.Client (/home/odroid/pimatic-app/node_modules/pimatic/node_modules/knex/lib/client.js:105:10)
    at new Client_SQLite3 (/home/odroid/pimatic-app/node_modules/pimatic/node_modules/knex/lib/dialects/sqlite3/index.js:58:20)
    at Knex (/home/odroid/pimatic-app/node_modules/pimatic/node_modules/knex/lib/index.js:60:34)
    at /home/odroid/pimatic-app/node_modules/pimatic/lib/database.coffee:71:17
    at tryCatcher (/home/odroid/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/odroid/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/odroid/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/home/odroid/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/home/odroid/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/odroid/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/odroid/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```
i know that it has something to do with the OS itself, is there another way to install SQLite3 ?

Thank you

**Comment by mwittig** [comment]
The node-sqlite3 package comes with pre-built binaries. Most likely, the platform detection as part of the package does not work in your case. My guess: Your system OS is a 64 bit build, but the package installer regards it as Raspbian (which always is 32 bit regardless of whether the hardware is 32 or 64 bit). To work around the matter you can try to make a full build. Maybe the following works for you:
```
npm install --build-from-source=sqlite3
```

See also https://github.com/mapbox/node-sqlite3/wiki

**Comment by hyp3rx** [comment]
wrong command? typo? 
should it be npm install --build-from-source --sqlite=/usr/local ? 

I´m on ubuntu 16.04 64Bit

**Comment by mwittig** [comment]
Sorry, I haven't tried this myself. See: https://github.com/mapbox/node-sqlite3/wiki/Binaries#forcing-a-source-compile

**Comment by hyp3rx** [comment]
removed /node_modules/sqlite3 completely... then installed as you mentioned...
after starting pimatic i get still the exact same ERROR

**Comment by mwittig** [comment]
My suggestion is to open a topic in the user forum, Maybe some other users came accross the same problem.

**Comment by hyp3rx** [comment]
Ok thank you anyway, i have opened a new Topic in the user forum

**Comment by mwittig** [comment]
Closing this now
