### ISSUE TITLE
uncaught exception

### ISSUE THREAD

**Issue by FranzieR** [pimatic/pimatic#1055]
I have a uncaught exception in my Pimatic system once in a while. Can someone tell me if I can do something about it?

error [pimatic]: A uncaught exception occured: Error: getaddrinfo ENOTFOUND ftp.knmi.nl ftp.knmi.nl:21
    at errnoException (dns.js:27:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
From connect
    at Socket.connect (/home/pi/pimatic-app/node_modules/pimatic/startup.coffee:55:29)
    at Socket.connect (net.js:883:28)
    at /home/pi/pimatic-app/node_modules/pimatic-denon-avr/telnet-app-protocol.coffee:108:19
    at Promise._execute (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:77:14)
    at TelnetAppProtocol._connect (/home/pi/pimatic-app/node_modules/pimatic-denon-avr/telnet-app-protocol.coffee:94:18)
    at null.PromiseObject.create.$run (/home/pi/pimatic-app/node_modules/pimatic-denon-avr/node_modules/promise-retryer/index.js:25:12)
    at Function.run (/home/pi/pimatic-app/node_modules/pimatic-denon-avr/node_modules/promise-retryer/node_modules/promise-object/index.js:78:11)
    at null._onTimeout (/home/pi/pimatic-app/node_modules/pimatic-denon-avr/node_modules/promise-retryer/index.js:40:16)
    at Timer.listOnTimeout (timers.js:92:15)
 This is most probably a bug in pimatic or in a module, please report it!

**Comment by mwittig** [comment]
Which version do you have installed of pimatic-knmi-weather? The issue should have been fixed as part of version 0.9.2

**Comment by FranzieR** [comment]
Sorry, die not see that there was a update for the plugin. Updated and I hope it will be fine now!
Thanks.

**Comment by mwittig** [comment]
Ok, no prob. Please re-open if the issue pops up again.  I am condident the issue has been solved, however.
