### ISSUE TITLE
SQLITE_ERROR: no such column: undefined

### ISSUE THREAD

**Issue by kanedo** [pimatic/pimatic#1072]
Since a while ago I regularly get an error saying:

```
error [pimatic]: delete from "message" where "time" < 1497155415956 and (1=1) AND NOT (1=1 AND level=undefined) - SQLITE_ERROR: no such column: undefined
```

This happens every day around the same time. So I guess it is some cronjob cleanup which goes wrong. However I cannot figure out what causes this error

**Comment by Blaimi** [comment]
I have the same problem with mysql:
```
delete from `message` where time < FROM_UNIXTIME(1476197705) and (1=1) AND NOT (1=1 AND level=undefined) - ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'where clause'
```
It also occures on every start.

With debug:true in settings and database:
```
Okt 11 23:08:05 furrina pimatic.js[966]: 23:08:05.977 [pimatic] Listening for HTTP-request on port 20080...
Okt 11 23:12:35 furrina pimatic.js[966]: 23:12:35.784 [pimatic] Deleting expired logged values
Okt 11 23:12:35 furrina pimatic.js[966]: 23:12:35.794 [pimatic] Deleting expired events
Okt 11 23:12:35 furrina pimatic.js[966]: 23:12:35.834 [pimatic] query: delete from `attributeValueNumber` where time < FROM_UNIXTIME(1476198755) and deviceAttributeId in (select `id` from `deviceAttribute` where (1=1) AND NOT (1=1 and discrete=0) AND NOT (1=1 and attributeName='temperature' and type='number') AND NOT (1=1 and attributeName='humidity' and type='number'))
Okt 11 23:12:35 furrina pimatic.js[966]: 23:12:35.859 [pimatic] query: delete from `attributeValueString` where time < FROM_UNIXTIME(1476198755) and deviceAttributeId in (select `id` from `deviceAttribute` where (1=1) AND NOT (1=1 and discrete=0) AND NOT (1=1 and attributeName='temperature' and type='number') AND NOT (1=1 and attributeName='humidity' and type='number'))
Okt 11 23:12:35 furrina pimatic.js[966]: 23:12:35.883 [pimatic] query: delete from `attributeValueNumber` where time < FROM_UNIXTIME(1476198755) and deviceAttributeId in (select `id` from `deviceAttribute` where (1=1 and discrete=0) AND NOT (1=1 and attributeName='temperature' and type='number') AND NOT (1=1 and attributeName='humidity' and type='number'))
Okt 11 23:12:35 furrina pimatic.js[966]: 23:12:35.902 [pimatic] query: delete from `attributeValueString` where time < FROM_UNIXTIME(1476198755) and deviceAttributeId in (select `id` from `deviceAttribute` where (1=1 and discrete=0) AND NOT (1=1 and attributeName='temperature' and type='number') AND NOT (1=1 and attributeName='humidity' and type='number'))
Okt 11 23:12:35 furrina pimatic.js[966]: 23:12:35.926 [pimatic] query: delete from `attributeValueNumber` where time < FROM_UNIXTIME(1476198755) and deviceAttributeId in (select `id` from `deviceAttribute` where (1=1 and attributeName='temperature' and type='number') AND NOT (1=1 and attributeName='humidity' and type='number'))
Okt 11 23:12:35 furrina pimatic.js[966]: 23:12:35.948 [pimatic] query: delete from `attributeValueString` where time < FROM_UNIXTIME(1476198755) and deviceAttributeId in (select `id` from `deviceAttribute` where (1=1 and attributeName='temperature' and type='number') AND NOT (1=1 and attributeName='humidity' and type='number'))
Okt 11 23:12:35 furrina pimatic.js[966]: 23:12:35.971 [pimatic] query: delete from `attributeValueNumber` where time < FROM_UNIXTIME(1476198755) and deviceAttributeId in (select `id` from `deviceAttribute` where (1=1 and attributeName='humidity' and type='number'))
Okt 11 23:12:35 furrina pimatic.js[966]: 23:12:35.992 [pimatic] query: delete from `attributeValueString` where time < FROM_UNIXTIME(1476198755) and deviceAttributeId in (select `id` from `deviceAttribute` where (1=1 and attributeName='humidity' and type='number'))
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.017 [pimatic] Deleting expired events... Done.
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.023 [pimatic] Deleting expired message
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.074 [pimatic] query: delete from `message` where time < FROM_UNIXTIME(1476198756) and (1=1) AND NOT (1=1 AND level=undefined)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.183 [pimatic] delete from `message` where time < FROM_UNIXTIME(1476198756) and (1=1) AND NOT (1=1 AND level=undefined) - ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'where clause'
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic] Error: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'where clause'
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Query.Sequence._packetToError (/home/pimatic/pimatic-app/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Query.ErrorPacket (/home/pimatic/pimatic-app/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Protocol._parsePacket (/home/pimatic/pimatic-app/node_modules/mysql/lib/protocol/Protocol.js:279:23)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Parser.write (/home/pimatic/pimatic-app/node_modules/mysql/lib/protocol/Parser.js:76:12)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Protocol.write (/home/pimatic/pimatic-app/node_modules/mysql/lib/protocol/Protocol.js:39:16)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Socket.<anonymous> (/home/pimatic/pimatic-app/node_modules/mysql/lib/Connection.js:103:28)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at emitOne (events.js:77:13)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Socket.emit (events.js:169:7)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Socket.emit (/home/pimatic/pimatic-app/node_modules/pimatic/startup.coffee:63:24)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at readableAddChunk (_stream_readable.js:153:18)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Socket.Readable.push (_stream_readable.js:111:10)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at TCP.onread (net.js:540:20)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    --------------------
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Protocol._enqueue (/home/pimatic/pimatic-app/node_modules/mysql/lib/protocol/Protocol.js:145:48)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Connection.query (/home/pimatic/pimatic-app/node_modules/mysql/lib/Connection.js:208:25)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at /home/pimatic/pimatic-app/node_modules/pimatic/node_modules/knex/lib/dialects/mysql/index.js:152:18
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Promise._execute (/home/pimatic/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/debuggability.js:300:9)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Promise._resolveFromExecutor (/home/pimatic/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:483:18)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at new Promise (/home/pimatic/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:79:10)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Client_MySQL._query (/home/pimatic/pimatic-app/node_modules/pimatic/node_modules/knex/lib/dialects/mysql/index.js:146:12)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Client_MySQL.query (/home/pimatic/pimatic-app/node_modules/pimatic/node_modules/knex/lib/client.js:197:17)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at /home/pimatic/pimatic-app/node_modules/pimatic/node_modules/knex/lib/transaction.js:274:21
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at tryCatcher (/home/pimatic/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/util.js:16:23)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Function.Promise.attempt.Promise.try (/home/pimatic/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/method.js:39:29)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Client_MySQL.trxClient.query (/home/pimatic/pimatic-app/node_modules/pimatic/node_modules/knex/lib/transaction.js:271:34)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Runner.<anonymous> (/home/pimatic/pimatic-app/node_modules/pimatic/node_modules/knex/lib/runner.js:146:36)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Runner.tryCatcher (/home/pimatic/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/util.js:16:23)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Runner.query (/home/pimatic/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/method.js:15:34)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at /home/pimatic/pimatic-app/node_modules/pimatic/node_modules/knex/lib/runner.js:65:21
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at tryCatcher (/home/pimatic/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/util.js:16:23)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at /home/pimatic/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/using.js:185:26
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at tryCatcher (/home/pimatic/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/util.js:16:23)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Promise._settlePromiseFromHandler (/home/pimatic/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:512:31)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Promise._settlePromise (/home/pimatic/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:569:18)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Promise._settlePromise0 (/home/pimatic/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:614:10)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Promise._settlePromises (/home/pimatic/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:693:18)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Promise._fulfill (/home/pimatic/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:638:18)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at PromiseArray._resolve (/home/pimatic/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise_array.js:126:19)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at PromiseArray._promiseFulfilled (/home/pimatic/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise_array.js:144:14)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Promise._settlePromise (/home/pimatic/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:574:26)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Promise._settlePromise0 (/home/pimatic/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:614:10)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Promise._settlePromises (/home/pimatic/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:693:18)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Async._drainQueue (/home/pimatic/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:133:16)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Async._drainQueues (/home/pimatic/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:143:10)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at Immediate.Async.drainQueues [as _onImmediate] (/home/pimatic/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:17:14)
Okt 11 23:12:36 furrina pimatic.js[966]: 23:12:36.188 [pimatic]>    at processImmediate [as _immediateCallback] (timers.js:396:17)
```

**Comment by Blaimi** [comment]
OK, I found out, I have an error in my "messageLogging"-Config. While disabling debug once, I deleted accidentially the `"level": "debug"`-line in "messageLogging".

Since the setting is correct, the message disappeared. (And the database is populated like it is set in "diskSyncInterval" after "5m")

@kanedo can you post your config.json? (watch out for passwords)

**Comment by kanedo** [comment]
@Blaimi I'm not exactly sure what you mean. There is a `level` in one of the messageLogging array entries.

I have shortened the config quite a bit so it is not so massive:
```
{
  "settings": {
    "httpServer": {
      ***
    },
    "httpsServer": {
     ***
    },
    "database": {
      "deviceAttributeLogging": [
        {
          "deviceId": "*",
          "attributeName": "*",
          "type": "*",
          "interval": "0",
          "expire": "7d"
        },
        {
          "deviceId": "*",
          "attributeName": "*",
          "type": "continuous",
          "interval": "5min",
          "expire": "7d"
        },
        {
          "deviceId": "*",
          "attributeName": "temperature",
          "type": "number",
          "expire": "2y"
        },
        {
          "deviceId": "*",
          "attributeName": "pressure",
          "type": "number",
          "expire": "2y"
        },
        {
          "deviceId": "*",
          "attributeName": "lightintensity",
          "type": "number",
          "expire": "2y"
        },
        {
          "deviceId": "*",
          "attributeName": "humidity",
          "type": "number",
          "expire": "2y"
        }
      ],
      "messageLogging": [
        {
          "level": "*",
          "tags": [],
          "expire": "7d"
        },
        {
          "tags": [],
          "expire": "0"
        }
      ]
    },
    "authentication": {
      "secret": "****"
    },
    "gui": {},
    "cors": {}
  },
  "plugins": [
    *****
  ],
  "devices": [
    ***
  ]
}
```

**Comment by fips21** [comment]
I have the "level": "debug" line in my config. Looks like this:

"messageLogging": [
        {
          "level": "*",
          "tags": [],
          "expire": "7d"
        },
        {
          **"level": "debug",**
          "tags": [],
          "expire": "0"
        }
      ]


Regards
