### ISSUE TITLE
[pimatic-ping] 

### ISSUE THREAD

**Issue by thost96** [pimatic/pimatic#1083]
Hi, i'm getting aroud 100 times this message after editing a PingPresence device every minute:

```
error [pimatic]: An uncaught exception occurred: Error: Resource temporarily unavailable
    at Error (native)
    at Socket.onRecvReady (/home/pi/pimatic-app/node_modules/pimatic-ping/node_modules/net-ping/node_modules/raw-socket/index.js:86:13)
    at emitNone (events.js:67:13)
    at SocketWrap.emit (events.js:166:7)
 This is most probably a bug in pimatic or in a module, please report it!
```

**Comment by mwittig** [comment]
Did you edit the ping device using the device editor?

**Comment by thost96** [comment]
Yes, after a reboot of pimatic, no new messages are logged.
