### ISSUE TITLE
Could not start Pimatic

### ISSUE THREAD

**Issue by groebi98** [pimatic/pimatic#1088]
Hello,
I have a problem with the installation. I followed the instruction, but every time i get this error ...

`pi@pi:~/pimatic-app $ sudo node_modules/pimatic/pimatic.js
coffee-cache: No coffee-script package found.
module.js:544
    throw err;
    ^

Error: Cannot find module './lib/daemon'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic/pimatic.js:5:12)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
`

**Comment by mwittig** [comment]
For general support cases please use our Forum. Thanks
https://forum.pimatic.org
