### ISSUE TITLE
[pimatic] 0.9.42 doesn't find config file

### ISSUE THREAD

**Issue by andig** [pimatic/pimatic#1097]
I have a config:

	~/htdocs/pimatic-app
	❯ ls
	config.json               node_modules              pim                       pimatic.sublime-project   start.sh
	etc                       package-lock.json         pimatic-database.sqlite   pimatic.sublime-workspace

start it from the current folder:

	❯ pwd
	/Users/andig/htdocs/pimatic-app

but config is not picked up:

	❯ sudo node_modules/pimatic/pimatic.js
	17:54:32.267 2018-04-14 Saturday
	17:54:33.525 [pimatic] Starting pimatic version 0.9.42
	17:54:33.594 [pimatic] Startup error: Error: ENOENT: no such file or directory, open '/Users/andig/Documents/config.json'
	17:54:33.594 [pimatic]>    at Object.fs.openSync (fs.js:663:18)
	17:54:33.594 [pimatic]>    at Object.fs.readFileSync (fs.js:568:33)
	17:54:33.594 [pimatic]>    at Framework._loadConfig (/Users/andig/Documents/htdocs/pimatic/lib/framework.coffee:142:21)
	17:54:33.594 [pimatic]>    at new Framework (/Users/andig/Documents/htdocs/pimatic/lib/framework.coffee:61:8)
	17:54:33.594 [pimatic]>    at /Users/andig/Documents/htdocs/pimatic/startup.coffee:94:17
	17:54:33.594 [pimatic]>    at tryCatcher (/Users/andig/Documents/htdocs/pimatic/node_modules/bluebird/js/release/util.js:16:23)
	17:54:33.594 [pimatic]>    at Function.Promise.attempt.Promise.try (/Users/andig/Documents/htdocs/pimatic/node_modules/bluebird/js/release/method.js:39:29)
	17:54:33.594 [pimatic]>    at Object.startup (/Users/andig/Documents/htdocs/pimatic/startup.coffee:93:10)
	17:54:33.594 [pimatic]>    at run (/Users/andig/Documents/htdocs/pimatic/pimatic.js:15:24)
	17:54:33.594 [pimatic]>    at Object.<anonymous> (/Users/andig/Documents/htdocs/pimatic/pimatic.js:20:3)
	17:54:33.594 [pimatic]>    at Module._compile (module.js:660:30)
	17:54:33.594 [pimatic]>    at Object.Module._extensions..js (module.js:671:10)
	17:54:33.594 [pimatic]>    at Module.load (module.js:573:32)
	17:54:33.594 [pimatic]>    at tryModuleLoad (module.js:513:12)
	17:54:33.594 [pimatic]>    at Function.Module._load (module.js:505:3)
	17:54:33.594 [pimatic]>    at Function.Module.runMain (module.js:701:10)
	17:54:33.594 [pimatic]>    at startup (bootstrap_node.js:194:16)
	17:54:33.594 [pimatic]>    at bootstrap_node.js:618:3
	17:54:33.604 [pimatic] exiting...

How can I convince pimatic to loo for the config in the current folder instead of the user's documents?

**Comment by andig** [comment]
Caused by some horribly entangled npm mess :/
