### ISSUE TITLE
Serial driver problem?!

### ISSUE THREAD

**Issue by syrisara** [pimatic/pimatic#1106]
After adding 2 dimmer devices and a raw switch next error happened,

```
error [pimatic]: An uncaught exception occurred: Error: Could not parse expression
    at VariableManager.parseVariableExpression (/home/pi/pimatic-app/node_modules/pimatic/lib/variables.coffee:504:15)
    at Board.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-homeduino/homeduino.coffee:1102:38)
    at emitOne (events.js:82:20)
    at Board.emit (events.js:169:7)
    at Board._emitReceive (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/lib/board.js:352:12)
    at Board._handleRFControl (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/lib/board.js:337:10)
    at Board._onLine (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/lib/board.js:142:21)
    at SerialPortDriver.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/lib/board.js:83:22)
    at emitOne (events.js:77:13)
    at SerialPortDriver.emit (events.js:169:7)
    at SerialPort.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/lib/driver/serialport.js:64:24)
    at emitOne (events.js:77:13)
    at SerialPort.emit (events.js:169:7)
    at /home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/parsers.js:25:17
    at Array.forEach (native)
    at Object.parser (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/parsers.js:24:13)
    at Object.SerialPort.opts.dataCallback (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/serialport.js:181:12)
    at SerialPortFactory.SerialPort._emitData (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/serialport.js:396:20)
    at afterRead (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/serialport.js:372:20)
    at /home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/serialport.js:388:9
    at FSReqWrap.wrapper [as oncomplete] (fs.js:576:17)
 This is most probably a bug in pimatic or in a module, please report it!

**Comment by michbeck100** [comment]
Please post your config.json.

**Comment by mwittig** [comment]
I am closing this as requester has not provided further information within 3 months.
