### ISSUE TITLE
Every Night " An uncaught exception occurred: Error: expected param: valueOrExpression" errors

### ISSUE THREAD

**Issue by MarcelMertens** [pimatic/pimatic#1117]
Hello,
i have a new fresh installation on a raspi b+. Every night i receive the following errors several times every hour. Mostly it starts at 11:50 pm and then every hour until 5:50 am.

`error [pimatic]: An uncaught exception occurred: Error: expected param: valueOrExpression
    at callActionFromSocket (/home/pi/pimatic-app/node_modules/pimatic/node_modules/decl-api/index.js:289:13)
    at callActionFromSocketAndRespond (/home/pi/pimatic-app/node_modules/pimatic/node_modules/decl-api/index.js:393:14)
    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/decl-api/index.js:476:20
    at Socket.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic/node_modules/decl-api/index.js:482:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/socket.js:503:12
    at nextTickCallbackWith0Args (node.js:489:9)
    at process._tickCallback (node.js:418:13)
 This is most probably a bug in pimatic or in a module, please report it!
05:54:28warn [pimatic]: Keeping pimatic alive, but could be in an undefined state, please restart pimatic as soon as possible!`

**Comment by MarcelMertens** [comment]
Pimatic version is latests, 
```
pi@raspberrypi:~/pimatic-app/node_modules/pimatic $ node --version
v4.9.1
```

**Comment by mwittig** [comment]
Thanks for reporting. The error occurs because some action operation on a variable does not contain the required parameter `valueOrExpression `. Action candidates are updateVariable, addVariable. Do you use the Pimatic API, e.g. as part of external scripts?

**Comment by MarcelMertens** [comment]
Yes, i do (Node-Red). I think its using the socket-io api.
But i'm wondering why its only during the night.
I will check my flows.

**Comment by MarcelMertens** [comment]
Just checked my flows. You might remember my topic in the pimatic forum regarding the cut-off of values of gas prices. The API i request (tankerkoenig.de) is not returning prices if the gas station is closed.
I will check the native tankerkoenig plugin for pimatic or change my node-red flow

**Comment by mwittig** [comment]
Excellent! As you say Tankerkoenig is not returning prices for closed gas stations this is likely to cause the issue if no valid value (e.g. no value at all or "null"). Looking forward to you findings

**Comment by saxn-paule** [comment]
Could you please provide the id of the gas station? I have no errors at all with the plugin and all of my gas stations are closed at night.
