### ISSUE TITLE
0.9.49 update npm error

### ISSUE THREAD

**Issue by Routout** [pimatic/pimatic#1123]
Got these errors while updating pimatic to 0.9.49

```
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

npm WARN deprecated jayschema@0.3.2: this project is no longer maintained

Error: Cannot find module './dir-reader.js'

at Function.Module._resolveFilename (module.js:325:15)

at Function.Module._load (module.js:276:25)

at Module.require (module.js:353:17)

at require (internal/module.js:12:17)

at Packer.Reader (/home/pi/pimatic-app/node_modules/pimatic/node_modules/npm/node_modules/fstream/lib/reader.js:53:19)

at Packer.DirReader (/home/pi/pimatic-app/node_modules/pimatic/node_modules/npm/node_modules/fstream/lib/dir-reader.js:35:10)

at Packer.IgnoreReader (/home/pi/pimatic-app/node_modules/pimatic/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:68:13)

at new Packer (/home/pi/pimatic-app/node_modules/pimatic/node_modules/npm/node_modules/fstream-npm/fstream-npm.js:23:10)

at pack_ (/home/pi/pimatic-app/node_modules/pimatic/node_modules/npm/lib/utils/tar.js:48:3)

at Object.pack (/home/pi/pimatic-app/node_modules/pimatic/node_modules/npm/lib/utils/tar.js:43:5)

npm ERR! cb() never called!

module.js:327

throw err;

^

Error: Cannot find module 'npm'

at Function.Module._resolveFilename (module.js:325:15)

at Function.Module._load (module.js:276:25)

at Module.require (module.js:353:17)

at require (internal/module.js:12:17)

at Object.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic/ppm.js:9:11)

at Module._compile (module.js:409:26)

at Object.Module._extensions..js (module.js:416:10)

at Module.load (module.js:343:32)

at Function.Module._load (module.js:300:12)

at Function.Module.runMain (module.js:441:10)

module.js:327

throw err;

^

Error: Cannot find module 'npm'

at Function.Module._resolveFilename (module.js:325:15)

at Function.Module._load (module.js:276:25)

at Module.require (module.js:353:17)

at require (internal/module.js:12:17)

at Object.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic/ppm.js:9:11)

at Module._compile (module.js:409:26)

at Object.Module._extensions..js (module.js:416:10)

at Module.load (module.js:343:32)

at Function.Module._load (module.js:300:12)

at Function.Module.runMain (module.js:441:10)

module.js:327

throw err;

^

Error: Cannot find module 'npm'

at Function.Module._resolveFilename (module.js:325:15)

at Function.Module._load (module.js:276:25)

at Module.require (module.js:353:17)

at require (internal/module.js:12:17)

at Object.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic/ppm.js:9:11)

at Module._compile (module.js:409:26)

at Object.Module._extensions..js (module.js:416:10)

at Module.load (module.js:343:32)

at Function.Module._load (module.js:300:12)

at Function.Module.runMain (module.js:441:10)

module.js:327

throw err;

^

Error: Cannot find module 'npm'

at Function.Module._resolveFilename (module.js:325:15)

at Function.Module._load (module.js:276:25)

at Module.require (module.js:353:17)

at require (internal/module.js:12:17)

at Object.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic/ppm.js:9:11)

at Module._compile (module.js:409:26)

at Object.Module._extensions..js (module.js:416:10)

at Module.load (module.js:343:32)

at Function.Module._load (module.js:300:12)

at Function.Module.runMain (module.js:441:10)

module.js:327

throw err;

^

Error: Cannot find module 'npm'

at Function.Module._resolveFilename (module.js:325:15)

at Function.Module._load (module.js:276:25)

at Module.require (module.js:353:17)

at require (internal/module.js:12:17)

at Object.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic/ppm.js:9:11)

at Module._compile (module.js:409:26)

at Object.Module._extensions..js (module.js:416:10)

at Module.load (module.js:343:32)

at Function.Module._load (module.js:300:12)

at Function.Module.runMain (module.js:441:10)
```

If I now try sudo pimatic.js start I get:

```
module.js:327
    throw err;
    ^

Error: Cannot find module 'module-alias'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic/pimatic.js:3:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

**Comment by akicker** [comment]
My solution was to run:
sudo service pimatic stop
**npm install pimatic --prefix pimatic-app --production**
this will update to 0.9.50
sudo pimatic-app/node_modules/pimatic/pimatic.js
exit (control C)
sudo service pimatic start

**Comment by Routout** [comment]
> My solution was to run:
> sudo service pimatic stop
> **npm install pimatic --prefix pimatic-app --production**
> this will update to 0.9.50
> sudo pimatic-app/node_modules/pimatic/pimatic.js
> exit (control C)
> sudo service pimatic start

That worked fine. Thanks.
