### ISSUE TITLE
Uncaught exception - EADDRINUSE Error after device search

### ISSUE THREAD

**Issue by quintz** [pimatic/pimatic#1155]
I enabled the harmony plugin and executed a device search, then I get this error:
`error [pimatic]: An uncaught exception occurred: Error: listen EADDRINUSE: address already in use :::61991
    at Server.setupListenHandle [as _listen2] (net.js:1279:14)
    at listenInCluster (net.js:1327:12)
    at Server.listen (net.js:1414:7)
    at ResponseCollector.start (/home/pi/pimatic-app/node_modules/pimatic-harmonyhub/node_modules/harmonyhubjs-discover/lib/responseCollector.js:33:6)
    at Explorer.start (/home/pi/pimatic-app/node_modules/pimatic-harmonyhub/node_modules/harmonyhubjs-discover/lib/explorer.js:74:26)
    at DeviceManager.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-harmonyhub/harmonyhub.coffee:146:37)
    at DeviceManager.emit (events.js:203:15)
    at DeviceManager.discoverDevices (/home/pi/pimatic-app/node_modules/pimatic/lib/devices.coffee:1623:8)
    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/decl-api/index.js:265:36
    at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/method.js:39:29)
    at callActionFromReq (/home/pi/pimatic-app/node_modules/pimatic/node_modules/decl-api/index.js:263:26)
    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/decl-api/index.js:362:14
    at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/method.js:39:29)
    at callActionFromReqAndRespond (/home/pi/pimatic-app/node_modules/pimatic/node_modules/decl-api/index.js:360:24)
    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/decl-api/index.js:443:18
    at Layer.handle [as handle_request] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:335:12)
    at next (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:275:10)
    at next (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/route.js:127:14)
    at /home/pi/pimatic-app/node_modules/pimatic/lib/framework.coffee:1021:19
    at Layer.handle [as handle_request] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:335:12)
    at next (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:275:10)
    at /home/pi/pimatic-app/node_modules/pimatic/lib/framework.coffee:336:18
    at Layer.handle [as handle_request] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:317:13)
    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:335:12)
    at next (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:275:10)
    at _cookieSession (/home/pi/pimatic-app/node_modules/pimatic/node_modules/cookie-session/index.js:126:5)
    at Layer.handle [as handle_request] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:317:13)
    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:335:12)
    at next (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:275:10)
    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/home/pi/pimatic-app/node_modules/pimatic/node_modules/raw-body/index.js:224:16)
    at done (/home/pi/pimatic-app/node_modules/pimatic/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/home/pi/pimatic-app/node_modules/pimatic/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
 This is most probably a bug in pimatic or in a module, please report it! `

Followed up by 

ˋ error [pimatic]: An uncaught exception occurred: Error: bind EADDRINUSE 0.0.0.0:5224
    at state.handle.lookup (dgram.js:242:18)
    at process._tickCallback (internal/process/next_tick.js:63:19)
 This is most probably a bug in pimatic or in a module, please report it! ˋ

Any thought on this?
The plug-in worked at some point for me, now I can’t get it to work...

**Comment by michbeck100** [comment]
Seems like port 5224 is in use. You should fix this first
