### ISSUE TITLE
An uncaught exception occurred: Error: getaddrinfo -3008

### ISSUE THREAD

**Issue by carlptr** [pimatic/pimatic#1156]
Since this afternoon I receive the following error at the end of the pimatic startup

20:54:42.681 [pimatic] An uncaught exception occurred: Error: getaddrinfo -3008
20:54:42.681 [pimatic]>    at errnoException (/space/d02/root_home/pimatic-app.0.9.5/node_modules/mdns/lib/resolver_sequence_tasks.js:199:11)
20:54:42.681 [pimatic]>    at getaddrinfo_complete (/space/d02/root_home/pimatic-app.0.9.5/node_modules/mdns/lib/resolver_sequence_tasks.js:112:10)
20:54:42.681 [pimatic]>    at GetAddrInfoReqWrap.oncomplete (/space/d02/root_home/pimatic-app.0.9.5/node_modules/mdns/lib/resolver_sequence_tasks.js:120:9)
20:54:42.681 [pimatic]> This is most probably a bug in pimatic or in a module, please report it!
20:54:42.685 [pimatic] shutting pimatic down...
/space/d02/root_home/pimatic-app.0.9.5/node_modules/pimatic/startup.coffee:100
          return framework.destroy().then(function() {
          ^

ReferenceError: framework is not defined
    at process.uncaughtException (/space/d02/root_home/pimatic-app.0.9.5/node_modules/pimatic/startup.coffee:100:11)
    at process.emit (events.js:182:13)
    at process.EventEmitter.emit (domain.js:442:20)
    at process._fatalException (internal/bootstrap/node.js:472:27)

I've installed a plugin (pimatic-nuki) today. I already deactivated it now. Perhaps some other module was updated by that and causes the error?
Thanks for any hints.

**Comment by carlptr** [comment]
This morning after testing with several different plugin active configs pimatic starts as usually even with the same config that did not work yesterday. I suppose it was causes by a network issue.
