### ISSUE TITLE
pimatic not starting:  Startup error: TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

### ISSUE THREAD

**Issue by carlptr** [pimatic/pimatic#1171]
Hi All,

Today my pimatic instance stopped working. Restarting fails:

15:52:52.690 2021-12-29 Wednesday
15:52:59.235 [pimatic] Starting pimatic version 0.9.54
15:52:59.247 [pimatic] Node.js version 10.24.1
15:52:59.250 [pimatic] OpenSSL version 1.1.1k
15:54:01.845 [pimatic] Startup error: TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
15:54:01.845 [pimatic]>    at Timeout._onTimeout (/root/pimatic-app/node_modules/pimatic/node_modules/knex/lib/client.js:287:18)
15:54:01.845 [pimatic]>    at ontimeout (timers.js:436:11)
15:54:01.845 [pimatic]>    at tryOnTimeout (timers.js:300:5)
15:54:01.845 [pimatic]>    at listOnTimeout (timers.js:263:5)
15:54:01.845 [pimatic]>    at Timer.processTimers (timers.js:223:10)
15:54:01.859 [pimatic] exiting...

I'll try to re-install and see if the problem persists. Any other ideas? Thanks.

**Comment by carlptr** [comment]
After a clean up of the database as described here https://forum.pimatic.org/topic/14/database-tips my pimatic instance is working again.
