### ISSUE TITLE
SQL Error 403

### ISSUE THREAD

**Issue by wuschel1337** [pimatic/pimatic#393]
Hello can u help me, i installed pimatic fresh but i cant use the webinterface...
Its an SQL Error 

21:32:21.408 2014-11-23 Sunday
21:32:33.415 [pimatic] info: Starting pimatic version 0.8.27
21:32:38.076 [pimatic] info: Installing database package sqlite3
21:32:47.109 [pimatic, npm] info: http GET https://registry.npmjs.org/sqlite3
21:33:17.750 [pimatic, npm] info: http GET https://registry.npmjs.org/nan
21:33:23.825 [pimatic, npm] info: > sqlite3@3.0.4 install /home/pi/pimatic-app/node_modules/sqlite3
21:33:23.893 [pimatic, npm] info: > node-pre-gyp install --fallback-to-build
21:33:32.966 [pimatic, npm] info: node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/node-v11-linux-arm.tar.gz
21:33:34.444 [pimatic, npm] info: node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/node-v11-linux-arm.tar.gz
21:33:34.526 [pimatic, npm] info: node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/node-v11-linux-arm.tar.gz (falling back to source compile with node-gyp)

**Comment by jjayjays** [comment]
Hello, 
i have the same problem... but the answers do not work for me.

sudo node /home/pi/pimatic-app/node_modules/pimatic/pimatic.js:
21:34:20.016 [pimatic] Starting pimatic version 0.9.37
Knex: run
$ npm install sqlite3 --save
Error: Cannot find module '/home/pi/pimatic-app/node_modules/sqlite3/lib/binding/node-v46-linux-arm/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pi/pimatic-app/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (/home/pi/pimatic-app/node_modules/pimatic/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Client_SQLite3._driver (/home/pi/pimatic-app/node_modules/pimatic/node_modules/knex/lib/dialects/sqlite3/index.js:75:12)
    at Client_SQLite3.initializeDriver (/home/pi/pimatic-app/node_modules/pimatic/node_modules/knex/lib/client.js:211:26)
    at Client_SQLite3.Client (/home/pi/pimatic-app/node_modules/pimatic/node_modules/knex/lib/client.js:105:10)
    at new Client_SQLite3 (/home/pi/pimatic-app/node_modules/pimatic/node_modules/knex/lib/dialects/sqlite3/index.js:58:20)
    at Knex (/home/pi/pimatic-app/node_modules/pimatic/node_modules/knex/lib/index.js:60:34)
    at /home/pi/pimatic-app/node_modules/pimatic/lib/database.coffee:71:17
    at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

I remove the sqlite3:
sudo rm -rf /home/pi/pimatic-app/node_modules_sqlite3

and again sudo node /home/pi/pimatic-app/node_modules/pimatic/pimatic.js:
but is the same output 
can somebody help me?

sorry about my english... is not the best
