### ISSUE TITLE
pimatic frequent crash : how to debug?

### ISSUE THREAD

**Issue by Yves911** [pimatic/pimatic#443]
my pimatic installation crash very often since about 1 week.

My setup is the following :
- pimatic running on a raspberry pi (model B)
- pimatic is connected to an arduino with homeduino
- the raspberry pi filesystem is on an external disk (to avoid SD corruption things)
- node.js version is v0.10.24

To enable debugging i have the following params into the pimatic config:
```
"settings": {
    "debug": true,
    "logLevel": "debug"
```

Unfortunately i have random crashes, for examples

```
20:49:34.207 [pimatic-homeduino] received: [ 688, 1970, 4264, 10088 ] 020102010201010202010201020101020201010202010102010201020201020101020201010202010201020102010201020102010201020102010201010202010102010201020201020102010102010202010102020101020201020102010201020103
20:49:34.251 [pimatic-homeduino] generic:  { id: 1111, type: 2, positive: true, value: 378528 }
20:49:42.920 [pimatic-homeduino] data: "RF receive 552 2105 4265 8452 0 0 0 0 0101020101010101020201010102010101010202010101020101010201010102010201010101010102010303"
20:49:42.961 [pimatic-homeduino] received: [ 552, 2105, 4265, 8452 ] 0101020101010101020201010102010101010202010101020101010201010102010201010101010102010303
20:49:43.005 [pimatic-homeduino] weather3:  { id: 131, channel: 2, temperature: -0.2, humidity: 84 }
20:49:43.085 [pimatic-homeduino] data: "ERR checksum_error"
20:49:43.137 [pimatic-homeduino] got checksum_error while reading dht sensor, retrying: 0 of 5
20:49:43.378 [pimatic-homeduino] data: "RF receive 520 2139 4299 8452 0 0 0 0 0101020101010101020201010102010101010202010101020101010201010102010201010101010102010303"
20:49:43.420 [pimatic-homeduino] received: [ 520, 2139, 4299, 8452 ] 0101020101010101020201010102010101010202010101020101010201010102010201010101010102010303
20:49:43.462 [pimatic-homeduino] weather3:  { id: 131, channel: 2, temperature: -0.2, humidity: 84 }
20:49:45.692 [pimatic-homeduino] data: "ACK 19.1 55.3"
20:49:51.066 [pimatic-homeduino] data: "RF receive 688 4264 1971 10088 0 0 0 0 010201020102020101020102010202010102020101020201020102010102010202010102020101020102010201020102010201020102010201020102020101020201020102010102010201020201020101020201010202010102010201020201020103"
20:49:51.109 [pimatic-homeduino] received: [ 688, 1971, 4264, 10088 ] 020102010201010202010201020101020201010202010102010201020201020101020201010202010201020102010201020102010201020102010201010202010102010201020201020102010102010202010102020101020201020102010102010203
20:49:51.153 [pimatic-homeduino] generic:  { id: 1111, type: 2, positive: true, value: 378531 }
20:49:54.753 [pimatic-homeduino] data: "ACK 19.1 55.3"
20:50:04.556 [pimatic-mobile-frontend] rendering theme: graphite/water
coffee-cache: compiling coffee-script file "themes/graphite/water.coffee"...Done
coffee-cache: compiling coffee-script file "themes/graphite/base.coffee"...Done
20:50:05.805 [pimatic-homeduino] data: "PING"
20:50:10.134 [pimatic-mobile-frontend] rendering theme finished
20:50:10.307 [pimatic-homeduino] data: "RF receive 688 4264 1969 10092 0 0 0 0 010201020102020101020102010202010102020101020201020102010102010202010102020101020102010201020102010201020102010201020102020101020201020102010102010201020201020101020201010202010102010202010201020103"
20:50:10.335 [pimatic-homeduino] received: [ 688, 1969, 4264, 10092 ] 020102010201010202010201020101020201010202010102010201020201020101020201010202010201020102010201020102010201020102010201010202010102010201020201020102010102010202010102020101020201020101020102010203
20:50:10.399 [pimatic-homeduino] generic:  { id: 1111, type: 2, positive: true, value: 378535 }
20:50:12.032 [pimatic-homeduino] data: "RF receive 532 1914 3924 7800 0 0 0 0 0101020201020102010101010101010102020201010201020102010102010101020201010101010102010303"
20:50:12.089 [pimatic-homeduino] received: [ 532, 1914, 3924, 7800 ] 0101020201020102010101010101010102020201010201020102010102010101020201010101010102010303
20:50:12.147 [pimatic-homeduino] weather3:  { id: 212, channel: 1, temperature: 11.5, humidity: 50 }
20:50:12.473 [pimatic-homeduino] data: "RF receive 489 1958 3970 7812 0 0 0 0 0101020201020102010101010101010102020201010201020102010102010101020201010101010102010303"
20:50:12.507 [pimatic-homeduino] received: [ 489, 1958, 3970, 7812 ] 0101020201020102010101010101010102020201010201020102010102010101020201010101010102010303
20:50:12.539 [pimatic-homeduino] weather3:  { id: 212, channel: 1, temperature: 11.5, humidity: 50 }
20:50:24.759 [pimatic-homeduino] data: "ACK 19.1 55.2"
20:50:25.255 [pimatic-homeduino] data: "RF receive 687 4266 1970 10084 0 0 0 0 010201020102020101020102010202010102020101020201020102010102010202010102020101020102010201020102010201020102010201020102020101020201020102010102010201020201020101020201010202010102020101020201010203"
20:50:25.309 [pimatic-homeduino] received: [ 687, 1970, 4266, 10084 ] 020102010201010202010201020101020201010202010102010201020201020101020201010202010201020102010201020102010201020102010201010202010102010201020201020102010102010202010102020101020201010202010102020103
20:50:25.361 [pimatic-homeduino] generic:  { id: 1111, type: 2, positive: true, value: 378538 }
Segmentation fault
```

How can i make pimatic more verbose or how can i track where the issue is coming from?

**Comment by ako82** [comment]
I disabled the plugin.
I had also tried all Hardware variations before. 3,3v + 5v mixed with 4700 and 10000 Ohm.

**Comment by Yves911** [comment]
@ako82, sorry i wasn't clear enough where your DHT was connected to : raspberry or arduino?

**Comment by sweetpi** [comment]
`Segmentation fault` means that the node.js process crash while executing some native code (not js). 

@Yves911 What plugins do you have in use?

I never had to debug a segmentation fault in node, but [node-segfault-handler](https://github.com/ddopson/node-segfault-handler) looks like a nice tool. Do the following:

```
cd pimatic-app/node_modules/pimatic
npm install segfault-handler
```

And add these two lines after the first line in `pimatic.js`:

```
var SegfaultHandler = require('segfault-handler');
SegfaultHandler.registerHandler();
```

and restart it. Hopefully the next crash then outputs something useful.

**Comment by Yves911** [comment]
Thanks!

Here is the full list of plugins that i am using
```
11:23:56.467 [pimatic] info: loading plugin: "pimatic-links" (0.8.5)
11:23:56.720 [pimatic] info: loading plugin: "pimatic-homeduino" (0.8.31)
11:23:57.783 [pimatic] info: loading plugin: "pimatic-mail" (0.8.2)
11:23:59.695 [pimatic] info: loading plugin: "pimatic-log-reader" (0.8.2)
11:23:59.905 [pimatic] info: loading plugin: "pimatic-cron" (0.8.3)
11:24:00.489 [pimatic] info: loading plugin: "pimatic-mobile-frontend" (0.8.31)
11:24:03.739 [pimatic] info: loading plugin: "pimatic-shell-execute" (0.8.1)
11:24:03.934 [pimatic] info: loading plugin: "pimatic-filebrowser" (0.8.0)
11:24:03.989 [pimatic] warn: package.json of "pimatic-filebrowser" has no "configSchema" property. Could not validate config.
11:24:04.012 [pimatic] info: loading plugin: "pimatic-pushbullet" (0.8.4)
11:24:07.264 [pimatic] info: loading plugin: "pimatic-sysinfo" (0.8.10)
11:24:07.750 [pimatic] info: loading plugin: "pimatic-weather" (0.8.8)
11:24:12.479 [pimatic] info: loading plugin: "pimatic-ping" (0.8.3)
```
I will give a try to segfault-handler and let you know the result...

**Comment by Yves911** [comment]
My guess (but no evidence here) is that pimatic-homeduino is causing the trouble. This trouble wasn't there 1 or 2 weeks ago. So could i install a previous version of pimatic-homeduino and check if problem still exists? It should be possible to isolate the issue.
So how can i install an old version of pimatic-homeduino?

**Comment by Yves911** [comment]
the crash seems to be linked to this rule:
```
if its20 and [$homeduino-temperature.temperature < $dummy-heating.temperatureSetpoint] 
then 
log \"Allumage Chaudière {date()}, température $homeduino-temperature.temperature° -> $dummy-heating.temperatureSetpoint° pour $heattime minutes\" 
and 
switch chaudiere off 
and
switch chaudiere on after 10 seconds for $heattime minutes 
and 
pushbullet title:\"Allumage chaudière {date()}\" message:\"Température du salon $homeduino-temperature.temperature°C, température de consigne $dummy-heating.temperatureSetpoint°C, temps de chauffe $heattime minutes\"
```

I have replaced recently my buttons based config to a dummy-heating heating one and it seems to be the root cause.. why exactly i don't know...

**Comment by sweetpi** [comment]
Hm strange, can't imagine that it has something to do with the rule / dummy device. If I look at your plugin list I would guess that it is the homeduino plugin or more precisely the node-serialport module.

Which version of node-serialport is installed?

```
cd pimatic-app/node_modules/pimatic-homeduino
npm list
```

I was running with serialport v1.4.9 and had no problems and now updated to 1.4.10 and will test.

**Comment by Yves911** [comment]
yes it's very strange also to me, but it seems to be the case.
about npm list this is what i have:
```
pimatic-homeduino@0.8.31 /root/pimatic-git/node_modules/pimatic-homeduino
├─┬ homeduino@0.0.25
│ ├── bluebird@2.2.2
│ ├── otaat-repl@1.0.2
│ ├── rfcontroljs@0.0.20
│ └─┬ serialport@1.4.10
│   ├── async@0.9.0
│   ├── bindings@1.2.1
│   ├── nan@1.3.0
│   ├─┬ node-pre-gyp@0.5.19
│   │ ├─┬ mkdirp@0.5.0
│   │ │ └── minimist@0.0.8
│   │ ├─┬ nopt@2.2.1
│   │ │ └── abbrev@1.0.5
│   │ ├─┬ npmlog@0.0.6
│   │ │ └── ansi@0.2.1
│   │ ├─┬ rc@0.4.0
│   │ │ ├── deep-extend@0.2.10
│   │ │ ├── ini@1.1.0
│   │ │ ├── minimist@0.0.10
│   │ │ └── strip-json-comments@0.1.3
│   │ ├─┬ request@2.36.0
│   │ │ ├── aws-sign2@0.5.0
│   │ │ ├── forever-agent@0.5.2
│   │ │ ├─┬ form-data@0.1.2
│   │ │ │ ├── async@0.2.10
│   │ │ │ └─┬ combined-stream@0.0.4
│   │ │ │   └── delayed-stream@0.0.5
│   │ │ ├─┬ hawk@1.0.0
│   │ │ │ ├── boom@0.4.2
│   │ │ │ ├── cryptiles@0.2.2
│   │ │ │ ├── hoek@0.9.1
│   │ │ │ └── sntp@0.2.4
│   │ │ ├─┬ http-signature@0.10.0
│   │ │ │ ├── asn1@0.1.11
│   │ │ │ ├── assert-plus@0.1.2
│   │ │ │ └── ctype@0.5.2
│   │ │ ├── json-stringify-safe@5.0.0
│   │ │ ├── mime@1.2.11
│   │ │ ├── node-uuid@1.4.1
│   │ │ ├── oauth-sign@0.3.0
│   │ │ ├── qs@0.6.6
│   │ │ ├─┬ tough-cookie@0.12.1
│   │ │ │ └── punycode@1.2.4
│   │ │ └── tunnel-agent@0.4.0
│   │ ├── rimraf@2.2.8
│   │ ├── semver@2.3.0
│   │ ├─┬ tar@0.1.19
│   │ │ ├── block-stream@0.0.7
│   │ │ ├─┬ fstream@0.1.25
│   │ │ │ ├── graceful-fs@2.0.3
│   │ │ │ └── mkdirp@0.3.5
│   │ │ └── inherits@2.0.1
│   │ └─┬ tar-pack@2.0.0
│   │   ├── debug@0.7.4
│   │   ├─┬ fstream@0.1.25
│   │   │ ├── graceful-fs@2.0.3
│   │   │ ├── inherits@2.0.1
│   │   │ └── mkdirp@0.3.5
│   │   ├─┬ fstream-ignore@0.0.7
│   │   │ ├── inherits@2.0.1
│   │   │ └─┬ minimatch@0.2.14
│   │   │   ├── lru-cache@2.5.0
│   │   │   └── sigmund@1.0.0
│   │   ├── graceful-fs@1.2.3
│   │   ├── once@1.1.1
│   │   ├─┬ readable-stream@1.0.27-1
│   │   │ ├── core-util-is@1.0.1
│   │   │ ├── inherits@2.0.1
│   │   │ ├── isarray@0.0.1
│   │   │ └── string_decoder@0.10.25-1
│   │   └── uid-number@0.0.3
│   ├─┬ optimist@0.6.1
│   │ ├── minimist@0.0.10
│   │ └── wordwrap@0.0.2
│   └── sf@0.1.7
└── UNMET DEPENDENCY pimatic 0.8.*

npm ERR! missing: pimatic@0.8.*, required by pimatic-homeduino@0.8.31
npm ERR! not ok code 0
```

**Comment by Yves911** [comment]
I don't have any crashes now, root of the trouble is unclear and seems to be linked to rules and dummy-heating.
For now we can close this issue (and if someone encounter same issue reopen)

**Comment by Yves911** [comment]
Unfortunately I still had some crashes...
Since yesterday evening no crash anymore (i have downgraded the pimatic frontend to 0.8.27)
Could crash be linked to pimatic-mobile-frontend? I have noticed that crashes happen mostly during pimatic startup or when accessing or playing with the web UI...

**Comment by Yves911** [comment]
I *may* have something interesting here,right before crash i have the following:
```
TypeError: Cannot read property 'length' of undefined
    at Function.Buffer.concat (buffer.js:491:20)
    at afterRead (/root/pimatic-git/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/serialport.js:323:36)
    at /root/pimatic-git/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/serialport.js:342:9
    at Object.wrapper [as oncomplete] (fs.js:454:17)
```
All modules are up to date

**Comment by Icesory** [comment]
Which arduino do you use?

**Comment by Yves911** [comment]
> Which arduino do you use?  

arduino nano 3 clone with an atmega328

**Comment by sweetpi** [comment]
I've added some debug flags and outputs to the node-serialport module, maybe this gives us a more verbose stack trace. I really don't think it is gui related. I think that there is some buffer that gets full / a overflow if there is too much serial port communication and pimatic is bussy with something else. 

Please do the following to install node-seriaport mit debug outputs:
```
cd pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules
rm -rf serialport
npm install sweetpi/node-serialport
```

You should now get a `SERIALPORT: _read` for every read from serial port and hopefully a stack trash when the Segmentation fault happens.

**Comment by Yves911** [comment]
thanks, this is what i get now
```
SERIALPORT: _read
PID 13464 received SIGSEGV for address: 0x0
```
and
```
SERIALPORT: _read
SERIALPORT: _read
SERIALPORT: _read
12:16:02.086 [pimatic-homeduino] data: "RF receive 941 342 8936 0 0 0 0 0 01101001010110101010011010010110101010100110101012"
12:16:02.111 [pimatic-homeduino] received: [ 342, 941, 8936 ] 10010110101001010101100101101001010101011001010102
12:16:02.136 [pimatic-homeduino] switch5:  { id: 408991, unit: 0, all: true, state: true }
SERIALPORT: _read
SERIALPORT: _read
PID 13520 received SIGSEGV for address: 0x0
```

**Comment by sweetpi** [comment]
Is there a `stacktrace-xxx-xxx.log` file in the pimatic directory? (https://github.com/ddopson/node-segfault-handler/blob/master/src/segfault-handler.cpp#L35)

**Comment by Yves911** [comment]
Yes, but the info is not more detailled 
```
stacktrace-1420456815-13740.log:
PID 13740 received SIGSEGV for address: 0xec
```
My **impression** is that when i get this kind of errors if try to restart again pimatic most of the time it will fail with the same error.
If i restart the pi, then most of the time it will start without error.
The arduino is connected to a hub so i don't know if it get reset when i restart the pi.

**Comment by sweetpi** [comment]
So: http://stackoverflow.com/questions/24700150/on-raspberry-pi-backtrace-returns-0-frames

I updated `sweetpi/node-serialport` with the right compilation flags. So could you rerun:

```
cd pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules
rm -rf serialport
npm install sweetpi/node-serialport
```

and test again?

**Comment by Yves911** [comment]
So after
```
rm -rf serialport/

root@raspberrypi:~/pimatic-git/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules# npm install sweetpi/node-serialport
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/node-pre-gyp
npm http GET https://registry.npmjs.org/bindings/1.2.1
npm http GET https://registry.npmjs.org/async/0.9.0
npm http GET https://registry.npmjs.org/sf/0.1.7
npm http GET https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/node-pre-gyp
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/bindings/1.2.1
npm http 304 https://registry.npmjs.org/async/0.9.0
npm http 304 https://registry.npmjs.org/sf/0.1.7
npm http GET https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/minimist

> serialport@1.4.10 install /root/pimatic-git/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport
> node-pre-gyp build --debug

make: Entering directory '/root/pimatic-git/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/build'
  CXX(target) Debug/obj.target/serialport/src/serialport.o
  CXX(target) Debug/obj.target/serialport/src/serialport_unix.o
  CXX(target) Debug/obj.target/serialport/src/serialport_poller.o
  SOLINK_MODULE(target) Debug/obj.target/serialport.node
  SOLINK_MODULE(target) Debug/obj.target/serialport.node: Finished
  COPY Debug/serialport.node
  COPY /root/pimatic-git/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/build/serialport/v1.4.10/Debug/node-v11-linux-arm/serialport.node
  TOUCH Debug/obj.target/action_after_build.stamp
make: Leaving directory '/root/pimatic-git/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/build'
serialport@1.4.10 serialport
├── bindings@1.2.1
├── sf@0.1.7
├── async@0.9.0
├── nan@1.3.0
├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)
└── node-pre-gyp@0.5.31
```
Same result :
```
14:22:46.275 [pimatic] [ReferenceError: err is not defined]
SERIALPORT: _read
PID 7049 received SIGSEGV for address: 0x0
```
more stacktrace-1420464166-7049.log
```
PID 7049 received SIGSEGV for address: 0x0
```

**Comment by sweetpi** [comment]
Ok let's do it the hard way, please use gdb:

```
cd pimatic-app
sudo gdb node
```

you should now have a gdb shell open: Type:

```
run node_modules/pimatic/pimatic.js
```

After it crashed type:

```
backtrace
```

**Comment by Yves911** [comment]
Okay, here is the result:
SERIALPORT: _read

Program received signal SIGSEGV, Segmentation fault.
0x007316b8 in ?? ()
(gdb) backtrace
```
#0  0x007316b8 in ?? ()
#1  0x0052f1dc in uv__io_poll (loop=0x6ea788, timeout=0) at ../deps/uv/src/unix/linux-core.c:263
#2  0x005240a4 in uv_run (loop=0x6ea788, mode=<optimized out>) at ../deps/uv/src/unix/core.c:317
#3  0x003f8404 in node::Start(int, char**) ()
#4  0xb6d0082c in __libc_start_main () from /lib/arm-linux-gnueabihf/libc.so.6
#5  0x0016adfc in _start ()
```

**Comment by sweetpi** [comment]
Damn almost there. But the important line is the one with the question-signs....

**Comment by Yves911** [comment]
:-)

**Comment by sweetpi** [comment]
So one more reinstall of node-serialport from my repo and it should expose the error :)

**Comment by Yves911** [comment]
I am trying to reproduce the crash now, but as usual in this situation : you can't :-)

**Comment by Yves911** [comment]
Ok here is the result:
```
Program received signal SIGSEGV, Segmentation fault.
0xffffff6a in ?? ()
(gdb) backtrace
#0  0xffffff6a in ?? ()
#1  0x0000f2a6 in ?? ()
#2  0x0000f2a6 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by sweetpi** [comment]
ok I think its not the serialport module. I produced an segfault in the serialport module and I get the function name and line number...

But the only two left with native modules are ping and sysinfo. Can you disable the two and test if it still segaults?

**Comment by Yves911** [comment]
I am closing this issue:
- pimatic is stable when running
- pimatic start with no problem if raspberry has been rebooted
so the issue is not solved, but for me it's manageable like this...
If someone encounter the same issue he can reopen this issue.

**Comment by KlausFeld** [comment]
Hi, I still have the Problems with the homeduino plugin and the arduino nano. My log tells this:

Disconnect completed
11:12:23.513 [pimatic-homeduino] warn: Couldn't connect (Serialport not open.), retrying...
11:12:23.521 [pimatic-homeduino] warn: Couldn't connect (Serialport not open.), retrying...

What can I check?

**Comment by Icesory** [comment]
For this stuff please use the forum.pimatic.org
