### ISSUE TITLE
DHTxx plugin installation

### ISSUE THREAD

**Issue by Gargoyle112** [pimatic/pimatic#477]
Hi!

I tried to start pimatic with the DHTxx plugin for the first time and this occurs:

```
sudo pimatic.js
02:25:03.377 2015-01-17 Saturday
02:25:19.413 [pimatic] Starting pimatic version 0.8.36
02:25:25.548 [pimatic] loading plugin: "pimatic-pilight" (0.8.5)
02:25:26.098 [pimatic] loading plugin: "pimatic-sispmctl" (0.8.2)
02:25:26.357 [pimatic] Installing: "dhtxx"
02:25:37.708 [pimatic, npm] http GET https://registry.npmjs.org/pimatic-dhtxx
02:25:40.810 [pimatic, npm] http GET https://registry.npmjs.org/node-dht-sensor
02:25:43.030 [pimatic, npm] > node-dht-sensor@0.0.5 install /home/pi/pimatic-app/node_modules/pimatic-dhtxx/node_modules/node-dht-sensor
02:25:43.116 [pimatic, npm] > node-gyp rebuild
02:25:52.679 [pimatic, npm] make: Entering directory '/home/pi/pimatic-app/node_modules/pimatic-dhtxx/node_modules/node-dht-sensor/build'
02:25:52.790 [pimatic, npm]   CXX(target) Release/obj.target/node-dht-sensor/node-dht-sensor.o
02:25:53.670 [pimatic, npm] ../node-dht-sensor.cpp:21:21: fatal error: bcm2835.h: Datei oder Verzeichnis nicht gefunden
02:25:53.977 [pimatic, npm] compilation terminated.
02:25:56.189 [pimatic, npm] node-dht-sensor.target.mk:79: recipe for target 'Release/obj.target/node-dht-sensor/node-dht-sensor.o' failed
02:25:56.263 [pimatic, npm] make: Leaving directory '/home/pi/pimatic-app/node_modules/pimatic-dhtxx/node_modules/node-dht-sensor/build'
02:25:56.370 [pimatic, npm] make: *** [Release/obj.target/node-dht-sensor/node-dht-sensor.o] Error 1
02:25:56.455 [pimatic, npm] gyp ERR! build error
02:25:56.553 [pimatic, npm] gyp ERR! stack Error: `make` failed with exit code: 2
02:25:56.658 [pimatic, npm] gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
02:25:56.744 [pimatic, npm] gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
02:25:56.832 [pimatic, npm] gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
02:25:56.941 [pimatic, npm] gyp ERR! System Linux 3.12.35+
02:25:57.034 [pimatic, npm] gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
02:25:57.126 [pimatic, npm] gyp ERR! cwd /home/pi/pimatic-app/node_modules/pimatic-dhtxx/node_modules/node-dht-sensor
02:25:57.223 [pimatic, npm] gyp ERR! node -v v0.10.21
02:25:57.327 [pimatic, npm] gyp ERR! node-gyp -v v0.10.10
02:25:57.408 [pimatic, npm] gyp ERR! not ok
02:25:57.465 [pimatic, npm] ERR! weird error 1
02:25:57.522 [pimatic, npm] ERR! not ok code 0
02:25:57.677 [pimatic] Error running "npm install pimatic-dhtxx"
02:25:58.973 [pimatic] loading plugin: "pimatic-cron" (0.8.5)
02:26:02.898 [pimatic] loading plugin: "pimatic-mobile-frontend" (0.8.38)
02:26:10.474 [pimatic-cron] the time is: Sat Jan 17 2015 02:26:10 GMT+0100 (CET)
02:26:15.339 [pimatic] new device "Beleuchtung"...
02:26:15.657 [pimatic] new device "Spots"...
02:26:15.829 [pimatic] new device "Nebel"...
02:26:15.991 [pimatic] new device "LEER"...
02:26:16.048 [pimatic] no plugin found for device "my-sensor" of class "DHTxxSensor"!
```

Here is my config file:
```json
{
  "//": "Please only change this file when pimatic is NOT running else pimatic will overwrite your changes.",
  "settings": {
    "httpServer": {
      "enabled": true,
      "port": 80
    },
    "database": {
      "deviceAttributeLogging": [
        {
          "deviceId": "*",
          "attributeName": "*",
          "time": "7d"
        },
        {
          "deviceId": "*",
          "attributeName": "temperature",
          "time": "1y"
        },
        {
          "deviceId": "*",
          "attributeName": "humidity",
          "time": "1y"
        }
      ],
      "messageLogging": [
        {
          "level": "*",
          "tags": [],
          "time": "7d"
        }
      ]
    },
    "authentication": {
      "secret": "<<<SECRET ;-)>>>"
    },
    "httpsServer": {},
    "gui": {}
  },
  "plugins": [
    {
      "plugin": "pilight"
    },
    {
      "plugin": "sispmctl"
    },
    {
      "plugin": "dhtxx"
    },
    {
      "plugin": "cron"
    },
    {
      "plugin": "mobile-frontend"
    }
  ],
  "devices": [
    {
      "id": "environment",
      "class": "SispmctlSwitch",
      "name": "Beleuchtung",
      "outletUnit": 1
    },
    {
      "id": "spot",
      "class": "SispmctlSwitch",
      "name": "Spots",
      "outletUnit": 2
    },
    {
      "id": "Fogger",
      "class": "SispmctlSwitch",
      "name": "Nebel",
      "outletUnit": 3
    },
    {
      "id": "free",
      "class": "SispmctlSwitch",
      "name": "LEER",
      "outletUnit": 4
    },
    {
      "id": "my-sensor",
      "name": "HeatSpot",
      "class": "DHTxxSensor",
      "type": 22,
      "gpio": 7,
      "interval": 50000
    }
  ],
  "rules": [
    {
      "id": "grundbeleuchtung",
      "name": "Licht an",
      "rule": "if its 8:00 then turn on Beleuchtung",
      "active": true,
      "logging": true
    },
    {
      "id": "licht-aus",
      "name": "Licht aus",
      "rule": "if its 22:00 then turn off Beleuchtung",
      "active": true,
      "logging": true
    }
  ],
  "pages": [
    {
      "id": "favourite",
      "name": "Favourites",
      "devices": [
        {
          "deviceId": "environment"
        },
        {
          "deviceId": "spot"
        },
        {
          "deviceId": "Fogger"
        }
      ]
    }
  ],
  "groups": [],
  "users": [
    {
      "username": "<<<NAME>>>",
      "password": "<<<PASS>>>",
      "role": "admin"
    }
  ],
  "roles": [
    {
      "name": "admin",
      "permissions": {
        "pages": "write",
        "rules": "write",
        "variables": "write",
        "messages": "write",
        "events": "write",
        "devices": "write",
        "groups": "write",
        "plugins": "write",
        "updates": "write",
        "controlDevices": true,
        "restart": true
      }
    }
  ],
  "variables": []
}
```

THX for the help

**Comment by sweetpi** [comment]
The node-sensors plugins needed by the dht plugin says:
 
```
This module uses the BCM2835 library that requires access to /open/mem. Because of this, you will typically run node with admin privileges.
```

I think you have to install the lib first: http://www.airspayce.com/mikem/bcm2835/

@wutu is this correct? Maybe we should add this notice to the readme.

**Comment by DDNRN** [comment]
Yes i think it's right, had to install the BCM2835 lib first to get it work.
It took me a few time to find something about the driver until i found this page from your link above.   

For beginners it would maybe better to include any kind of automatic install of this, or give any notification about it, at least some more text in the Logfile.

**Comment by Gargoyle112** [comment]
Yo, pimatic is running!
But now, I have another problem with the DHT sensor. Can I post this here or should I open another thread?

**Comment by Gargoyle112** [comment]
How do I mark this issue as closed?

**Comment by sweetpi** [comment]
The button at the bottom.
