### ISSUE TITLE
Updated, failed starting

### ISSUE THREAD

**Issue by sweebee** [pimatic/pimatic#482]
I updated the weather plugin in the GUI and now pimatic won't start:

```
22:40:13.475 [pimatic] error: Unexpected token 
22:40:13.475 [pimatic] error:>
22:40:15.982 [pimatic] debug: SyntaxError: Unexpected token 
22:40:15.982 [pimatic] debug:>
22:40:15.982 [pimatic] debug:>    at Object.parse (native)
22:40:15.982 [pimatic] debug:>    at Object.fStringDouble [as f] (/usr/local/pimatic-app/node_modules/pimatic/node_modules/relaxed-json/relaxed-json.js:109:19)
22:40:15.982 [pimatic] debug:>    at /usr/local/pimatic-app/node_modules/pimatic/node_modules/relaxed-json/relaxed-json.js:58:34
22:40:15.982 [pimatic] debug:>    at some (/usr/local/pimatic-app/node_modules/pimatic/node_modules/relaxed-json/relaxed-json.js:37:13)
22:40:15.982 [pimatic] debug:>    at findToken (/usr/local/pimatic-app/node_modules/pimatic/node_modules/relaxed-json/relaxed-json.js:51:16)
22:40:15.982 [pimatic] debug:>    at /usr/local/pimatic-app/node_modules/pimatic/node_modules/relaxed-json/relaxed-json.js:65:23
22:40:15.982 [pimatic] debug:>    at Object.transform (/usr/local/pimatic-app/node_modules/pimatic/node_modules/relaxed-json/relaxed-json.js:224:18)
22:40:15.982 [pimatic] debug:>    at Framework._loadConfig (/framework.coffee:97:36)
22:40:15.982 [pimatic] debug:>    at new Framework (/framework.coffee:54:8)
22:40:15.982 [pimatic] debug:>    at /startup.coffee:36:21
22:40:15.982 [pimatic] debug:>    at tryCatch1 (/usr/local/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:43:21)
22:40:15.982 [pimatic] debug:>    at Function.Promise$_Try (/usr/local/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:233:11)
22:40:15.982 [pimatic] debug:>    at Object.module.exports.startup (/startup.coffee:35:10)
22:40:15.982 [pimatic] debug:>    at run (/usr/local/pimatic-app/node_modules/pimatic/pimatic.js:15:24)
22:40:15.982 [pimatic] debug:>    at /daemon.coffee:98:9
22:40:15.982 [pimatic] debug:>    at Object.oncomplete (fs.js:107:15)
```

**Comment by sweebee** [comment]
Reinstalled pimatic, now up and running

**Comment by sweetpi** [comment]
Looks like it was a problem while parsing your config file.
