### ISSUE TITLE
When using a "ButtonsDevice" in my config, the rule-parser stops working.

### ISSUE THREAD

**Issue by DavidZH** [pimatic/pimatic#500]
I started implementing pimatic two weeks ago. The first week I was on a skitrip, but that was a good test for the logging. This week I started to fully configure my installation.

The biggest issue I com across is the usage of a ButtonsDevice.

After two days of fighting I'm now adding my devices piece by piece. All the actual hardware adds without a hitch, but now I want a two-way button to be able to select the dimlevel of a light("dinner" or "work"). 
First, the buttons do not render properly, independent of device or browser.
![Uploading Screen Shot 2015-01-23 at 10.44.54.png . . .]()

(**Eettafel level** in the right column)

Next when starting the service I get an error: 
*14:01:49.471 [pimatic] error: Could not force add rule, because error had no rule attribute.
14:01:57.235 [pimatic] error: Could not parse rule "if its 10 minutes before sunset and Nachtlicht is off then turn Nachtlicht on": Illegal object in patterns*
I can use pimatic normally, but I am unable to make new rules. As soon as I start typing in the conditions field I get *"Illegal object in patterns"* popups. The actions field I can use.

Am I doing something wrong?
This is my device:
```
    {
      "id": "set-dimlevel-dining",
      "name": "Eettafel dimmer”,
      "class": "ButtonsDevice",
      "buttons": [
        {
          "id": "level_LO",
          "name": "Eten"
        },
        {
          "id": "level_HI",
          "name": "Werken"
        }
      ]
    }
```

**Comment by sweetpi** [comment]
Could you please enable debug outputs and post the debug output in the logs (https://github.com/pimatic/pimatic/issues/137)?

**Comment by DavidZH** [comment]
Ok, my Linux skills are virtually non-existent (Google and I are bosom buddies now), but I think it doesn't give debug output.
This is my log:
```
16:33:47.360 2015-01-23 Friday
16:33:57.097 [pimatic] info: Starting pimatic version 0.8.37
16:33:57.403 [pimatic] error: Parse error on line 2:
16:33:57.403 [pimatic] error:>...te your changes."  "settings": {    "d
16:33:57.403 [pimatic] error:>----------------------^
16:33:57.403 [pimatic] error:>Expecting 'EOF', '}', ':', ',', ']', got 'STRING'
16:33:59.996 [pimatic] debug: Error: Parse error on line 2:
16:33:59.996 [pimatic] debug:>...te your changes."  "settings": {    "d
16:33:59.996 [pimatic] debug:>----------------------^
16:33:59.996 [pimatic] debug:>Expecting 'EOF', '}', ':', ',', ']', got 'STRING'
16:33:59.996 [pimatic] debug:>    at Object.parseError (/pimatic-app/node_modules/pimatic/node_modules/cjson/node_modules/jsonlint/lib/jsonlint.js:55:11)
16:33:59.996 [pimatic] debug:>    at Object.parse (/pimatic-app/node_modules/pimatic/node_modules/cjson/node_modules/jsonlint/lib/jsonlint.js:132:22)
16:33:59.996 [pimatic] debug:>    at Object.exports.parse (/pimatic-app/node_modules/pimatic/node_modules/cjson/node_modules/jsonlint/lib/jsonlint.js:417:53)
16:33:59.996 [pimatic] debug:>    at Object.exports.parse (/pimatic-app/node_modules/pimatic/node_modules/cjson/index.js:88:28)
16:33:59.996 [pimatic] debug:>    at Framework._loadConfig (/pimatic-app/framework.coffee:97:24)
16:33:59.996 [pimatic] debug:>    at new Framework (/pimatic-app/framework.coffee:54:8)
16:33:59.996 [pimatic] debug:>    at /pimatic-app/startup.coffee:36:21
16:33:59.996 [pimatic] debug:>    at tryCatch1 (/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:43:21)
16:33:59.996 [pimatic] debug:>    at Function.Promise$_Try (/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:233:11)
16:33:59.996 [pimatic] debug:>    at Object.module.exports.startup (/pimatic-app/startup.coffee:35:10)
16:33:59.996 [pimatic] debug:>    at run (/pimatic-app/node_modules/pimatic/pimatic.js:15:24)
16:33:59.996 [pimatic] debug:>    at /pimatic-app/daemon.coffee:98:9
16:33:59.996 [pimatic] debug:>    at Object.oncomplete (fs.js:107:15)
16:38:49.612 2015-01-23 Friday
16:38:59.468 [pimatic] info: Starting pimatic version 0.8.37
16:39:04.203 [pimatic] info: loading plugin: "pimatic-cron" (0.8.5)
16:39:06.576 [pimatic] info: loading plugin: "pimatic-mobile-frontend" (0.8.39)
16:39:10.904 [pimatic] info: loading plugin: "pimatic-homeduino" (0.8.36)
16:39:12.347 [pimatic] info: loading plugin: "pimatic-sunrise" (0.8.0)
16:39:12.624 [pimatic-cron] info: the time is: Fri Jan 23 2015 16:39:12 GMT+0100 (CET)
16:39:13.756 [pimatic-sunrise] info: Your location is set to lat: 52.030293, long: 4.321763
16:39:15.076 [pimatic] info: new device "Lamp achterkamer"...
16:39:15.278 [pimatic] info: new device "Lamp boekenkast"...
16:39:15.431 [pimatic] info: new device "Lamp tafel"...
16:39:15.579 [pimatic] info: new device "Nachtlicht"...
16:39:15.721 [pimatic] info: new device "Temp woonkamer"...
16:39:15.895 [pimatic] info: new device "Actueel weer"...
16:39:16.046 [pimatic] info: new device "Plafondfan"...
16:39:16.200 [pimatic] info: new device "Eettafel dimmer"...
16:39:16.797 [pimatic] error: Could not force add rule, because error had no rule attribute.
16:39:24.484 [pimatic] error: Could not parse rule "if its 10 minutes before sunset and Nachtlicht is off then turn Nachtlicht on": Illegal object in patterns
16:39:24.718 [pimatic-homeduino] info: Connected to homeduino device.
16:39:25.356 [pimatic-mobile-frontend] info: packing static assets
16:39:26.778 [pimatic-mobile-frontend] info: packing static assets finished
16:39:26.823 [pimatic-mobile-frontend] info: rendering html
16:39:48.745 [pimatic-mobile-frontend] info: rendering html finished
16:39:48.924 [pimatic] info: listening for http-request on port 8013...
(END)
```
At 16:33:47 you see I made an error with the commented first line of the config.
I deleted the whole line and restarted again at 16:38:49.
That gives no results except the *info* lines.

And this is my config
```
{
  "settings": {
    "debug": true,
    "loglevel": "debug",
    "httpServer": {
      "enabled": true,
      "port": 8013
    },
    "database": {
      "deviceAttributeLogging": [
        {
          "deviceId": "*",
          "attributeName": "*",
          "time": "7d"
        },
        {
          "deviceId": "*",
          "attributeName": "temperature",
          "time": "1y"
        },
        {
          "deviceId": "*",
          "attributeName": "humidity",
          "time": "1y"
        }
      ],
      "messageLogging": [
        {
          "level": "*",
          "tags": [],
          "time": "7d"
        }
      ]
    },
    "authentication": {
      "secret": "pdzTEN/uT/MJKBBsribh7JKvEE/ymq1n4hh1KDt6FoOAi/8bRlI8o464Rj0gJFpCXnPvuYFc3BwnOzVmCGGcUQ=="
    },
    "httpsServer": {},
    "gui": {}
  },
  "plugins": [
    {
      "plugin": "cron"
    },
    {
      "plugin": "mobile-frontend",
      "theme": "graphite/dark"
    },
    {
      "plugin": "homeduino",
      "driver": "serialport",
      "driverOptions": {
        "serialDevice": "/dev/ttyACM0",
        "baudrate": 115200
      },
      "receiverPin": 1,
      "transmitterPin": 4
    },
    {
      "plugin": "sunrise",
      "latitude": 52.030293,
      "longitude": 4.321763
    }
  ],
  "devices": [
    {
      "id": "lamp-living-entrance",
      "name": "Lamp achterkamer",
      "class": "HomeduinoRFSwitch",
      "protocols": [
        {
          "name": "switch1",
          "options": {
            "id": 7979378,
            "unit": 13
          }
        }
      ]
    },
    {
      "id": "lamp-living-bookcase",
      "name": "Lamp boekenkast",
      "class": "HomeduinoRFSwitch",
      "protocols": [
        {
          "name": "switch1",
          "options": {
            "id": 7979378,
            "unit": 14
          }
        }
      ]
    },
    {
      "id": "lamp-living-table",
      "name": "Lamp tafel",
      "class": "HomeduinoRFSwitch",
      "protocols": [
        {
          "name": "switch1",
          "options": {
            "id": 7979378,
            "unit": 15
          }
        }
      ]
    },
    {
      "id": "lamp-night",
      "name": "Nachtlicht",
      "class": "HomeduinoRFSwitch",
      "protocols": [
        {
          "name": "switch1",
          "options": {
            "id": 7979378,
            "unit": 12
          }
        }
      ]
    },
    {
      "id": "temperature-living",
      "name": "Temp woonkamer",
      "class": "HomeduinoDHTSensor",
      "type": 11,
      "pin": 8,
      "interval": 60000
    },
    {
      "id": "weather-home-actual",
      "class": "HomeduinoRFTemperature",
      "name": "Actueel weer",
      "protocols": [
        {
          "name": "weather1",
          "options": {
            "id": 87,
            "channel": 1
          }
        }
      ]
    },
    {
      "id": "fan-bedroom-bed",
      "name": "Plafondfan",
      "class": "HomeduinoRFSwitch",
      "protocols": [
        {
          "name": "switch1",
          "options": {
            "id": 7979378,
            "unit": 10
          }
        }
      ]
    },
    {
      "id": "set-dimlevel-dining",
      "name": "Eettafel dimmer",
      "class": "ButtonsDevice",
      "buttons": [
        {
          "id": "level_LO",
          "name": "Eten"
        },
        {
          "id": "level_HI",
          "name": "Werken"
        }
      ]
    }
  ],
  "rules": [
    {
      "id": "nachtlicht-automaat",
      "name": "Nachtlicht automaat",
      "rule": "if its 10 minutes before sunset and Nachtlicht is off then turn Nachtlicht on",
      "active": true,
      "logging": true
    }
  ],
  "pages": [
    {
      "id": "favourite",
      "name": "Favourites",
      "devices": [
        {
          "deviceId": "lamp-night"
        },
        {
          "deviceId": "lamp-living-entrance"
        },
        {
          "deviceId": "lamp-living-bookcase"
        },
        {
          "deviceId": "lamp-living-table"
        },
        {
          "deviceId": "temperature-living"
        },
        {
          "deviceId": "weather-home-actual"
        },
        {
          "deviceId": "fan-bedroom-bed"
        }
      ]
    }
  ],
  "rules": [
    {
      "id": "nachtlicht-automaat",
      "name": "Nachtlicht automaat",
      "rule": "if its 10 minutes before sunset and Nachtlicht is off then turn Nachtlicht on",
      "active": true,
      "logging": true
    }
  ],
  "pages": [
    {
      "id": "favourite",
      "name": "Favourites",
      "devices": [
        {
          "deviceId": "lamp-night"
        },
        {
          "deviceId": "lamp-living-entrance"
        },
        {
          "deviceId": "lamp-living-bookcase"
        },
        {
          "deviceId": "lamp-living-table"
        },
        {
          "deviceId": "temperature-living"
        },
        {
          "deviceId": "weather-home-actual"
        },
        {
          "deviceId": "fan-bedroom-bed"
        }
      ]
    }
  ],
  "groups": [],
  "users": [
    {
      "username": "PI_boss",
      "password": "_0Soleil!",
      "role": "admin"
    }
  ],
  "roles": [
    {
      "name": "admin",
      "permissions": {
        "pages": "write",
        "rules": "write",
        "variables": "write",
        "messages": "write",
        "events": "write",
        "devices": "write",
        "groups": "write",
        "plugins": "write",
        "updates": "write",
        "controlDevices": true,
        "restart": true
      }
    }
  ],
  "variables": []
}
```

**Comment by sweetpi** [comment]
Thanks for the feedback.

Change:
```json
    {
      "id": "set-dimlevel-dining",
      "name": "Eettafel dimmer”,
      "class": "ButtonsDevice",
      "buttons": [
        {
          "id": "level_LO",
          "name": "Eten"
        },
        {
          "id": "level_HI",
          "name": "Werken"
        }
      ]
    }
```

to:

```json
    {
      "id": "set-dimlevel-dining",
      "name": "Eettafel dimmer”,
      "class": "ButtonsDevice",
      "buttons": [
        {
          "id": "level_LO",
          "text": "Eten"
        },
        {
          "id": "level_HI",
          "text": "Werken"
        }
      ]
    }
```

I will add a verification check for that.

**Comment by DavidZH** [comment]
Check!  
Thanks a lot! 

That is (what I find) the biggest drawback of editing config files in this way. You're staring yourself cross-eyed with all the hyphens, commas, brackets, blocks, and ít's soooo easy to miss a little thing.

This works, but.... Is it possible to have feedback in the buttons ie.: they light up when selected? In the DummyThermostaat you can see what modus is selected, will it be possible in the future with a ButtonsDevice?

Keep up the good work and kudo's for the quick response.

**Comment by kenci** [comment]
>This works, but.... Is it possible to have feedback in the buttons ie.: they light up when selected? In the DummyThermostaat you can see what modus is selected, will it be possible in the future with a ButtonsDevice?

Anything new on this one?

**Comment by sweetpi** [comment]
Could you please make a feature request for it in the forum?

http://forum.pimatic.org/category/14/feature-requests
