### ISSUE TITLE
logrotate: a uncaught exception occured

### ISSUE THREAD

**Issue by Harrdy** [pimatic/pimatic#538]
if i'm trying to stop the pimatic service i get this message and the daemon didn't stop. i must kill him to stop it. The problem comes with the last update

```
error [pimatic]: a uncaught exception occured: Error: write after end at writeAfterEnd (_stream_writable.js:130:12) at WriteStream.Writable.write (_stream_writable.js:178:5) at next (/home/pi/pimatic-app/node_modules/pimatic/node_modules/logrotate-stream/index.js:64:19) at LogStream._write (/home/pi/pimatic-app/node_modules/pimatic/node_modules/logrotate-stream/index.js:71:5) at doWrite (_stream_writable.js:221:10) at clearBuffer (_stream_writable.js:299:5) at onwrite (_stream_writable.js:257:7) at WritableState.onwrite (_stream_writable.js:97:5) at next (/home/pi/pimatic-app/node_modules/pimatic/node_modules/logrotate-stream/index.js:54:36) at afterWrite (_stream_writable.js:272:3) at onwrite (_stream_writable.js:264:7) at WritableState.onwrite (_stream_writable.js:97:5) at fs.js:1681:5 at Object.wrapper [as oncomplete] (fs.js:510:5) 
This is most probably a bug in pimatic or an module, please report it!

error [pimatic]: The genericPool is not initialized.
warn [pimatic]: keeping pimatic alive, but could be in an undefined state, please restart pimatic so soon as possible!
```

````
node --version
v0.10.24
````

**Comment by leader21** [comment]
maybe a ```sudo npm``` install within the node_modules/pimatic directory could help?

**Comment by Harrdy** [comment]
````sudo npm install```` don't work. After a full reinstall of raspbian and restore pimatic db/conf the error is gone

**Comment by sweetpi** [comment]
@Harrdy How did you try to kill it? Does the error happen every time?

**Comment by Harrdy** [comment]
the error comes everytime. i just trying ````sudo service pimatic stop```` to stop the daemon

i'm installing the new version and the error is gone. Just now i'm able to stop the daemon without errors.

**Comment by sweetpi** [comment]
Thank you for reporting and testing :)
