### ISSUE TITLE
Installing updates failed.

### ISSUE THREAD

**Issue by tomansi** [pimatic/pimatic#545]
Update finish with the message "Installing updates. Please be patient..."

```
npm http GET https://registry.npmjs.org/pimatic/latest
npm http GET https://registry.npmjs.org/pimatic-homeduino/latest
npm http GET https://registry.npmjs.org/pimatic-mobile-frontend/latest
npm http 200 https://registry.npmjs.org/pimatic-homeduino/latest
npm http 200 https://registry.npmjs.org/pimatic/latest
npm http 200 https://registry.npmjs.org/pimatic-mobile-frontend/latest
npm http GET https://registry.npmjs.org/pimatic-homeduino
npm http GET https://registry.npmjs.org/pimatic
npm http GET https://registry.npmjs.org/pimatic-mobile-frontend
npm http 200 https://registry.npmjs.org/pimatic-mobile-frontend
npm http 200 https://registry.npmjs.org/pimatic
npm http 200 https://registry.npmjs.org/pimatic-homeduino
npm http GET https://registry.npmjs.org/pimatic-mobile-frontend/-/pimatic-mobile-frontend-0.8.44.tgz
npm http GET https://registry.npmjs.org/pimatic/-/pimatic-0.8.46.tgz
npm http GET https://registry.npmjs.org/pimatic-homeduino/-/pimatic-homeduino-0.8.41.tgz
npm http 200 https://registry.npmjs.org/pimatic-mobile-frontend/-/pimatic-mobile-frontend-0.8.44.tgz
npm http 200 https://registry.npmjs.org/pimatic-homeduino/-/pimatic-homeduino-0.8.41.tgz
npm http 200 https://registry.npmjs.org/pimatic/-/pimatic-0.8.46.tgz
npm http GET https://registry.npmjs.org/pimatic-homeduino/0.8.41
npm http GET https://registry.npmjs.org/pimatic-mobile-frontend/0.8.44
npm http GET https://registry.npmjs.org/pimatic/0.8.46
npm http 200 https://registry.npmjs.org/pimatic-homeduino/0.8.41
npm http 200 https://registry.npmjs.org/pimatic/0.8.46
npm http GET https://registry.npmjs.org/pimatic-homeduino/-/pimatic-homeduino-0.8.41.tgz
npm http 200 https://registry.npmjs.org/pimatic-mobile-frontend/0.8.44
npm http GET https://registry.npmjs.org/pimatic/-/pimatic-0.8.46.tgz
npm http GET https://registry.npmjs.org/pimatic-mobile-frontend/-/pimatic-mobile-frontend-0.8.44.tgz
npm http 200 https://registry.npmjs.org/pimatic-homeduino/-/pimatic-homeduino-0.8.41.tgz
npm http 200 https://registry.npmjs.org/pimatic/-/pimatic-0.8.46.tgz
npm http 200 https://registry.npmjs.org/pimatic-mobile-frontend/-/pimatic-mobile-frontend-0.8.44.tgz
npm http GET https://registry.npmjs.org/homeduino
npm http 200 https://registry.npmjs.org/homeduino
npm http GET https://registry.npmjs.org/homeduino/-/homeduino-0.0.32.tgz
npm http 200 https://registry.npmjs.org/homeduino/-/homeduino-0.0.32.tgz
npm http GET https://registry.npmjs.org/otaat-repl
npm http GET https://registry.npmjs.org/rfcontroljs
npm http GET https://registry.npmjs.org/serialport
npm http GET https://registry.npmjs.org/bluebird
npm http 200 https://registry.npmjs.org/serialport
npm http 200 https://registry.npmjs.org/bluebird
npm http GET https://registry.npmjs.org/async/0.9.0
npm http GET https://registry.npmjs.org/sf/0.1.7
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/bindings/1.2.1
npm http 200 https://registry.npmjs.org/async/0.9.0
npm http 200 https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/async/-/async-0.9.0.tgz
npm http 200 https://registry.npmjs.org/async/-/async-0.9.0.tgz
npm http GET https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/minimist
npm http 200 https://registry.npmjs.org/minimist
> serialport@1.4.10 install /usr/local/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport
> node-pre-gyp install --fallback-to-build
node-pre-gyp http GET https://node-serialport.s3.amazonaws.com/serialport/v1.4.10/Release/node-v11-linux-arm.tar.gz
node-pre-gyp http 404 https://node-serialport.s3.amazonaws.com/serialport/v1.4.10/Release/node-v11-linux-arm.tar.gz
node-pre-gyp http Pre-built binary not available for your system (falling back to source compile with node-gyp)
make: Entering directory '/usr/local/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/build'
CXX(target) Release/obj.target/serialport/src/serialport.o
CXX(target) Release/obj.target/serialport/src/serialport_unix.o
CXX(target) Release/obj.target/serialport/src/serialport_poller.o
SOLINK_MODULE(target) Release/obj.target/serialport.node
SOLINK_MODULE(target) Release/obj.target/serialport.node: Finished
COPY Release/serialport.node
COPY /usr/local/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/build/serialport/v1.4.10/Release/node-v11-linux-arm/serialport.node
TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory '/usr/local/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/build'
pimatic-homeduino@0.8.41 node_modules/pimatic-homeduino
└── homeduino@0.0.32 (otaat-repl@1.0.2, rfcontroljs@0.0.23, bluebird@2.2.2, serialport@1.4.10)
```

Now there is the application message.
```
pi@raspberrypi ~ $ sudo service pimatic status                                  
module.js:340
    throw err;
          ^
Error: Cannot find module 'source-map-support'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic/coffee-cache.js:76:1)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic/pimatic.js:3:1)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:902:3
```

Now pimatic don't work.

What can I do next?
Can I delete cache and force the compilation? How?
I need to reinstall pimatic?

Thanks in advance.

**Comment by leader21** [comment]
try ```sudo npm install``` in the node_modules/pimatic directory.

**Comment by tomansi** [comment]
The first solution has been enough to start pimatic but a error message "Cannot find module 'source-map'" is present.

I search this and I see the problem at https://github.com/pimatic/pimatic/issues/343 and I try it.
```
sudo service pimatic stop
cd /usr/local/pimatic-app/node_modules/pimatic
sudo rm -rf node_modules
sudo npm install
```

Now pimatic works again, but the message error remain.

Thanks for you help.

**Comment by tomansi** [comment]
... and the web say the message "Cannot GET /"

then I have done the https://github.com/pimatic/pimatic/issues/468

´´´
sudo service pimatic stop
sudo rm -rf /usr/local/pimatic-app/node_modules/pimatic-mobile-frontend
sudo service pimatic start
´´´

Now everything works fine.

Thanks.
