### ISSUE TITLE
After update ???

### ISSUE THREAD

**Issue by WimUtTwente** [pimatic/pimatic#565]
Possibly unhandled Error: unknown_command
    at /home/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/lib/board.js:291:19
    at tryCatch1 (/home/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/bluebird/js/main/util.js:43:21)
    at Promise$_callHandler [as _callHandler] (/home/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/bluebird/js/main/promise.js:627:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/home/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/bluebird/js/main/promise.js:641:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/home/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/bluebird/js/main/promise.js:804:14)
    at Promise$_settlePromises [as _settlePromises] (/home/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/bluebird/js/main/promise.js:938:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/home/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/bluebird/js/main/async.js:75:12)
    at Async$consumeFunctionBuffer (/home/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/bluebird/js/main/async.js:38:14)
    at process._tickCallback (node.js:415:13)

**Comment by leader21** [comment]
don't know what it caused but you can try to delete the folder node_modules/pimatic-homeduino and start pimatic again. this will install the homeduino plugin again.
maybe this will solve this issue.

**Comment by sweetpi** [comment]
@WimUtTwente Does it happen all the time or just one time?

**Comment by jensebub** [comment]
It is here the same! Also after reinstalling pimatic-homeduino:
```
10:37:11.997 [pimatic-homeduino] info: Connected to homeduino device.
Possibly unhandled Error: unknown_command
    at /root/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/lib/board.js:291:19
    at tryCatch1 (/root/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/bluebird/js/main/util.js:43:21)
    at Promise$_callHandler [as _callHandler] (/root/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/bluebird/js/main/promise.js:627:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/root/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/bluebird/js/main/promise.js:641:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/root/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/bluebird/js/main/promise.js:804:14)
    at Promise$_settlePromises [as _settlePromises] (/root/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/bluebird/js/main/promise.js:938:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/root/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/bluebird/js/main/async.js:75:12)
    at Async$consumeFunctionBuffer (/root/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/bluebird/js/main/async.js:38:14)
    at process._tickCallback (node.js:415:13)
```

**Comment by sweetpi** [comment]
Thanks for reporting, should be fixed in newest version

**Comment by jensebub** [comment]
yes it's fixed here. thx

**Comment by WimUtTwente** [comment]
After update yes it's fixed. Thx😁
