### ISSUE TITLE
Unhandled rejection Error: Command failed

### ISSUE THREAD

**Issue by n3roGit** [pimatic/pimatic#570]
Hey guys,

i get this error in the pimatic-daemon.log

Unhandled rejection Error: Command failed:
    at ChildProcess.exithandler (child_process.js:637:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Socket.<anonymous> (child_process.js:948:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
Unhandled rejection Error: Command failed:
    at ChildProcess.exithandler (child_process.js:637:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Socket.<anonymous> (child_process.js:948:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
Unhandled rejection Error: Command failed:
    at ChildProcess.exithandler (child_process.js:637:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Socket.<anonymous> (child_process.js:948:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)

any ideas?

**Comment by n3roGit** [comment]
and i cant update pimatic.

Found update for pimatic: current version is 0.8.52, latest version is: 0.8.53
All plugins are up to date.
npm http GET https://registry.npmjs.org/pimatic/latest
npm http GET https://registry.npmjs.org/pimatic
Updates were successful. Please restart pimatic.

every time I update and re-start the update comes again

**Comment by Icesory** [comment]
You can try to update it manually. 
Go in the pimatic directory and run
```
sudo npm install pimatic 
```

**Comment by n3roGit** [comment]
Ah okay. Now the update works! But I have still the errors in my log every 1 second

**Comment by Icesory** [comment]
Can you give us some more information's about your system?

**Comment by n3roGit** [comment]
What information do you need?

**Comment by n3roGit** [comment]
since last update the error is gone.

closed :)

**Comment by calvintwr** [comment]
For the benefit of those who reached here:

I had the same problem. I am not using pimatic, but I believe it is the same problem as the stack trace is identical.

I was using GraphicsMagick 1.7.0 with node 0.12.1. GM was set to use ImageMagick (using the `imageMagick: true` flag.)

The problem was solved by upgrading GraphicsMagick to 1.9.0.

Cheers.
