### ISSUE TITLE
[pimatic-homeduino] AssertionError Board._handleRF

### ISSUE THREAD

**Issue by Icesory** [pimatic/pimatic#572]
I am not sure why this error occurs.

```
warn [pimatic]: Keeping pimatic alive, but could be in an undefined state, please restart pimatic so soon as possible!
17:30:05error [pimatic]: A uncaught exception occured: AssertionError: false == true at Board._handleRFControl (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/lib/board.js:323:5) at Board._onLine (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/lib/board.js:142:21) at SerialPortDriver.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/lib/board.js:83:22) at SerialPortDriver.EventEmitter.emit (events.js:95:17) at SerialPort.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/lib/driver/serialport.js:60:24) at SerialPort.EventEmitter.emit (events.js:95:17) at /home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/parsers.js:25:17 at Array.forEach (native) at Object.parser (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/parsers.js:24:13) at Object.SerialPort.options.dataCallback (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/serialport.js:168:15) at SerialPortFactory.SerialPort._emitData (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/serialport.js:350:20) at afterRead (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/serialport.js:326:20) at /home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/serialport.js:342:9 at Object.wrapper [as oncomplete] (fs.js:454:17) This is most probably a bug in pimatic or in a module, please report it!
```

**Comment by sweebee** [comment]
I had this too when i tried to send a message to the serial port (in the terminal) while pimatic was running.

**Comment by sweetpi** [comment]
I've add a [more verbose debug output](https://github.com/pimatic/homeduinojs/commit/3a5e3a77769b03076d5fdaf259192107ef64057f), hopefully this will show what's going wrong here.

**Comment by mggg** [comment]
I had to this morning, maybe related with info received through arduino nano :
´´´
02:15:26.763 [pimatic-homeduino] debug: data: "RF receive 489 2010 4048 7876 0 0 0 0 01010201010101020102020102020101010101020201020101010101010101010201010203"
02:15:26.776 [pimatic-homeduino] debug: received: [ 489, 2010, 4048, 7876 ] 01010201010101020102020102020101010101020201020101010101010101010201010203
02:15:26.804 [pimatic-homeduino] debug: weather1:  { id: 22,
02:15:26.804 [pimatic-homeduino] debug:>  channel: 1,
02:15:26.804 [pimatic-homeduino] debug:>  temperature: 41.6,
02:15:26.804 [pimatic-homeduino] debug:>  humidity: 9,
02:15:26.804 [pimatic-homeduino] debug:>  lowBattery: false }
02:15:26.814 [pimatic-homeduino] debug: weather5:  { id: 132, lowBattery: false, rain: 22 }
02:15:26.858 [pimatic-homeduino] debug: data: "RF receive 252 104 820 2028 468 3520 6648 148 0100232345002033434345434545434545434343432345454325432343434343434343254343452607000$\�P4�$8(��X���T�$� @�D$�,0�0�(�,�(4�,$$ �$ �� 0��X�0(X�H$�$�4�<� ��8�$$@� �P�,�((�, �0�0�0�<�88"
02:15:26.938 [pimatic] error: A uncaught exception occured: AssertionError: false == true
02:15:26.938 [pimatic] error:>    at Board._handleRFControl (/etc/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/lib/board.js:322:5)
02:15:26.938 [pimatic] error:>    at Board._onLine (/etc/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/lib/board.js:142:21)
02:15:26.938 [pimatic] error:>    at SerialPortDriver.<anonymous> (/etc/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/lib/board.js:83:22)
02:15:26.938 [pimatic] error:>    at SerialPortDriver.EventEmitter.emit (events.js:95:17)
02:15:26.938 [pimatic] error:>    at SerialPort.<anonymous> (/etc/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/lib/driver/serialport.js:60:24)
02:15:26.938 [pimatic] error:>    at SerialPort.EventEmitter.emit (events.js:95:17)
02:15:26.938 [pimatic] error:>    at /etc/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/parsers.js:25:17
02:15:26.938 [pimatic] error:>    at Array.forEach (native)
02:15:26.938 [pimatic] error:>    at Object.parser (/etc/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/parsers.js:24:13)
02:15:26.938 [pimatic] error:>    at Object.SerialPort.options.dataCallback (/etc/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/serialport.js:168:15)
02:15:26.938 [pimatic] error:>    at SerialPortFactory.SerialPort._emitData (/etc/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/serialport.js:350:20)
02:15:26.938 [pimatic] error:>    at afterRead (/etc/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/serialport.js:326:20)
02:15:26.938 [pimatic] error:>    at /etc/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/serialport.js:342:9
02:15:26.938 [pimatic] error:>    at Object.wrapper [as oncomplete] (fs.js:454:17)
02:15:26.938 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!
02:15:26.952 [pimatic] warn: Keeping pimatic alive, but could be in an undefined state, please restart pimatic so soon as possible!
´´´
