### ISSUE TITLE
[warning] (node) warning: possible EventEmitter memory leak detected 

### ISSUE THREAD

**Issue by mggg** [pimatic/pimatic#579]
Hi 
I have a raspbian-pimatic installation with 29 devices and 45 variables. The warnings seems to me related with this numbers...
When I start pimatic I get this two messages:
```
(node) warning: possible EventEmitter memory leak detected. 11 rf listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Board.addListener (events.js:179:15)
    at new HomeduinoRFShutter (/homeduino.coffee:458:14)
    at Object._this.framework.deviceManager.registerDeviceClass.createCallback (/homeduino.coffee:113:28)
    at DeviceManager._loadDevice (/devices.coffee:850:26)
    at Runner_SQLite3.<anonymous> (/devices.coffee:875:16)
    at Runner_SQLite3.tryCatcher (/etc/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/etc/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:466:31)
    at Promise._settlePromiseAt (/etc/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:545:18)
    at Promise._settlePromises (/etc/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:661:14)
    at Async._drainQueue (/etc/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:79:16)
    at Async._drainQueues (/etc/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:89:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/etc/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:14:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```
```
(node) warning: possible EventEmitter memory leak detected. 11 variableValueChanged listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at VariableManager.addListener (events.js:179:15)
    at VariablePredicateHandler.setup (/predicates.coffee:616:34)
    at /rules.coffee:551:21
    at RuleManager._addPredicateChangeListener (/rules.coffee:548:9)
    at /rules.coffee:638:10
    at tryCatcher (/etc/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/etc/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:466:31)
    at Promise._settlePromiseAt (/etc/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:545:18)
    at Promise._settlePromiseAtPostResolution (/etc/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:229:10)
    at Async._drainQueue (/etc/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:84:12)
    at Async._drainQueues (/etc/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:89:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/etc/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:14:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```
Should I be worried? Is there any way to remove this warnings?... I like a clean log...
Thanks in advance!!!

**Comment by sweetpi** [comment]
Thanks for reporting. Should be fixed in the new release, please reopen if the problem still exists.
