### ISSUE TITLE
ETIMEDOUT Error in Log

### ISSUE THREAD

**Issue by frosenheimer** [pimatic/pimatic#589]
I get these errors every ~ 5mins in my Log:
Does someone know where they come frome?

```
error [pimatic]: A uncaught exception occured: Error: socket hang up at createHangUpError (http.js:1472:15) at Socket.socketCloseListener (http.js:1522:23) at Socket.EventEmitter.emit (events.js:117:20) at TCP.close (net.js:466:12) This is most probably a bug in pimatic or in a module, please report it!

error [pimatic]: A uncaught exception occured: Error: connect ETIMEDOUT at errnoException (net.js:901:11) at Object.afterConnect [as oncomplete] (net.js:892:19) This is most probably a bug in pimatic or in a module, please report it!
```

**Comment by sweetpi** [comment]
It's a problem with the openweather plugin, a fix is in progress (https://github.com/baslr/node-openweathermap/pulls)

It's safe to ignore the error till a fix is released.
