### ISSUE TITLE
Getting exceptions, socket hang up. 

### ISSUE THREAD

**Issue by tomvlk** [pimatic/pimatic#592]
New installation. Just started and directly got this:

```
2015-03-15 08:45:31error [pimatic]: A uncaught exception occured: Error: socket hang up at createHangUpError (http.js:1472:15) at Socket.socketCloseListener (http.js:1522:23) at Socket.EventEmitter.emit (events.js:117:20) at TCP.close (net.js:466:12) This is most probably a bug in pimatic or in a module, please report it!
08:45:31error [pimatic]: A uncaught exception occured: Error: read ECONNRESET at errnoException (net.js:901:11) at TCP.onread (net.js:556:19) This is most probably a bug in pimatic or in a module, please report it!
```

**Comment by sweetpi** [comment]
Thanks for reporting, see #584
