### ISSUE TITLE
RFControl error

### ISSUE THREAD

**Issue by elektronaut69** [pimatic/pimatic#602]
I found this in the log today:
```
error [pimatic]: A uncaught exception occured: AssertionError: false == true at Board._handleRFControl (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/lib/board.js:323:5) at Board._onLine (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/lib/board.js:142:21) at SerialPortDriver.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/lib/board.js:83:22) at SerialPortDriver.EventEmitter.emit (events.js:95:17) at SerialPort.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/lib/driver/serialport.js:60:24) at SerialPort.EventEmitter.emit (events.js:95:17) at /home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/parsers.js:25:17 at Array.forEach (native) at Object.parser (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/parsers.js:24:13) at Object.SerialPort.options.dataCallback (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/serialport.js:168:15) at SerialPortFactory.SerialPort._emitData (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/serialport.js:350:20) at afterRead (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/serialport.js:326:20) at /home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/serialport.js:342:9 at Object.wrapper [as oncomplete] (fs.js:454:17) This is most probably a bug in pimatic or in a module, please report it!
```

**Comment by Icesory** [comment]
It is already known.
https://github.com/pimatic/pimatic/issues/572

**Comment by sweetpi** [comment]
Thanks for reporting, did you do something with the serialport while pimatic was running?

**Comment by sweetpi** [comment]
closing this in favor of #572

**Comment by elektronaut69** [comment]
No I didn't do anything. I wasn't even at home when the error occured.

**Comment by sweetpi** [comment]
Ok thanks, that it must be something deeper.
