### ISSUE TITLE
Error: spawn ENOENT after enabled pimatic-homeduino

### ISSUE THREAD

**Issue by annuh** [pimatic/pimatic#628]
Hi,
After reinstalling my raspberry (powered by Xbian) I can't get Pimatic to work.
It works after I remove the Pimatic-Homeduino plugin from the config.json.

My complete  config.json looks like this:
```
{
  "//": "Please only change this file when pimatic is NOT running else pimatic will overwrite your changes.",
  "settings": {
    "httpServer": {
      "enabled": true,
      "port": 9093
    },
    "database": {
      "deviceAttributeLogging": [
        {
          "deviceId": "*",
          "attributeName": "*",
          "type": "*",
          "interval": "0",
          "expire": "7d"
        },
        {
          "deviceId": "*",
          "attributeName": "*",
          "type": "continuous",
          "interval": "5min",
          "expire": "7d"
        },
        {
          "deviceId": "*",
          "attributeName": "temperature",
          "type": "number",
          "expire": "1y"
        },
        {
          "deviceId": "*",
          "attributeName": "humidity",
          "type": "number",
          "expire": "1y"
        }
      ],
      "messageLogging": [
        {
          "level": "*",
          "tags": [],
          "expire": "7d"
        },
        {
          "level": "debug",
          "tags": [],
          "expire": "0"
        }
      ]
    },
    "authentication": {
      "secret": "2/zELSPWgsVKDx+JM4R90zWSA7zjHGMCGGX/F+HY7d5ayZ2k7lQSxJVn3kVBn7kEjIa/FRj5Ovk5yZo+YjjDfA=="
    },
    "httpsServer": {},
    "gui": {}
  },
  "plugins": [
    {
      "plugin": "cron"
    },
    {
      "plugin": "mobile-frontend"
    },
    {
      "plugin": "homeduino",
      "driver": "gpio",
      "driverOptions": {},
      "receiverPin": 0,
      "transmitterPin": 4,
      "rfrepeats": 15
    },
    {
      "plugin": "sunrise",
      "latitude": 123,
      "longitude": 123
    },
    {
      "plugin": "filebrowser",
      "mappings": [
        {
          "path": "/files",
          "directory": "/media/xxx"
        }
      ]
    },
    {
      "plugin": "ping"
    }
  ],
  "devices": [
    {
      "id": "rfswitch1",
      "name": "Switch 1",
      "class": "HomeduinoRFSwitch",
      "protocols": [
        {
          "name": "switch1",
          "options": {
            "id": 15562074,
            "unit": 0
          }
        }
      ]
    },
    {
      "id": "rfswitch2",
      "name": "Switch 2",
      "class": "HomeduinoRFSwitch",
      "protocols": [
        {
          "name": "switch1",
          "options": {
            "id": 15562074,
            "unit": 1
          }
        }
      ]
    },
    {
      "id": "rfswitch3",
      "name": "Switch 3",
      "class": "HomeduinoRFSwitch",
      "protocols": [
        {
          "name": "switch1",
          "options": {
            "id": 15562074,
            "unit": 2
          }
        }
      ]
    }
  ],
  "rules": [
    {
      "id": "licht-aan-avond",
      "name": "licht-aan-avond",
      "rule": "if sunset then turn Switch 1 on",
      "active": true,
      "logging": true
    }
  ],
  "pages": [
    {
      "id": "favourite",
      "name": "Favourites",
      "devices": [
        {
          "deviceId": "rfswitch3"
        },
        {
          "deviceId": "rfswitch2"
        },
        {
          "deviceId": "rfswitch1"
        }
      ]
    }
  ],
  "groups": [
    {
      "id": "woonkamer",
      "name": "Woonkamer",
      "devices": [
        "rfswitch1"
      ],
      "rules": [],
      "variables": []
    },
    {
      "id": "buiten",
      "name": "Buiten",
      "devices": [
        "rfswitch3"
      ],
      "rules": [],
      "variables": []
    }
  ],
  "users": [
    {
      "username": "admin",
      "password": "admin",
      "role": "admin"
    }
  ],
  "roles": [
    {
      "name": "admin",
      "permissions": {
        "pages": "write",
        "rules": "write",
        "variables": "write",
        "messages": "write",
        "events": "write",
        "devices": "write",
        "groups": "write",
        "plugins": "write",
        "updates": "write",
        "controlDevices": true,
        "restart": true
      }
    }
  ],
  "variables": []
}
```

The output of executing pimatic.js is:
```
08:41:56.362 2015-04-01 Wednesday
08:42:14.967 [pimatic] Starting pimatic version 0.8.60
08:42:19.344 [pimatic] Loading plugin: "pimatic-cron" (0.8.5)
08:42:21.912 [pimatic] Loading plugin: "pimatic-mobile-frontend" (0.8.61)
08:42:26.254 [pimatic] Loading plugin: "pimatic-homeduino" (0.8.44)
coffee-cache: compiling coffee-script file "homeduino.coffee"...Done
coffee-cache: compiling coffee-script file "homeduino-config-schema.coffee"...Done
08:42:38.235 [pimatic] Loading plugin: "pimatic-sunrise" (0.8.0)
08:42:38.411 [pimatic] Loading plugin: "pimatic-filebrowser" (0.8.0)
08:42:38.462 [pimatic] package.json of "pimatic-filebrowser" has no "configSchema" property. Could not validate config.
08:42:38.473 [pimatic] Loading plugin: "pimatic-ping" (0.8.3)
08:42:41.473 [pimatic-cron] the time is: Wed Apr 01 2015 08:42:41 GMT+0000 (UTC)
coffee-cache: compiling coffee-script file "device-config-schema.coffee"...Done
08:42:43.822 [pimatic-sunrise] Your location is set to lat: xxxx
08:42:44.436 [pimatic] New device "Switch 1"...
08:42:44.601 [pimatic] New device "Switch 2"...
08:42:44.722 [pimatic] New device "Switch 3"...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
```

Note the old versions of pimatic and pimatic-homeduino. I tried to downgrade the pimatic and/or pimatic-homeduino plugin to find the problem, but this didn't help.

I could find any more logs. Does someone know what is going wrong?
Thanks!

**Comment by leader21** [comment]
guess it's the same issue like here #625

**Comment by sweetpi** [comment]
Coud you post the output of?

```
uname -a
file pimatic-app/node_modules/pimatic-homeduino/node_modules/bin/vhduino
./pimatic-app/node_modules/pimatic-homeduino/node_modules/bin/vhduino
```

It could be that you have to press CTRL+C to exit the last command.

**Comment by annuh** [comment]
uname -a
Linux xbian 3.18.8+ #1 PREEMPT Thu Mar 5 03:43:34 CET 2015 armv6l GNU/Linux

I cannot find the other two files. Could that be the problem?

**Comment by Icesory** [comment]
the right path is this
```
/home/user/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/bin
```

**Comment by sweetpi** [comment]
Does the directory exist? Ofcause it depends where you've installed it

**Comment by annuh** [comment]
Okay, I found the file, if I try to execute the output is:

-bash: ./pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/bin/vhduino: No such file or directory

However, the file exists. I even tried to execute it with sudo.

**Comment by sweetpi** [comment]
That means the vhduino file does not fit your arch. Thats really strange. 

The bin should be armv6l hardf. I think xbain should be hardf, too. But maybe I'm wrong here or something else goes wrong.

**Comment by annuh** [comment]
Before I tried to reinstall pimatic, it used to work. Even if I downgrade the pimatic and pimatic-homeduino it still don't work. 

Maybe the problem is in a newer xbian version?

**Comment by sweetpi** [comment]
Yes, the binary shipped with the plugin seems to be not compatible with this release.

**Comment by zwevert** [comment]
Hi, 
First of all, I really dig pimatic !.
But since pilight support was dropped and open issue #628 on the homeduino binary, my 433mhz on xbian is dead in the water. Is there any news / or workaround for this issue ?

**Comment by ManuelW77** [comment]
Hey there,
i have xbian on my pi2 running. vduino wont work :(

**Comment by mwittig** [comment]
Maybe the following is helpful for you: https://forum.pimatic.org/topic/2460/solved-installing-pimatic-0-9-osmc/53
