### ISSUE TITLE
Error with homeduino contact sensor

### ISSUE THREAD

**Issue by sweebee** [pimatic/pimatic#647]
I tried to add a contact sensor but pimatic doesn't like it...

error:
```
error [pimatic]: A uncaught exception occured: TypeError: Cannot read property 'value' of undefined at HomeduinoRFContactSensor.Device.toJson (/home/xbian/pimatic-app/node_modules/pimatic/lib/devices.coffee:160:30) at Framework.<anonymous> (/home/xbian/pimatic-app/node_modules/pimatic/lib/framework.coffee:474:37) at Namespace.<anonymous> (/home/xbian/pimatic-app/node_modules/pimatic/lib/framework.coffee:474:35) at Namespace.EventEmitter.emit (events.js:95:17) at Namespace.emit (/home/xbian/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:205:10) at /home/xbian/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:172:14 at process._tickCallback (node.js:415:13) This is most probably a bug in pimatic or in a module, please report it!
```

config: 
```json
{
      "id": "woonkamer-deur",
      "name": "Deur",
      "class": "HomeduinoRFContactSensor",
      "protocols": [
        {
          "name": "contact1",
          "options": {
            "unit": 1,
            "id": 27951
          }
        }
      ]
    },
```

**Comment by Icesory** [comment]
I have not looked at the source but it sounds like a failure with an variable "value". I remember sweetpi changed something to present. Eventually is one thing wrong.

**Comment by sweetpi** [comment]
Strange bug. @sweebee Do you use any other ContactSensors?

**Comment by sweebee** [comment]
Not from homeduino.  But one from mysensors

**Comment by sweetpi** [comment]
There's a little error in the mysensor plugin, so that the common super class ContactSensor is modified. I submitted a fix for it. Thanks for the fast feedback.

**Comment by sweetpi** [comment]
Should be fixed.
