### ISSUE TITLE
pimatic-sunrise error

### ISSUE THREAD

**Issue by sweebee** [pimatic/pimatic#660]
Every evening i get this error:

```
error [pimatic]: A uncaught exception occured: AssertionError: timediff > 0 at SunrisePredicateHandler._getNextEventDate (/home/xbian/pimatic-app/node_modules/pimatic-sunrise/sunrise.coffee:150:7) at SunrisePredicateHandler._getTimeTillEvent (/home/xbian/pimatic-app/node_modules/pimatic-sunrise/sunrise.coffee:140:15) at /home/xbian/pimatic-app/node_modules/pimatic-sunrise/sunrise.coffee:193:32 at null._onTimeout (/home/xbian/pimatic-app/node_modules/pimatic-sunrise/sunrise.coffee:195:17) at Timer.listOnTimeout [as ontimeout] (timers.js:110:15) This is most probably a bug in pimatic or in a module, please report it!
```

Other than this it works fine.

**Comment by pimagical** [comment]
Can you check your system time?
https://github.com/pimatic/pimatic-sunrise/issues/2

**Comment by sweebee** [comment]
The time is correct

**Comment by n3roGit** [comment]
i have the same: 
error [pimatic]: A uncaught exception occured: AssertionError: timediff > 0 at SunrisePredicateHandler._getNextEventDate (/opt/pimatic-app/node_modules/pimatic-sunrise/sunrise.coffee:150:7) at SunrisePredicateHandler._getTimeTillEvent (/opt/pimatic-app/node_modules/pimatic-sunrise/sunrise.coffee:140:15) at /opt/pimatic-app/node_modules/pimatic-sunrise/sunrise.coffee:168:30 at null._onTimeout (/opt/pimatic-app/node_modules/pimatic-sunrise/sunrise.coffee:170:15) at Timer.listOnTimeout [as ontimeout] (timers.js:110:15) This is most probably a bug in pimatic or in a module, please report it!

**Comment by mwittig** [comment]
Looks like this is an follow-up on #655 

Does this issue still occur?

**Comment by pimagical** [comment]
I fixed the problem with deleting the rule and adding a new rule with the exact same actions in it and it worked successfully again strangely. The problem never happened again.

So from my experience I would say at that time a rule can be broken even if the rule actions are right.
