### ISSUE TITLE
[pimatic] emfil

### ISSUE THREAD

**Issue by georg90** [pimatic/pimatic#667]

**Comment by sweetpi** [comment]
Could you try to find out, which files are opened by pimatic (http://www.cyberciti.biz/faq/howto-linux-get-list-of-open-files/)?

**Comment by georg90** [comment]
this is now: http://pastebin.com/raw.php?i=UV0ky5rb
It's running fine for now.

**Comment by sweetpi** [comment]
Looks like the open tcp connections are the problem. I think normally these get closed when the hping3 program exits. If I execute the mentioned comment it exits after doing its job. Maybe there is a problem at spawning the child process, preventing child processes from exiting.

It is also strange that `node` holds the connections and not the child process `hping3`, but maybe node inherits them. Could you check if there are  still running `hping3` processes (`grep --colour=auto hping3`)?

I don't think that these connections are created by this rule. Which other plugins do you use that connect to the internet?

**Comment by georg90** [comment]
Thanks for the quick reply. 
There are no hping3 processes running..

I use ping, location and pushbullet

**Comment by mwittig** [comment]
The browser may keep connections open for a long time. However, it is strange that you have so many connections!!! Possibly, the connections are stale/dead? This may happen, for example, if you use a VPN between your workplace computer and pimatic and the VPN gets torn down at some point. It may also happen a firewall in between will drop (-> forget) the connection after a certain period of inactivity.

@sweetpi Assuming "zbox.fritz.box:1443" is the pimatic web frontend, may be pimatic should detect & close "idle" connections somehow?! It should be possible to use TCP-Keepalives to detect dead connections. See "Checking for dead peers" at http://tldp.org/HOWTO/TCP-Keepalive-HOWTO/overview.html Another strategy may be to implement an application-level timer for accepted connections as TCP-Keepalice has some drawbacks.

**Comment by sweetpi** [comment]
I've tested with my setup and I've similar open connections...

Hm since we just use very common npm modules (`express` and `socket.io`) which are also used in servers with much higher load (our forum for example :D), it would be really strange if we get into this problems with just a few users using a pimatic instance.

I checked at the demo and forum server, but there are just a few open connections (seems because all connections get proxied by nginx). I've to look deeper into that.

**Comment by mwittig** [comment]
Agree. I haven't thought about this. According to google a node.js http server would close an accepted connection after two minutes of inactivity which is a long time, but still short enough to handle dead connections in a normal load scenario. Express seems to apply the same default. So, may be @georg90 can send another lsof if the the problem occurs again.

**Comment by georg90** [comment]
Happened again today: http://pastebin.com/LXEZvSqQ

**Comment by sweetpi** [comment]
@georg90 Do you have any uncaught exception erros in the log?

**Comment by georg90** [comment]
```
11:40:03.100 [pimatic] info: rule ping-iphone-to-be-awake: executed "sudo hping3 -2 -c 3 -p 5353 192.168.0.105 >/dev/null 2>&1 || true":
SyntaxError: Unexpected token }
    at Object.parse (native)
    at /home/kodi/pimatic-app/node_modules/pimatic/node_modules/express/node_modules/connect/lib/middleware/json.js:75:25
    at IncomingMessage.onEnd (/home/kodi/pimatic-app/node_modules/pimatic/node_modules/express/node_modules/connect/node_modules/raw-body/index.js:109:7)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
11:56:34.109 [pimatic-location] error: { [Error: getaddrinfo EADDRINFO] code: 'EADDRINFO', errno: 'EADDRINFO', syscall: 'getaddrinfo' }
12:00:00.017 [pimatic] error: rule ping-iphone-to-be-awake error executing an action: spawn EMFILE
12:00:00.019 [pimatic] error: Error on evaluation of rule condition of rule ping-iphone-to-be-awake: spawn EMFILE
12:20:03.119 [pimatic] info: rule ping-iphone-to-be-awake: executed "sudo hping3 -2 -c 3 -p 5353 192.168.0.105 >/dev/null 2>&1 || true":
12:40:03.101 [pimatic] info: rule ping-iphone-to-be-awake: executed "sudo hping3 -2 -c 3 -p 5353 192.168.0.105 >/dev/null 2>&1 || true":
SyntaxError: Unexpected token }
    at Object.parse (native)
    at /home/kodi/pimatic-app/node_modules/pimatic/node_modules/express/node_modules/connect/lib/middleware/json.js:75:25
    at IncomingMessage.onEnd (/home/kodi/pimatic-app/node_modules/pimatic/node_modules/express/node_modules/connect/node_modules/raw-body/index.js:109:7)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
SyntaxError: Unexpected token }
    at Object.parse (native)
    at /home/kodi/pimatic-app/node_modules/pimatic/node_modules/express/node_modules/connect/lib/middleware/json.js:75:25
    at IncomingMessage.onEnd (/home/kodi/pimatic-app/node_modules/pimatic/node_modules/express/node_modules/connect/node_modules/raw-body/index.js:109:7)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

**Comment by sweetpi** [comment]
That could be the cause of the problem. It seems that for a api request the body can not be parsed because it isn't valid json. It could be that the response is never send in this case and so the connections are not closed.

Do you have and scripts that do api requests? Looking at the log, it looks like that the error seems to be happen every 20 minutes.

**Comment by georg90** [comment]
I have on that is updating every 45min..But the exception is in fact every ~1h

**Comment by sweetpi** [comment]
@georg90 I've added some additional error handling and check for unclosed requests in v0.8.73. Could you test with this version if you get any warnings?

**Comment by georg90** [comment]
Thank you, will watch it and report :)

**Comment by mwittig** [comment]
@sweetpi See also http://forum.pimatic.org/topic/562/problems-with-error-messages/3

Unfortunately, the error handling code does not dump details on the incoming request, i.e. originator, requested resources, data. May it would be helpful to use a request logger like morgan to get more details.

**Comment by georg90** [comment]
So today pimatic crashed again.
```
08:23:15.367 [pimatic] error: Could not write config file:  EMFILE, too many open files '/home/kodi/pimatic-app/config.json'
08:23:15.376 [pimatic] info: config.json updated
08:23:15.377 [pimatic] info: rule alloff: set $message to 0
08:40:00.020 [pimatic] error: rule ping-iphone-to-be-awake error executing an action: spawn EMFILE
08:40:00.021 [pimatic] error: Error on evaluation of rule condition of rule ping-iphone-to-be-awake: spawn EMFILE
08:53:59.265 [pimatic] error: Could not write config file:  EMFILE, too many open files '/home/kodi/pimatic-app/config.json'
08:53:59.275 [pimatic] info: config.json updated
08:53:59.277 [pimatic] info: rule check-if-somebody-is-at-home: set $ping to 0
09:00:00.019 [pimatic] error: rule ping-iphone-to-be-awake error executing an action: spawn EMFILE
09:00:00.020 [pimatic] error: Error on evaluation of rule condition of rule ping-iphone-to-be-awake: spawn EMFILE
09:00:00.274 [pimatic] info: rule heizungmorgensaus: set temp of Badezimmer to 17Â°C
09:00:00.477 [pimatic] info: rule heizungmorgensaus: set temp of Wohnzimmer to 18Â°C
09:00:00.679 [pimatic] info: rule heizungmorgensaus: set temp of Schlafzimmer to 18Â°C
09:20:00.020 [pimatic] error: rule ping-iphone-to-be-awake error executing an action: spawn EMFILE
09:20:00.021 [pimatic] error: Error on evaluation of rule condition of rule ping-iphone-to-be-awake: spawn EMFILE
09:40:00.019 [pimatic] error: rule ping-iphone-to-be-awake error executing an action: spawn EMFILE
09:40:00.021 [pimatic] error: Error on evaluation of rule condition of rule ping-iphone-to-be-awake: spawn EMFILE
10:00:00.020 [pimatic] error: rule ping-iphone-to-be-awake error executing an action: spawn EMFILE
10:00:00.021 [pimatic] error: Error on evaluation of rule condition of rule ping-iphone-to-be-awake: spawn EMFILE
10:00:00.159 [pimatic] error: Could not write config file:  EMFILE, too many open files '/home/kodi/pimatic-app/config.json'
10:00:00.168 [pimatic] info: config.json updated
10:00:00.169 [pimatic] info: rule reset-forceheizung-an: set $forceHeizungAn to 0
10:20:00.019 [pimatic] error: rule ping-iphone-to-be-awake error executing an action: spawn EMFILE
10:20:00.020 [pimatic] error: Error on evaluation of rule condition of rule ping-iphone-to-be-awake: spawn EMFILE
10:40:00.020 [pimatic] error: rule ping-iphone-to-be-awake error executing an action: spawn EMFILE
10:40:00.021 [pimatic] error: Error on evaluation of rule condition of rule ping-iphone-to-be-awake: spawn EMFILE
11:00:00.016 [pimatic] error: rule ping-iphone-to-be-awake error executing an action: spawn EMFILE
11:00:00.018 [pimatic] error: Error on evaluation of rule condition of rule ping-iphone-to-be-awake: spawn EMFILE
11:20:00.019 [pimatic] error: rule ping-iphone-to-be-awake error executing an action: spawn EMFILE
11:20:00.021 [pimatic] error: Error on evaluation of rule condition of rule ping-iphone-to-be-awake: spawn EMFILE
Unhandled rejection Error: spawn EMFILE
    at errnoException (child_process.js:988:11)
    at ChildProcess.spawn (child_process.js:935:11)
    at exports.spawn (child_process.js:723:9)
    at Object.exports.execFile (child_process.js:607:15)
    at exports.exec (child_process.js:578:18)
    at tryCatcher (/home/kodi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:24:31)
    at ret (eval at <anonymous> (/home/kodi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promisify.js:154:12), <anonymous>:13:23)
    at ShellSensor._getUpdatedAttributeValue (/home/kodi/pimatic-app/node_modules/pimatic-shell-execute/shell-execute.coffee:118:14)
    at null._onTimeout (/home/kodi/pimatic-app/node_modules/pimatic-shell-execute/shell-execute.coffee:110:10)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
11:40:00.019 [pimatic] error: rule ping-iphone-to-be-awake error executing an action: spawn EMFILE
11:40:00.020 [pimatic] error: Error on evaluation of rule condition of rule ping-iphone-to-be-awake: spawn EMFILE
```

lsof:
http://pastebin.com/raw.php?i=R1ubhuCJ

**Comment by sweetpi** [comment]
That's really strange, no timedout requests :(

Do you use android-location and if yes, with how many phones? Maybe it does not close the connections after the request finished.

**Comment by georg90** [comment]
I do.

**Comment by georg90** [comment]
With one phone.

**Comment by georg90** [comment]
So the pimatic-location plugin is deactivated and I still get the errors..
So I guess the rule has something to do with it after all:

```
if every 20 minutes then execute "sudo hping3 -2 -c 3 -p 5353 192.168.0.109 >/dev/null 2>&1 || true"
````

**Comment by georg90** [comment]
So I think it was my android app: https://github.com/georg90/pimatic-android-hybrid-app which was not closing the requests when paused or turned off. So everytime you'll open it, it will add a new connection (or reopen it, when paused). 
I changed that and didn't have any errors so far..will se if this fixes it.

I'd like pimatic to close idle connections after a while. since someone could just access your pimatic installation multiple times to shut it down - which is not very safe ? Is there a way to improve the stability on this one?

**Comment by mwittig** [comment]
In production, you would not expose an express server, but use a proxy which implements various strategies against DOS (teergrubing, limiting #connections per client, close idle connections, and such).  Express should also provide a strategy for idle connections, but I am not sure it is supported out-of-the-box. Maybe this is something a middleware used with express has to provide for.

**Comment by georg90** [comment]
@mwittig Maybe you could write a short article/howto about this? So one has the chance to secure the connection to pimatic?

**Comment by mwittig** [comment]
@georg90 OK, I think this should be a "HowTo" forum article. I'll put that on my TODO list.
