### ISSUE TITLE
[bug] can't use id name of dummy switch in rules

### ISSUE THREAD

**Issue by sweebee** [pimatic/pimatic#668]
I have this dummy switch:

```
{
      "class": "DummySwitch",
      "id": "alarm-switch",
      "name": "Alarm"
    },
```

If i try to add a rule with ```if alarm-switch is turned on``` i get:

```
Could not find an provider that decides next predicate of "alarm-switch is turned on"
```

**Comment by sweetpi** [comment]
Did you check that the device is loaded? Any warnings or errors in the log?

**Comment by sweebee** [comment]
If I use the name instead of the ID in the rule it works. This is what i get:

```
15:33:11.680 [pimatic] error: Could not find an provider that decides next predicate of "alarm-switch is turned on and thuis is closed".
15:33:11.685 [pimatic] debug: Error: Could not find an provider that decides next predicate of "alarm-switch is turned on and thuis is closed".
15:33:11.685 [pimatic] debug:>    at /home/xbian/pimatic-app/node_modules/pimatic/lib/rules.coffee:706:23
15:33:11.685 [pimatic] debug:>    at tryCatcher (/home/xbian/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:24:31)
15:33:11.685 [pimatic] debug:>    at Promise._settlePromiseFromHandler (/home/xbian/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:466:31)
15:33:11.685 [pimatic] debug:>    at Promise._settlePromiseAt (/home/xbian/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:545:18)
15:33:11.685 [pimatic] debug:>    at Promise._settlePromiseAtPostResolution (/home/xbian/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:229:10)
15:33:11.685 [pimatic] debug:>    at Async._drainQueue (/home/xbian/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:84:12)
15:33:11.685 [pimatic] debug:>    at Async._drainQueues (/home/xbian/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:89:10)
15:33:11.685 [pimatic] debug:>    at Async.drainQueues (/home/xbian/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:14:14)
15:33:11.685 [pimatic] debug:>    at process._tickCallback (node.js:415:13)
```

**Comment by sweetpi** [comment]
Found the bug, it was a serious bug while device name / id parsing. Is fixed in the new release.
