### ISSUE TITLE
pimatic-homeduino  version 0.8.56 buttons is not defined

### ISSUE THREAD

**Issue by Yves911** [pimatic/pimatic#702]
Since pimatic-homeduino  version 0.8.56, i have this error message

```
15:16:05.784 [pimatic] error: A uncaught exception occured: ReferenceError: buttons is not defined
15:16:05.784 [pimatic] error:>    at Board.<anonymous> (/root/pimatic-git/node_modules/pimatic-homeduino/homeduino.coffee:479:18)
15:16:05.784 [pimatic] error:>    at Board.EventEmitter.emit (events.js:117:20)
15:16:05.784 [pimatic] error:>    at Board._emitReceive (/root/pimatic-git/node_modules/pimatic-homeduino/node_modules/homeduino/lib/board.js:352:12)
15:16:05.784 [pimatic] error:>    at Board._handleRFControl (/root/pimatic-git/node_modules/pimatic-homeduino/node_modules/homeduino/lib/board.js:337:10)
15:16:05.784 [pimatic] error:>    at Board._onLine (/root/pimatic-git/node_modules/pimatic-homeduino/node_modules/homeduino/lib/board.js:142:21)
15:16:05.784 [pimatic] error:>    at SerialPortDriver.<anonymous> (/root/pimatic-git/node_modules/pimatic-homeduino/node_modules/homeduino/lib/board.js:83:22)
15:16:05.784 [pimatic] error:>    at SerialPortDriver.EventEmitter.emit (events.js:95:17)
15:16:05.784 [pimatic] error:>    at SerialPort.<anonymous> (/root/pimatic-git/node_modules/pimatic-homeduino/node_modules/homeduino/lib/driver/serialport.js:60:24)
15:16:05.784 [pimatic] error:>    at SerialPort.EventEmitter.emit (events.js:95:17)
15:16:05.784 [pimatic] error:>    at /root/pimatic-git/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/parsers.js:25:17
15:16:05.784 [pimatic] error:>    at Array.forEach (native)
15:16:05.784 [pimatic] error:>    at Object.parser (/root/pimatic-git/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/parsers.js:24:13)
15:16:05.784 [pimatic] error:>    at Object.SerialPort.options.dataCallback (/root/pimatic-git/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/serialport.js:168:15)
15:16:05.784 [pimatic] error:>    at SerialPortFactory.SerialPort._emitData (/root/pimatic-git/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/serialport.js:350:20)
15:16:05.784 [pimatic] error:>    at afterRead (/root/pimatic-git/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/serialport.js:326:20)
15:16:05.784 [pimatic] error:>    at /root/pimatic-git/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/serialport.js:342:9
15:16:05.784 [pimatic] error:>    at Object.wrapper [as oncomplete] (fs.js:454:17)
15:16:05.784 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!
```

**Comment by skipper79** [comment]
Same to me. And my switches does not work anymore 😏 since last update!

**Comment by Yves911** [comment]
@skipper79 you are right, switches are not functional anymore and pimatic see no more messages coming from my weather stations...

**Comment by sweetpi** [comment]
Thanks for the fast reporting. Should be fixed in v0.8.56. Can you confirm?

**Comment by Yves911** [comment]
Yes it's working fine now, thanks a lot !!!!!

**Comment by skipper79** [comment]
I agree. It's working now! Thx!
