### ISSUE TITLE
[pimatic-homeduino] Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Icesory** [pimatic/pimatic#711]
I run once a day in a failure with homeduino.
```
A uncaught exception occured: TypeError: Cannot read property 'length' of undefined at Function.Buffer.concat (buffer.js:491:20) at afterRead (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/serialport.js:323:36) at /home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/serialport.js:342:9 at Object.wrapper [as oncomplete] (fs.js:454:17) This is most probably a bug in pimatic or in a module, please report it!
```

It is possible, that my arduino has a failure. But at the moment i haven´t discovered the error.

**Comment by incmve** [comment]
Your not alone :)
https://github.com/pimatic/pimatic/issues/704

**Comment by sweetpi** [comment]
This error indicates a unstable serial connection. Try another arduino / power supply / kernal.
