### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ich92** [pimatic/pimatic#715]
Hello, I have the following error in pimatic:

```
error [pimatic]: A uncaught exception occured: Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'field list' 
at Query.Sequence._packetToError (/home/pi/pimatic-app/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14) 
at Query.ErrorPacket (/home/pi/pimatic-app/node_modules/mysql/lib/protocol/sequences/Query.js:83:18) 
at Protocol._parsePacket (/home/pi/pimatic-app/node_modules/mysql/lib/protocol/Protocol.js:274:23) 
at Parser.write (/home/pi/pimatic-app/node_modules/mysql/lib/protocol/Parser.js:77:12) 
at Protocol.write (/home/pi/pimatic-app/node_modules/mysql/lib/protocol/Protocol.js:39:16) 
at Socket.<anonymous> (/home/pi/pimatic-app/node_modules/mysql/lib/Connection.js:96:28) 
at Socket.EventEmitter.emit (events.js:95:17) 
at Socket.<anonymous> (_stream_readable.js:746:14) 
at Socket.EventEmitter.emit (events.js:92:17) 
at emitReadable_ (_stream_readable.js:408:10) 
at emitReadable (_stream_readable.js:404:5) 
at readableAddChunk (_stream_readable.js:165:9) 
at Socket.Readable.push (_stream_readable.js:127:10) 
at TCP.onread (net.js:526:21) -------------------- 
at Protocol._enqueue (/home/pi/pimatic-app/node_modules/mysql/lib/protocol/Protocol.js:135:48) 
at Connection.query (/home/pi/pimatic-app/node_modules/mysql/lib/Connection.js:201:25) 
at /home/pi/pimatic-app/node_modules/pimatic/node_modules/knex/lib/dialects/mysql/runner.js:42:16 
at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:24:31) 
at Promise._resolveFromResolver (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:439:31) 
at new Promise (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:53:37) 
at Runner_MySQL.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic/node_modules/knex/lib/dialects/mysql/runner.js:41:10) 
at Runner_MySQL.tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:24:31) 
at Runner_MySQL._query (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/method.js:15:34) 
at Runner_MySQL.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic/node_modules/knex/lib/runner.js:125:15) 
at Runner_MySQL.tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:24:31) 
at Runner_MySQL.query (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/method.js:15:34) 
at Runner_MySQL.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic/node_modules/knex/lib/runner.js:172:17) 
at Runner_MySQL.tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:24:31) 
at Runner_MySQL.transactionQuery (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/method.js:15:34) 
at Runner_MySQL.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic/node_modules/knex/lib/runner.js:27:17) 
at Runner_MySQL.tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:24:31) 
at Runner_MySQL.run (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/method.js:15:34) 
at QueryBuilder_MySQL.Target.then (/home/pi/pimatic-app/node_modules/pimatic/node_modules/knex/lib/interface.js:27:27) 
at QueryBuilder_MySQL.tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:24:31) 
at doThenable (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/thenables.js:52:38) 
at tryConvertToPromise (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/thenables.js:30:20) 
at PromiseArray.init [as _init] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise_array.js:79:28) 
at new PromiseArray (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise_array.js:24:10) 
at Function.Promise.all (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:156:12) 
at /home/pi/pimatic-app/node_modules/pimatic/lib/database.coffee:547:26 
at /home/pi/pimatic-app/node_modules/pimatic/lib/database.coffee:210:20 
at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:24:31) 
at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:466:31) 
at Promise._settlePromiseAt (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:545:18) 
at Promise._settlePromiseAtPostResolution (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:229:10) 
at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:84:12) 
at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:89:10) 
at Async.drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:14:14) 
at process._tickCallback (node.js:415:13) This is most probably a bug in pimatic or in a module, please report it!
```

**Comment by sweetpi** [comment]
Thanks for reporting. Could you post your database config?

**Comment by ich92** [comment]
I think the error message comes from the openweather-plugin from the rain data

My database configuration:
"database": {
      "client": "mysql",
      "connection": {
        "host": "127.0.0.1",
        "user": "root",
        "password": "********",
        "database": "pimatic"
      },
      "deviceAttributeLogging": [
        {
          "deviceId": "*",
          "attributeName": "*",   
"type": "*",
          "interval": "0",
          "expire": "7d"
        },
        {
          "deviceId": "*",
          "attributeName": "*",
          "type": "continuous",
          "interval": "5min",
          "expire": "7d"
        },
        {
          "deviceId": "*",
          "attributeName": "temperature",
          "type": "number",
          "expire": "1y"
        },
        {
          "deviceId": "*",
          "attributeName": "humidity",
          "type": "number",
          "expire": "1y"
        }
      ],
      "messageLogging": [
        {
          "level": "*",
          "tags": [],
          "expire": "7d"
        },
        {
          "level": "debug",
          "tags": [],
          "expire": "0"
        }
      ]
    }

**Comment by sweetpi** [comment]
I think you are right. Should be fixed with pimatic v0.8.85. Please reopen if the issue still exists.

**Comment by mwittig** [comment]
@sweetpi I am happy to revise the openweather plugin. Currently, values are initialized with "null". In case data cannot be acquired from openweather (sometimes rain data is not contained in the data set!) the value is invalid. Shall we set initial values to "0"? What are your throught on this.

**Comment by sweetpi** [comment]
null as initial value is absolutely perfect. However it shouldn't be NaN.

**Comment by mwittig** [comment]
Ok, I'll add some assertions on my dev fork to see if I can reproduce a NaN case, e.g. invalid data received from openweather
