### ISSUE TITLE
error [pimatic]: Pushover: Parse Error

### ISSUE THREAD

**Issue by p4co86** [pimatic/pimatic#752]
today i get this error message:
```
error [pimatic]: Error on evaluation of rule condition of rule monatlicher-stromverbrauch: Parse Error
00:02:05error [pimatic]: rule monatlicher-stromverbrauch error executing an action: Parse Error
00:02:05error [pimatic]: A uncaught exception occured: SyntaxError: Unexpected end of input at Object.parse (native) at Pushover.errors (/root/pimatic-app/node_modules/pimatic-pushover/node_modules/pushover-notifications/lib/pushover.js:74:12) at IncomingMessage.<anonymous> (/root/pimatic-app/node_modules/pimatic-pushover/node_modules/pushover-notifications/lib/pushover.js:144:9) at IncomingMessage.EventEmitter.emit (events.js:117:20) at _stream_readable.js:920:16 at process._tickDomainCallback (node.js:459:13) This is most probably a bug in pimatic or in a module, please report it!
``

**Comment by p4co86** [comment]
here with debug:
```
debug [pimatic]: Error: Parse Error at CleartextStream.socketOnData (http.js:1583:20) at CleartextStream.read [as _read] (tls.js:511:12) at CleartextStream.Readable.read (_stream_readable.js:320:10) at EncryptedStream.write [as _write] (tls.js:366:25) at doWrite (_stream_writable.js:221:10) at writeOrBuffer (_stream_writable.js:211:5) at EncryptedStream.Writable.write (_stream_writable.js:180:11) at write (_stream_readable.js:583:24) at flow (_stream_readable.js:592:7) at Socket.pipeOnReadable (_stream_readable.js:624:5) at Socket.EventEmitter.emit (events.js:92:17) at emitReadable_ (_stream_readable.js:408:10) at emitReadable (_stream_readable.js:404:5) at readableAddChunk (_stream_readable.js:165:9) at Socket.Readable.push (_stream_readable.js:127:10) at TCP.onread (net.js:526:21)
16:12:01error [pimatic]: Error on evaluation of rule condition of rule wettervorhersage-schicken: Parse Error
16:12:01debug [pimatic]: Error: Parse Error at CleartextStream.socketOnData (http.js:1583:20) at CleartextStream.read [as _read] (tls.js:511:12) at CleartextStream.Readable.read (_stream_readable.js:320:10) at EncryptedStream.write [as _write] (tls.js:366:25) at doWrite (_stream_writable.js:221:10) at writeOrBuffer (_stream_writable.js:211:5) at EncryptedStream.Writable.write (_stream_writable.js:180:11) at write (_stream_readable.js:583:24) at flow (_stream_readable.js:592:7) at Socket.pipeOnReadable (_stream_readable.js:624:5) at Socket.EventEmitter.emit (events.js:92:17) at emitReadable_ (_stream_readable.js:408:10) at emitReadable (_stream_readable.js:404:5) at readableAddChunk (_stream_readable.js:165:9) at Socket.Readable.push (_stream_readable.js:127:10) at TCP.onread (net.js:526:21)
16:12:01error [pimatic]: rule wettervorhersage-schicken error executing an action: Parse Error
```

and this is the rule:
```
if it is 06:00 then pushover title:"wettervorhersage" message:"Es wird heute mindestens $wettervorhersage-temperature-min °C und maximal $wettervorhersage-temperatur-max °C bei $wettervorhersage-status" device:"Stefan"
```
