### ISSUE TITLE
pimatic crash: max plugin uncaught exception error

### ISSUE THREAD

**Issue by Pastinakel** [pimatic/pimatic#754]
```
08:38:34.225 [pimatic] Listening for HTTP-request on port 80...
08:38:34.404 [pimatic] A uncaught exception occured: TypeError: Cannot call method 'toString' of undefined
08:38:34.404 [pimatic]>    at MaxCube.parseCommandMetadata (/home/pi/pimatic-app/node_modules/pimatic-max/node_modules/max-control/index.js:173:47)
08:38:34.404 [pimatic]>    at MaxCube.parseCommand (/home/pi/pimatic-app/node_modules/pimatic-max/node_modules/max-control/index.js:109:19)
08:38:34.404 [pimatic]>    at MaxCube.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-max/node_modules/max-control/index.js:66:26)
08:38:34.404 [pimatic]>    at Array.forEach (native)
08:38:34.404 [pimatic]>    at MaxCube.onData (/home/pi/pimatic-app/node_modules/pimatic-max/node_modules/max-control/index.js:61:8)
08:38:34.404 [pimatic]>    at Socket.EventEmitter.emit (events.js:95:17)
08:38:34.404 [pimatic]>    at Socket.<anonymous> (_stream_readable.js:746:14)
08:38:34.404 [pimatic]>    at Socket.EventEmitter.emit (events.js:92:17)
08:38:34.404 [pimatic]>    at emitReadable_ (_stream_readable.js:408:10)
08:38:34.404 [pimatic]>    at emitReadable (_stream_readable.js:404:5)
08:38:34.404 [pimatic]>    at readableAddChunk (_stream_readable.js:165:9)
08:38:34.404 [pimatic]>    at Socket.Readable.push (_stream_readable.js:127:10)
08:38:34.404 [pimatic]>    at TCP.onread (net.js:526:21)
08:38:34.404 [pimatic]> This is most probably a bug in pimatic or in a module, please report it!
08:38:34.446 [pimatic] shutting pimatic down...
```

Pimatic does not start ... any clues? The max cube is responding on the defined address and port (tested with telnet).

**Comment by mwittig** [comment]
Seems to be a bug in the underlying max-control package maintained by @sweetpi 
https://github.com/sweetpi/max-control/blob/master/index.js#L173
