### ISSUE TITLE
error please report it!

### ISSUE THREAD

**Issue by justice70** [pimatic/pimatic#763]
error [pimatic]: A uncaught exception occured: Error: dns service error: unknown
    at Advertisement.on_service_registered (/home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:42:24)
    at SocketWatcher.MDNSService.self.watcher.callback (/home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/mdns/lib/mdns_service.js:18:40)
 This is most probably a bug in pimatic or in a module, please report it!

**Comment by mwittig** [comment]
Seems to be an issue with pimatic-hap!
Please report the issue at https://github.com/michbeck100/pimatic-hap and close this issue. Thanks!

**Comment by justice70** [comment]
thanks for answer 
sorry but it was working fine until update piratic 1 hour ago
