### ISSUE TITLE
[pimatic-openweather] A uncaught exception occured: Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by hansjeu** [pimatic/pimatic#772]
```
error [pimatic]: A uncaught exception occured: Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
 This is most probably a bug in pimatic or in a module, please report it!
04:02:20error [pimatic]: A uncaught exception occured: Error: read ECONNRESET
    at errnoException (net.js:901:11)
    at TCP.onread (net.js:556:19)
 This is most probably a bug in pimatic or in a module, please report it!
02:19:59error [pimatic]: A uncaught exception occured: TypeError: Cannot read property 'icon' of undefined
    at /home/pi/pimatic-app/node_modules/pimatic-openweather/node_modules/openweathermap/openweather.js:99:67
    at IncomingMessage.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-openweather/node_modules/openweathermap/openweather.js:155:16)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickDomainCallback (node.js:459:13)
 This is most probably a bug in pimatic or in a module, please report it!

**Comment by mwittig** [comment]
Does the issue occurs repeately? 
Did you change openweather settings recently?
Can you please post the openweather device configuration you're using (xxx out your API key)?

**Comment by hansjeu** [comment]
i did not change anything.

    {
      "plugin": "openweather",
      "apiKey": "xxxxxxxxxxx"
    },
    {
      "id": "weather",
      "class": "OpenWeatherDevice",
      "name": "Huidig Weer Nijmegen",
      "location": "Nijmegen, Netherlands",
      "units": "metric",
      "lang": "nl",
      "timeout": 600000
    },
    {
      "id": "forecast",
      "class": "OpenWeatherForecastDevice",
      "name": "Voorspelling Weer Nijmegen",
      "location": "Nijmegen, Netherlands",
      "units": "metric",
      "lang": "nl",
      "timeout": 600000,
      "day": 1
    },

Had the same errors on a pimatic i am building for friends at aboud the same time.
error [pimatic]: A uncaught exception occured: Error: connect ETIMEDOUT
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
 This is most probably a bug in pimatic or in a module, please report it!
05:03:09error [pimatic]: A uncaught exception occured: Error: connect ETIMEDOUT
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
 This is most probably a bug in pimatic or in a module, please report it!
04:44:08error [pimatic]: A uncaught exception occured: Error: connect ETIMEDOUT
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
 This is most probably a bug in pimatic or in a module, please report it!
04:06:56error [pimatic]: A uncaught exception occured: Error: socket hang up
    at createHangUpError (http.js:1472:15)
    at CleartextStream.socketOnEnd [as onend] (http.js:1568:23)
    at CleartextStream.onCryptoStreamEnd (tls.js:320:24)
    at CleartextStream.g (events.js:180:16)
    at CleartextStream.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickDomainCallback (node.js:459:13)
 This is most probably a bug in pimatic or in a module, please report it!
04:06:56error [pimatic]: A uncaught exception occured: Error: socket hang up
    at createHangUpError (http.js:1472:15)
    at CleartextStream.socketCloseListener (http.js:1522:23)
    at CleartextStream.EventEmitter.emit (events.js:117:20)
    at tls.js:696:10
    at process._tickDomainCallback (node.js:459:13)
 This is most probably a bug in pimatic or in a module, please report it!
01:56:19error [pimatic]: A uncaught exception occured: TypeError: Cannot read property 'icon' of undefined
    at /home/pi/pimatic-app/node_modules/pimatic-openweather/node_modules/openweathermap/openweather.js:99:67
    at IncomingMessage.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-openweather/node_modules/openweathermap/openweather.js:155:16)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickDomainCallback (node.js:459:13)
 This is most probably a bug in pimatic or in a module, please report it!

**Comment by sweetpi** [comment]
Hm I thought I have fixed all this problems long ago in the openweather module..

**Comment by hansjeu** [comment]
i will keep watching it.
maybe its a problem of the site.
Report tomorrow if thats ok

**Comment by sweetpi** [comment]
Big thanks for reporting. It looks like a networt error (Either openweather was down or your internet connection). However obviously we don't handle these errors correctly, so that it gets to the global error handler which shouts out loud :D.

**Comment by hansjeu** [comment]
I had these errors on two machines on two differend internet connections and providers.
So i think you do not have to look to that option, the chance of two differend providers craching at the sane time is to small) therfore i think openweather had problems. funny that only i reported it.

**Comment by hansjeu** [comment]
No errors today

Greets Hans

**Comment by mwittig** [comment]
Looking at the timestamps of the two exception, I think the ECONNRESET exception possibly is not related to openweathermap. There is a gap of 39 seconds between the two exceptions.

**Comment by sweetpi** [comment]
I added some code to trace the cause of the ECONNRESET exception in pimatic v0.8.102. Please update to the newest version and reopen with the new error message when the error happens again.
