### ISSUE TITLE
[pimatic-homeduino] timeout

### ISSUE THREAD

**Issue by p4co86** [pimatic/pimatic#775]
I get this error, arduino ist flashed and all worked finde before.

error [pimatic-homeduino]: TimeoutError: operation timed out
    at afterTimeout (/root/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/bluebird/js/main/timers.js:11:15)
    at timeoutTimeout (/root/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/bluebird/js/main/timers.js:53:9)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

**Comment by matthijsf** [comment]
Did you ever resolve this? I’ve got the same issue
