### ISSUE TITLE
[pimatic-fritz] Unhandled rejection Error: [object Object]

### ISSUE THREAD

**Issue by thost96** [pimatic/pimatic#807]
I have added pimatic-fritz to my config for switching guest wifi on and off. Now i'm getting this error: 
```
Unhandled rejection Error: [object Object]
    at Object.ensureErrorObject (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:261:20)
    at Promise._rejectUncheckedCheckError (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:657:22)
    at Promise._settlePromise (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/promise.js:542:21)
    at Promise._settlePromise0 (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/promise.js:590:10)
    at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/promise.js:669:18)
    at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/async.js:125:16)
    at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/async.js:135:10)
    at Async.drainQueues (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/async.js:16:14)
    at process._tickCallback (node.js:415:13)
```

here is my fritz plugin config:

```
{
      "plugin": "fritz",
      "url": "http://192.168.XXX.XXX",
      "user": "XXX",
      "password": "XXX",
      "interval": 3600
},

{
      "id": "guest-wlan",
      "name": "Gast WLAN",
      "class": "FritzWlan"
},

```

What is causing this rejection?

**Comment by mwittig** [comment]
Hi, pimatic-fritz has its own issues queue. To get support from the plugin maintainer, please file the issue at https://github.com/andig/pimatic-fritz/issues
