### ISSUE TITLE
config_default.json is propably outdated

### ISSUE THREAD

**Issue by Wandmalfarbe** [pimatic/pimatic#810]
After starting pimatic for the first time I get the following error:

```
23:42:22.208 [pimatic] error: Invalid config: Missing property "authentication,httpsServer,gui" in /settings
23:42:23.179 [pimatic] error: Startup error: Error: Authentication is enabled, but no password has been defined for the user "admin". Please define a password for "admin" in the users section of the config.json file or disable authentication.
23:42:23.179 [pimatic] error:>    at Framework._setupExpressApp (/home/pi/pimatic-app/node_modules/pimatic/lib/framework.coffee:276:23)
23:42:23.179 [pimatic] error:>    at new Framework (/home/pi/pimatic-app/node_modules/pimatic/lib/framework.coffee:78:8)
23:42:23.179 [pimatic] error:>    at /home/pi/pimatic-app/node_modules/pimatic/startup.coffee:51:21
23:42:23.179 [pimatic] error:>    at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:26:23)
23:42:23.179 [pimatic] error:>    at Function.Promise.attempt.Promise.try (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/method.js:31:24)
23:42:23.179 [pimatic] error:>    at Object.startup (/home/pi/pimatic-app/node_modules/pimatic/startup.coffee:50:10)
23:42:23.179 [pimatic] error:>    at run (/home/pi/pimatic-app/node_modules/pimatic/pimatic.js:15:24)
23:42:23.179 [pimatic] error:>    at /home/pi/pimatic-app/node_modules/pimatic/lib/daemon.coffee:87:9
23:42:23.179 [pimatic] error:>    at FSReqWrap.oncomplete (fs.js:82:15)
23:42:23.182 [pimatic] info: exiting...
```

When I add the missing properties by hand everything is ok. After my modifications the config.json looks like this:

```
{
  "//": "Please only change this file when pimatic is NOT running, otherwise pimatic will overwrite your changes.",
  "settings": {
    "httpServer": {
      "enabled": true,
      "port": 80
    },
    "authentication": {
      "enabled": false
    },
    "httpsServer": {
      "enabled": false
    },
    "gui": {}
  },
 ...
```

**Comment by incmve** [comment]
There is no default password in the config file that's why you get that error.

**Comment by sweetpi** [comment]
@Wandmalfarbe Thanks for reporting.

> `23:42:22.208 [pimatic] error: Invalid config: Missing property "authentication,httpsServer,gui" in /settings`

You are right the default config is missing some values, that should be present. I will fix this.

> `23:42:23.179 [pimatic] error: Startup error: Error: Authentication is enabled, but no password has been defined for the user "admin". Please define a password for "admin" in the users section of the config.json file or disable authentication.`

This is normal behaviour if you have not set an password (like @incmve mentioned).

**Comment by sweetpi** [comment]
Fixed in development branch.
