### ISSUE TITLE
Pimatic ask to report this to you.

### ISSUE THREAD

**Issue by hansjeu** [pimatic/pimatic#823]
error [pimatic]: A uncaught exception occured: Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
 This is most probably a bug in pimatic or in a module, please report it!
01:26:50error [pimatic]: A uncaught exception occured: Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
 This is most probably a bug in pimatic or in a module, please report it!
01:25:50error [pimatic]: A uncaught exception occured: Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
 This is most probably a bug in pimatic or in a module, please report it!
01:24:50error [pimatic]: A uncaught exception occured: Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
 This is most probably a bug in pimatic or in a module, please report it!
01:23:50error [pimatic]: A uncaught exception occured: Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
 This is most probably a bug in pimatic or in a module, please report it!

**Comment by sweetpi** [comment]
Thanks for reporting, can you post your installed and activated plugins? Best would be the startup log with the plugin names and versions.

**Comment by sweetpi** [comment]
I added some code to trace the error down to the causing plugin. Please update to pimatic v0.8.102 and report with the new logged error message if the problem happens again.
