### ISSUE TITLE
[v0.9] Error editing device

### ISSUE THREAD

**Issue by sweebee** [pimatic/pimatic#832]
Pimatic crashes when editing (recreating) a device:

```
atal Error: Destroy called, but setup was not called!
    at ContactActionHandler.ActionHandler.destroy (/home/pi/pimatic-app/node_modules/pimatic/lib/actions.coffee:66:43)
    at /home/pi/pimatic-app/node_modules/pimatic/lib/rules.coffee:636:30
    at RuleManager._destroyActionsAndCancelSheduledActions (/home/pi/pimatic-app/node_modules/pimatic/lib/rules.coffee:634:11)
    at /home/pi/pimatic-app/node_modules/pimatic/lib/rules.coffee:776:12
    at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:680:18)
    at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:126:16)
    at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
```

**Comment by sweetpi** [comment]
Dublicate of #831

**Comment by sweebee** [comment]
Still not always working after update:

happens like 1/4 times.

```
09:11:02.225 [pimatic] Recreating "Tafel"...
Fatal Error: Destroy called, but setup was not called!
    at SetVariableActionHandler.ActionHandler.destroy (/home/pi/pimatic-app/node_modules/pimatic/lib/actions.coffee:66:43)
    at /home/pi/pimatic-app/node_modules/pimatic/lib/rules.coffee:636:30
    at RuleManager._destroyActionsAndCancelSheduledActions (/home/pi/pimatic-app/node_modules/pimatic/lib/rules.coffee:634:11)
    at /home/pi/pimatic-app/node_modules/pimatic/lib/rules.coffee:776:12
    at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:680:18)
    at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:126:16)
    at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
```

**Comment by sweetpi** [comment]
The SetVariableActionHandler was missing... Should be really fixed now.
