### ISSUE TITLE
v0.9 Plugin installation now gives all kind errors

### ISSUE THREAD

**Issue by mwittig** [pimatic/pimatic#833]
When I do the installation from the command line (pimatic-prowl) it works

```
00:59:44.058 [pimatic, npm] info: WARN unmet dependency /home/pi/pimatic-dev/node_modules/pimatic-mobile-frontend/node_modules/pimatic/node_modules/decl-api requir
es lodash@'~2.4.1' but will load
00:59:44.064 [pimatic, npm] info: WARN unmet dependency /home/pi/pimatic-dev/node_modules/pimatic-mobile-frontend/node_modules/pimatic/node_modules/lodash,
00:59:44.066 [pimatic, npm] info: WARN unmet dependency which is version 3.10.1
00:59:44.067 [pimatic, npm] info: WARN unmet dependency /home/pi/pimatic-dev/node_modules/pimatic-mobile-frontend/node_modules/pimatic/node_modules/decl-api requir
es bluebird@'~2.3.0' but will load
00:59:44.069 [pimatic, npm] info: WARN unmet dependency /home/pi/pimatic-dev/node_modules/pimatic-mobile-frontend/node_modules/pimatic/node_modules/bluebird,
00:59:44.074 [pimatic, npm] info: WARN unmet dependency which is version 3.3.4
00:59:44.076 [pimatic, npm] info: WARN unmet dependency /home/pi/pimatic-dev/node_modules/pimatic-mobile-frontend/node_modules/pimatic/node_modules/knex requires b
luebird@'^2.9.24' but will load
00:59:44.078 [pimatic, npm] info: WARN unmet dependency /home/pi/pimatic-dev/node_modules/pimatic-mobile-frontend/node_modules/pimatic/node_modules/bluebird,
00:59:44.079 [pimatic, npm] info: WARN unmet dependency which is version 3.3.4
00:59:44.206 [pimatic, npm] info: ERR! Linux 4.1.18-v7+
00:59:44.211 [pimatic, npm] info: ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pimatic-prowl"
00:59:44.214 [pimatic, npm] info: ERR! node v4.4.0
00:59:44.217 [pimatic, npm] info: ERR! npm  v2.15.0
00:59:44.220 [pimatic, npm] info: ERR! code EPEERINVALID
00:59:44.246 [pimatic, npm] info: ERR! peerinvalid The package pimatic@0.9.0 does not satisfy its siblings' peerDependencies requirements!
00:59:44.251 [pimatic, npm] info: ERR! peerinvalid Peer pimatic-cron@0.8.6 wants pimatic@0.8.*
00:59:44.253 [pimatic, npm] info: ERR! peerinvalid Peer pimatic-denon-avr@0.8.6 wants pimatic@0.8.*
00:59:44.255 [pimatic, npm] info: ERR! peerinvalid Peer pimatic-edimax@0.3.5 wants pimatic@0.8.*
00:59:44.257 [pimatic, npm] info: ERR! peerinvalid Peer pimatic-filter@0.8.6 wants pimatic@0.8.*
00:59:44.259 [pimatic, npm] info: ERR! peerinvalid Peer pimatic-gpio@0.8.13 wants pimatic@0.8.*
00:59:44.261 [pimatic, npm] info: ERR! peerinvalid Peer pimatic-johnny-five@0.8.8 wants pimatic@0.8.*
00:59:44.264 [pimatic, npm] info: ERR! peerinvalid Peer pimatic-links@0.8.5 wants pimatic@0.8.*
00:59:44.267 [pimatic, npm] info: ERR! peerinvalid Peer pimatic-mail@0.8.5 wants pimatic@0.8.*
00:59:44.269 [pimatic, npm] info: ERR! peerinvalid Peer pimatic-mobile-frontend@0.9.0 wants pimatic@0.9.*
00:59:44.272 [pimatic, npm] info: ERR! peerinvalid Peer pimatic-openweather@0.8.19 wants pimatic@0.8.*
00:59:44.280 [pimatic, npm] info: ERR! peerinvalid Peer pimatic-probe@0.2.2 wants pimatic@>0.8.19
00:59:44.282 [pimatic, npm] info: ERR! peerinvalid Peer pimatic-prowl@0.0.2 wants pimatic@>=0.8.0 <1.0.0
00:59:44.284 [pimatic, npm] info: ERR! peerinvalid Peer pimatic-shell-execute@0.8.17 wants pimatic@0.8.*
00:59:44.286 [pimatic, npm] info: ERR! peerinvalid Peer pimatic-solarview@0.8.3 wants pimatic@0.8.*
00:59:44.288 [pimatic, npm] info: ERR! peerinvalid Peer pimatic-upnp-root@0.8.9 wants pimatic@>0.8.19
00:59:44.310 [pimatic, npm] info: ERR! Please include the following file with any support request:
00:59:44.312 [pimatic, npm] info: ERR!     /home/pi/pimatic-dev/npm-debug.log
00:59:44.342 [pimatic] error: Error Updating plugin pimatic-prowl: Error running "npm install pimatic-prowl"
00:59:44.347 [pimatic] debug: Error: Error running "npm install pimatic-prowl"
00:59:44.347 [pimatic] debug:>    at ChildProcess.<anonymous> (/home/pi/pimatic-dev/node_modules/pimatic/lib/plugins.coffee:290:24)
00:59:44.347 [pimatic] debug:>    at emitTwo (events.js:87:13)
00:59:44.347 [pimatic] debug:>    at ChildProcess.emit (events.js:172:7)
00:59:44.347 [pimatic] debug:>    at maybeClose (internal/child_process.js:827:16)
00:59:44.347 [pimatic] debug:>    at Socket.<anonymous> (internal/child_process.js:319:11)
00:59:44.347 [pimatic] debug:>    at emitOne (events.js:77:13)
00:59:44.347 [pimatic] debug:>    at Socket.emit (events.js:169:7)
00:59:44.347 [pimatic] debug:>    at Socket.emit (/home/pi/pimatic-dev/node_modules/pimatic/startup.coffee:63:24)
00:59:44.347 [pimatic] debug:>    at Pipe._onclose (net.js:475:12)
q

**Comment by sweetpi** [comment]
> 00:59:44.220 [pimatic, npm] info: ERR! code EPEERINVALID

This happens, because not all installed plugins have updated peerDependencies. It will go away if all plugins are marked compatible.

**Comment by sweebee** [comment]
What i do is change the package.json. And add pimatic 0.9 support. and then manually npm install. If it still doesn't work check if it uses some old libraries and check if a newer version works. Like homeduino wants an old version of serialport.

**Comment by mwittig** [comment]
@sweetpi I still dont't get it

```
00:59:44.246 [pimatic, npm] info: ERR! peerinvalid The package pimatic@0.9.0 does not satisfy its siblings' peerDependencies requirements!
...
00:59:44.282 [pimatic, npm] info: ERR! peerinvalid Peer pimatic-prowl@0.0.2 wants pimatic@>=0.8.0 <1.0.0
```

">=0.8.0 <1.0.0" should work.

**Comment by sweetpi** [comment]
I'm not sure but maybe its beacause the peer dependcies of imatic-prowl conflict with for example pimatic-openweather. Maybe on wron peerDependency does make all plugins shout :D

**Comment by sweetpi** [comment]
If one plugin has a wrong peer-dependency all following plugin installations throw the 'EPEERINVALID' error. I added some code to ignore this error.
