### ISSUE TITLE
[v0.9.1] whenPredicateIsTrue is not defined

### ISSUE THREAD

**Issue by sweebee** [pimatic/pimatic#834]
Got this error when a pir status is  received:

```
08:23:00.136 [pimatic] error: A uncaught exception occured: ReferenceError: whenPredicateIsTrue is not defined
08:23:00.136 [pimatic] error:>    at EveryCronPredicateHandler.p.handler.on.changeListener (/home/pi/pimatic-app/node_modules/pimatic/lib/rules.coffee:598:17)
08:23:00.136 [pimatic] error:>    at emitOne (events.js:77:13)
08:23:00.136 [pimatic] error:>    at EveryCronPredicateHandler.emit (events.js:169:7)
08:23:00.136 [pimatic] error:>    at [object Object]._onTimeout (/home/pi/pimatic-app/node_modules/pimatic-cron/cron.coffee:426:12)
08:23:00.136 [pimatic] error:>    at Timer.listOnTimeout (timers.js:89:15)
08:23:00.136 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!
08:23:00.141 [pimatic] warn: Keeping pimatic alive, but could be in an undefined state, please restart pimatic as soon as possible!
```

**Comment by sweebee** [comment]
```
09:20:23.633 [pimatic] A uncaught exception occured: ReferenceError: whenPredicateIsTrue is not defined
09:20:23.633 [pimatic]>    at DeviceAttributePredicateHandler.p.handler.on.changeListener (/home/pi/pimatic-app/node_modules/pimatic/lib/rules.coffee:598:17)
09:20:23.633 [pimatic]>    at emitOne (events.js:77:13)
09:20:23.633 [pimatic]>    at DeviceAttributePredicateHandler.emit (events.js:169:7)
09:20:23.633 [pimatic]>    at MySensorsLight.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic/lib/predicates.coffee:429:12)
09:20:23.633 [pimatic]>    at emitOne (events.js:82:20)
09:20:23.633 [pimatic]>    at MySensorsLight.emit (events.js:169:7)
09:20:23.633 [pimatic]>    at Board.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-mysensors/MySensors.coffee:944:16)
09:20:23.633 [pimatic]>    at emitOne (events.js:82:20)
09:20:23.633 [pimatic]>    at Board.emit (events.js:169:7)
09:20:23.633 [pimatic]>    at Board._rfsendtoboard (/home/pi/pimatic-app/node_modules/pimatic-mysensors/MySensors.coffee:274:10)
09:20:23.633 [pimatic]>    at Board._rfReceived (/home/pi/pimatic-app/node_modules/pimatic-mysensors/MySensors.coffee:179:12)
09:20:23.633 [pimatic]>    at SerialPortDriver.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-mysensors/MySensors.coffee:148:10)
09:20:23.633 [pimatic]>    at emitOne (events.js:77:13)
09:20:23.633 [pimatic]>    at SerialPortDriver.emit (events.js:169:7)
09:20:23.633 [pimatic]>    at SerialPort.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-mysensors/serialport.coffee:44:10)
09:20:23.633 [pimatic]>    at emitOne (events.js:77:13)
09:20:23.633 [pimatic]>    at SerialPort.emit (events.js:169:7)
09:20:23.633 [pimatic]>    at /home/pi/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/parsers.js:25:17
09:20:23.633 [pimatic]>    at Array.forEach (native)
09:20:23.633 [pimatic]>    at Object.parser (/home/pi/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/parsers.js:24:13)
09:20:23.633 [pimatic]>    at Object.SerialPort.opts.dataCallback (/home/pi/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/serialport.js:181:12)
09:20:23.633 [pimatic]>    at SerialPortFactory.SerialPort._emitData (/home/pi/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/serialport.js:396:20)
09:20:23.633 [pimatic]>    at afterRead (/home/pi/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/serialport.js:372:20)
09:20:23.633 [pimatic]>    at /home/pi/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/serialport.js:388:9
09:20:23.633 [pimatic]>    at FSReqWrap.wrapper [as oncomplete] (fs.js:576:17)
09:20:23.633 [pimatic]> This is most probably a bug in pimatic or in a module, please report it!
```

**Comment by sweetpi** [comment]
Fixes
