### ISSUE TITLE
[v0.9] Error on incoming http request: Can't set headers after they are sent. Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by mwittig** [pimatic/pimatic#836]
What I did 
- Removed all plugins except for pimatic-mobile-frontend
- Started with a fresh config (copy from template plus admin password set)

```
12:52:51.171 2016-03-22 Tuesday
12:52:55.875 [pimatic] info: Starting pimatic version 0.9.1
12:52:57.084 [pimatic] info: Installing: "pimatic-cron" from npm-registry.
12:53:00.717 [pimatic, npm] info: WARN peerDependencies The peer dependency pimatic@>=0.8.0 <0.9.0 included from pimatic-cron will no
12:53:00.726 [pimatic, npm] info: WARN peerDependencies longer be automatically installed to fulfill the peerDependency
12:53:00.728 [pimatic, npm] info: WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
12:53:13.671 [pimatic, npm] info: WARN unmet dependency /home/pi/pimatic-dev/node_modules/pimatic-mobile-frontend/node_modules/pimatic/node_modules/decl-api requires lodash@'~2.4.1' but will load
12:53:13.675 [pimatic, npm] info: WARN unmet dependency /home/pi/pimatic-dev/node_modules/pimatic-mobile-frontend/node_modules/pimatic/node_modules/lodash,
12:53:13.676 [pimatic, npm] info: WARN unmet dependency which is version 3.10.1
12:53:13.684 [pimatic, npm] info: WARN unmet dependency /home/pi/pimatic-dev/node_modules/pimatic-mobile-frontend/node_modules/pimatic/node_modules/decl-api requires bluebird@'~2.3.0' but will load
12:53:13.687 [pimatic, npm] info: WARN unmet dependency /home/pi/pimatic-dev/node_modules/pimatic-mobile-frontend/node_modules/pimatic/node_modules/bluebird,
12:53:13.688 [pimatic, npm] info: WARN unmet dependency which is version 3.3.4
12:53:13.691 [pimatic, npm] info: WARN unmet dependency /home/pi/pimatic-dev/node_modules/pimatic-mobile-frontend/node_modules/pimatic/node_modules/knex requires bluebird@'^2.9.24' but will load
12:53:13.697 [pimatic, npm] info: WARN unmet dependency /home/pi/pimatic-dev/node_modules/pimatic-mobile-frontend/node_modules/pimatic/node_modules/bluebird,
12:53:13.701 [pimatic, npm] info: WARN unmet dependency which is version 3.3.4
12:53:13.825 [pimatic, npm] info: ERR! Linux 4.1.18-v7+
12:53:13.836 [pimatic, npm] info: ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pimatic-cron"
12:53:13.839 [pimatic, npm] info: ERR! node v4.4.0
12:53:13.842 [pimatic, npm] info: ERR! npm  v2.15.0
12:53:13.844 [pimatic, npm] info: ERR! code EPEERINVALID
12:53:13.846 [pimatic, npm] info: ERR! peerinvalid The package pimatic@0.9.1 does not satisfy its siblings' peerDependencies requirements!
12:53:13.847 [pimatic, npm] info: ERR! peerinvalid Peer pimatic-cron@0.8.7 wants pimatic@>=0.8.0 <0.9.0
12:53:13.849 [pimatic, npm] info: ERR! peerinvalid Peer pimatic-mobile-frontend@0.9.0 wants pimatic@0.9.*
12:53:13.883 [pimatic, npm] info: ERR! Please include the following file with any support request:
12:53:13.886 [pimatic, npm] info: ERR!     /home/pi/pimatic-dev/npm-debug.log
12:53:13.928 [pimatic] error: Error running "npm install pimatic-cron"
12:53:13.939 [pimatic] info: Loading plugin: "pimatic-mobile-frontend" (0.9.0)
coffee-cache: compiling coffee-script file "lib/nap.coffee"...Done
12:53:16.277 [pimatic-mobile-frontend] info: packing static assets
12:53:16.671 [pimatic-mobile-frontend] info: packing static assets finished
12:53:16.679 [pimatic-mobile-frontend] info: rendering html
12:53:21.618 [pimatic-mobile-frontend] info: rendering html finished
12:53:21.649 [pimatic] info: Listening for HTTP-request on port 80...
12:53:21.930 [pimatic] error: Error on incoming http request: Can't set headers after they are sent.
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/response.js:718:10)
    at ServerResponse.send (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/response.js:163:12)
    at /home/pi/pimatic-dev/node_modules/pimatic/lib/framework.coffee:434:25
    at Layer.handle_error (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:310:13)
    at /home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:330:12)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:271:10)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/route.js:121:14)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
    at Layer.handle [as handle_request] (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/layer.js:97:5)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/route.js:131:13)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
    at Route.dispatch (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
    at /home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:277:22
    at param (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:349:14)
    at param (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:410:3)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:271:10)
    at /home/pi/pimatic-dev/node_modules/pimatic/lib/framework.coffee:303:18
    at Layer.handle [as handle_request] (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:312:13)
    at /home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:330:12)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:271:10)
    at _cookieSession (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/cookie-session/index.js:124:5)
    at Layer.handle [as handle_request] (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:312:13)
    at /home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:330:12)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:271:10)
    at jsonParser (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/body-parser/lib/types/json.js:100:40)
    at Layer.handle [as handle_request] (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:312:13)
    at /home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:330:12)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:271:10)
    at urlencodedParser (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/body-parser/lib/types/urlencoded.js:88:40)
    at Layer.handle [as handle_request] (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:312:13)
    at /home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:330:12)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:271:10)
    at cookieParser (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/cookie-parser/index.js:70:5)
    at Layer.handle [as handle_request] (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:312:13)
    at /home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:330:12)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:271:10)
    at /home/pi/pimatic-dev/node_modules/pimatic/lib/framework.coffee:244:9
    at Layer.handle [as handle_request] (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:312:13)
    at /home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:330:12)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:271:10)
    at /home/pi/pimatic-dev/node_modules/pimatic/node_modules/connect-timeout/index.js:64:5
    at Layer.handle [as handle_request] (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:312:13)
    at /home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:330:12)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:271:10)
    at expressInit (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/middleware/init.js:33:5)
    at Layer.handle [as handle_request] (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:312:13)
    at /home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:330:12)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:271:10)
    at query (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/middleware/query.js:49:5)
    at Layer.handle [as handle_request] (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:312:13)
    at /home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:330:12)
    at next (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/router/index.js:176:3)
    at EventEmitter.handle (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/application.js:173:10)
    at Server.app (/home/pi/pimatic-dev/node_modules/pimatic/node_modules/express/lib/express.js:38:9)
    at emitTwo (events.js:87:13)
    at Server.emit (events.js:172:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:528:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)

**Comment by sweetpi** [comment]
I can't reproduce this. Maybe some mobile-frontend caching issue? Did you use the same port like for a previous v0.8 setup?

**Comment by sweetpi** [comment]
I added some path info and check if headers already sent. Please reopen if the error occurs again.
