### ISSUE TITLE
Issue with the update function after the internet connection was down

### ISSUE THREAD

**Issue by fritz-hh** [pimatic/pimatic#850]
How to reproduce it:
- In the GUI select "update" while the internet connection is down (In my case due to an issue on ISP side)
- Try GUI select "update" again after the internet connection is up --> Still the "update" function returns an error message (Even 1 day after the internet connection is back to normal state)
- The problem only disappeared after restarting pimatic

Extract of the log file:
`22:53:57.735 [pimatic] error:>  error:
22:53:57.735 [pimatic] error:>   { [Error: getaddrinfo ENOTFOUND]
22:53:57.735 [pimatic] error:>     code: 'ENOTFOUND',
22:53:57.735 [pimatic] error:>     errno: 'ENOTFOUND',
22:53:57.735 [pimatic] error:>     syscall: 'getaddrinfo',
22:53:57.735 [pimatic] error:>     __trace: 'Error: From connect\n    at Socket.connect (/home/pi/pimatic-app/pimatic-app/node_modules/pimatic/startup.coffee:55:29)\n    at Agent.exports.connect.exports.createConnection (net.js:94:26)\n    at Agent.createSocket (http.js:1295:16)\n    at Agent.addRequest (http.js:1271:23)\n    at new ClientRequest (http.js:1416:16)\n    at Object.exports.request (http.js:1843:10)\n    at Request.start (/home/pi/pimatic-app/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/request/request.js:747:30)\n    at Request.end (/home/pi/pimatic-app/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/request/request.js:1381:10)\n    at end (/home/pi/pimatic-app/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/request/request.js:575:14)\n    at Object._onImmediate (/home/pi/pimatic-app/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/request/request.js:589:7)\n    at processImmediate [as _immediateCallback] (timers.js:330:15)' },
22:53:57.735 [pimatic] error:>  options:
22:53:57.735 [pimatic] error:>   { uri: 'http://api.pimatic.org/plugins',
22:53:57.735 [pimatic] error:>     callback: undefined,
22:53:57.735 [pimatic] error:>     simple: true,
22:53:57.735 [pimatic] error:>     resolveWithFullResponse: false },
22:53:57.735 [pimatic] error:>  response: undefined }
22:53:57.754 [pimatic] error: { name: 'RequestError',
22:53:57.754 [pimatic] error:>  message: 'Error: getaddrinfo ENOTFOUND',
22:53:57.754 [pimatic] error:>  cause:
22:53:57.754 [pimatic] error:>   { [Error: getaddrinfo ENOTFOUND]
22:53:57.754 [pimatic] error:>     code: 'ENOTFOUND',
22:53:57.754 [pimatic] error:>     errno: 'ENOTFOUND',
22:53:57.754 [pimatic] error:>     syscall: 'getaddrinfo',
22:53:57.754 [pimatic] error:>     __trace: 'Error: From connect\n    at Socket.connect (/home/pi/pimatic-app/pimatic-app/node_modules/pimatic/startup.coffee:55:29)\n    at Agent.exports.connect.exports.createConnection (net.js:94:26)\n    at Agent.createSocket (http.js:1295:16)\n    at Agent.addRequest (http.js:1271:23)\n    at new ClientRequest (http.js:1416:16)\n    at Object.exports.request (http.js:1843:10)\n    at Request.start (/home/pi/pimatic-app/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/request/request.js:747:30)\n    at Request.end (/home/pi/pimatic-app/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/request/request.js:1381:10)\n    at end (/home/pi/pimatic-app/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/request/request.js:575:14)\n    at Object._onImmediate (/home/pi/pimatic-app/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/request/request.js:589:7)\n    at processImmediate [as _immediateCallback] (timers.js:330:15)' },
22:53:57.754 [pimatic] error:>  error:
22:53:57.754 [pimatic] error:>   { [Error: getaddrinfo ENOTFOUND]
22:53:57.754 [pimatic] error:>     code: 'ENOTFOUND',
22:53:57.754 [pimatic] error:>     errno: 'ENOTFOUND',
22:53:57.754 [pimatic] error:>     syscall: 'getaddrinfo',
22:53:57.754 [pimatic] error:>     __trace: 'Error: From connect\n    at Socket.connect (/home/pi/pimatic-app/pimatic-app/node_modules/pimatic/startup.coffee:55:29)\n    at Agent.exports.connect.exports.createConnection (net.js:94:26)\n    at Agent.createSocket (http.js:1295:16)\n    at Agent.addRequest (http.js:1271:23)\n    at new ClientRequest (http.js:1416:16)\n    at Object.exports.request (http.js:1843:10)\n    at Request.start (/home/pi/pimatic-app/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/request/request.js:747:30)\n    at Request.end (/home/pi/pimatic-app/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/request/request.js:1381:10)\n    at end (/home/pi/pimatic-app/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/request/request.js:575:14)\n    at Object._onImmediate (/home/pi/pimatic-app/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/request/request.js:589:7)\n    at processImmediate [as _immediateCallback] (timers.js:330:15)' },
22:53:57.754 [pimatic] error:>  options:
22:53:57.754 [pimatic] error:>   { uri: 'http://api.pimatic.org/plugins',
22:53:57.754 [pimatic] error:>     callback: undefined,
22:53:57.754 [pimatic] error:>     simple: true,
22:53:57.754 [pimatic] error:>     resolveWithFullResponse: false },
22:53:57.754 [pimatic] error:>  response: undefined }
`

**Comment by sweetpi** [comment]
Hm we cache the update info for 1min. Maybe the cache isn't cleared probably after an error. I will take a look.

**Comment by fritz-hh** [comment]
Thanks for the feedback.
Am 09.04.2016 10:19 schrieb "sweet pi - sweet home" <
notifications@github.com>:
