### ISSUE TITLE
system crashes with pimatic-max plugin

### ISSUE THREAD

**Issue by leader21** [pimatic/pimatic#851]
from the forum
https://forum.pimatic.org/topic/1610/pimatic-max-plugin-broken-since-the-last-update/4

```
21:27:56.922 [pimatic] A uncaught exception occured: TypeError: Cannot call method ‘emit’ of undefined
21:27:56.922 [pimatic]> at /home/pi/pimatic-app/node_modules/pimatic-max/node_modules/max-control/index.js:48:21
21:27:56.922 [pimatic]> at MaxCube.send (/home/pi/pimatic-app/node_modules/pimatic-max/node_modules/max-control/index.js:62:5)
21:27:56.922 [pimatic]> at MaxCube.connect (/home/pi/pimatic-app/node_modules/pimatic-max/node_modules/max-control/index.js:46:10)
21:27:56.922 [pimatic]> at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
21:27:56.922 [pimatic]> This is most probably a bug in pimatic or in a module, please report it!
21:27:56.938 [pimatic] exiting…
```

**Comment by sweetpi** [comment]
Fixed in latest release.

**Comment by DerGrafausB** [comment]
i have the same problem, since the last update 0.8.17

**Comment by mwittig** [comment]
Apparnetly the same problem here ... https://github.com/pimatic/pimatic/issues/921

**Comment by mwittig** [comment]
I assume this issue has been solved. Please re-open if you still experience crashes
