### ISSUE TITLE
Pimatic Max Plugin failed after Upadte from 15.04.2016

### ISSUE THREAD

**Issue by DerGrafausB** [pimatic/pimatic#856]
A uncaught exception occured: TypeError: First argument needs to be a number, array or string.
09:01:43.080 [pimatic]>    at new Buffer (buffer.js:188:15)
09:01:43.080 [pimatic]>    at MaxCube.parseCommandMetadata (/home/pi/pimatic-app/node_modules/pimatic-max/node_modules/max-control/index.js:180:24)
09:01:43.080 [pimatic]>    at MaxCube.parseCommand (/home/pi/pimatic-app/node_modules/pimatic-max/node_modules/max-control/index.js:117:19)
09:01:43.080 [pimatic]>    at MaxCube.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-max/node_modules/max-control/index.js:75:26)
09:01:43.080 [pimatic]>    at Array.forEach (native)
09:01:43.080 [pimatic]>    at MaxCube.onData (/home/pi/pimatic-app/node_modules/pimatic-max/node_modules/max-control/index.js:70:8)
09:01:43.080 [pimatic]>    at Socket.EventEmitter.emit (events.js:95:17)
09:01:43.080 [pimatic]>    at Socket.emit (/home/pi/pimatic-app/node_modules/pimatic/startup.coffee:63:24)
09:01:43.080 [pimatic]>    at Socket.<anonymous> (_stream_readable.js:746:14)
09:01:43.080 [pimatic]>    at Socket.EventEmitter.emit (events.js:92:17)
09:01:43.080 [pimatic]>    at Socket.emit (/home/pi/pimatic-app/node_modules/pimatic/startup.coffee:63:24)
09:01:43.080 [pimatic]>    at emitReadable_ (_stream_readable.js:408:10)
09:01:43.080 [pimatic]>    at emitReadable (_stream_readable.js:404:5)
09:01:43.080 [pimatic]>    at readableAddChunk (_stream_readable.js:165:9)
09:01:43.080 [pimatic]>    at Socket.Readable.push (_stream_readable.js:127:10)
09:01:43.080 [pimatic]>    at TCP.onread (net.js:526:21)
09:01:43.080 [pimatic]> This is most probably a bug in pimatic or in a module, please report it!

**Comment by mwittig** [comment]
@sweetpi Most likely it is a bug of the underlying max-control package. 
https://github.com/sweetpi/max-control/blob/master/index.js#L178-L180

**Comment by sweetpi** [comment]
Hm that's really strange. @DerGrafausB  which cube firmware do you use?

Could you please add the following log statement in `/home/pi/pimatic-app/node_modules/pimatic-max/node_modules/max-control/index.js` line 179 (https://github.com/sweetpi/max-control/blob/master/index.js#L179):

```
console.log(payload);
```

and post the output.

**Comment by DerGrafausB** [comment]
the cube was empty, no rooms, firmware 1.41. I connected all devices, added romms. 
And it works.
The Ids are the same.

**Comment by DerGrafausB** [comment]
and again

 [pimatic] A uncaught exception occured: TypeError: must start with number, buffer, array or string
21:13:31.549 [pimatic]>    at fromObject (buffer.js:138:11)
21:13:31.549 [pimatic]>    at new Buffer (buffer.js:65:10)
21:13:31.549 [pimatic]>    at MaxCube.parseCommandMetadata (/home/pi/pimatic-app/node_modules/pimatic-max/node_modules/max-control/index.js:180:24)
21:13:31.549 [pimatic]>    at MaxCube.parseCommand (/home/pi/pimatic-app/node_modules/pimatic-max/node_modules/max-control/index.js:117:19)
21:13:31.549 [pimatic]>    at MaxCube.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-max/node_modules/max-control/index.js:75:26)
21:13:31.549 [pimatic]>    at Array.forEach (native)
21:13:31.549 [pimatic]>    at MaxCube.onData (/home/pi/pimatic-app/node_modules/pimatic-max/node_modules/max-control/index.js:70:8)
21:13:31.549 [pimatic]>    at emitOne (events.js:77:13)
21:13:31.549 [pimatic]>    at Socket.emit (events.js:169:7)
21:13:31.549 [pimatic]>    at Socket.emit (/home/pi/pimatic-app/node_modules/pimatic/startup.coffee:63:24)
21:13:31.549 [pimatic]>    at readableAddChunk (_stream_readable.js:153:18)
21:13:31.549 [pimatic]>    at Socket.Readable.push (_stream_readable.js:111:10)
21:13:31.549 [pimatic]>    at TCP.onread (net.js:531:20)
21:13:31.549 [pimatic]> This is most probably a bug in pimatic or in a module, please report it!
21:13:31.550 [pimatic] exiting...
