### ISSUE TITLE
[v0.9.x] error on starting. installing sqlite3

### ISSUE THREAD

**Issue by michaelberg79** [pimatic/pimatic#872]
Hey,

I tried to install pimatic and the plugins by github, If i now try to start pimatic i get following error.:

15:48:55.290 2016-04-25 Monday
15:49:23.106 [pimatic] Starting pimatic version 0.9.8
15:49:27.915 [pimatic] Could not find a device with the ID "S2" from group "lampen" in devices config section.
15:49:27.928 [pimatic] Could not find a device with the ID "rauchmelder" from group "lampen" in devices config section.
15:49:29.033 [pimatic] Installing database package sqlite3, this can take some minutes
15:54:27.985 [pimatic, npm] WARN enoent ENOENT: no such file or directory, open '/home/pi/pimatic-app/package.json'
15:54:28.041 [pimatic, npm] ERR! Linux 4.1.13+
15:54:28.063 [pimatic, npm] ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sqlite3"
15:54:28.083 [pimatic, npm] ERR! node v4.4.3
15:54:28.105 [pimatic, npm] ERR! npm  v3.8.7
15:54:28.125 [pimatic, npm] ERR! path /home/pi/pimatic-app/node_modules/pimatic
15:54:28.145 [pimatic, npm] ERR! code EISGIT
15:54:28.181 [pimatic, npm] ERR! git /home/pi/pimatic-app/node_modules/pimatic: Appears to be a git repo or submodule.
15:54:28.193 [pimatic, npm] ERR! git     /home/pi/pimatic-app/node_modules/pimatic
15:54:28.213 [pimatic, npm] ERR! git Refusing to remove it. Update manually,
15:54:28.235 [pimatic, npm] ERR! git or move it out of the way first.
15:54:29.328 [pimatic, npm] ERR! Please include the following file with any support request:
15:54:29.345 [pimatic, npm] ERR!     /home/pi/pimatic-app/npm-debug.log
15:54:29.608 [pimatic] Startup error: Error: Error running "npm install sqlite3"
15:54:29.608 [pimatic]>    at ChildProcess.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic/lib/plugins.coffee:348:26)
15:54:29.608 [pimatic]>    at emitTwo (events.js:87:13)
15:54:29.608 [pimatic]>    at ChildProcess.emit (events.js:172:7)
15:54:29.608 [pimatic]>    at maybeClose (internal/child_process.js:827:16)
15:54:29.608 [pimatic]>    at Socket.<anonymous> (internal/child_process.js:319:11)
15:54:29.608 [pimatic]>    at emitOne (events.js:77:13)
15:54:29.608 [pimatic]>    at Socket.emit (events.js:169:7)
15:54:29.608 [pimatic]>    at Pipe._onclose (net.js:477:12)
15:54:29.633 [pimatic] exiting...

The same error appears if i try to install sqlite3 manually.

best regards
Michael

**Comment by michaelberg79** [comment]
I downloaded node sqlite3 by git and installed it manually into the ~/pimatic-app/node_modules/ folder. After that pimatic started fully. I cant install packages by git and use they as modules for npm?

**Comment by michaelberg79** [comment]
I installed a new fresh pimatic instance directly by npm with git sources. Not by cloning github resources. Now pimatic could install sqlite3 at startup.
