### ISSUE TITLE
starting up error

### ISSUE THREAD

**Issue by michaelberg79** [pimatic/pimatic#876]
Hallo,

Ich habe nun erfolgreich pimatic 0.9 installiert und schon ein paar mal ausgeführt. Nachdem ich nun , nach der installation eines Plugins,  neu starten wollte will pimatic nicht mehr starten. Folgende Fehlermeldung wird vor dem html rendering ausgelöst:

20:21:04.944 [pimatic-max] connection error: Error: The cube is busy
Fatal Error: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at /home/pi/pimatic-app/node_modules/knex/lib/runner.js:138:30
    at tryCatcher (/home/pi/pimatic-app/node_modules/knex/node_modules/bluebird/js/main/util.js:26:23)
    at CatchFilter.doFilter (/home/pi/pimatic-app/node_modules/knex/node_modules/bluebird/js/main/catch_filter.js:40:36)
    at CatchFilter.tryCatcher (/home/pi/pimatic-app/node_modules/knex/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/knex/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/pi/pimatic-app/node_modules/knex/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/home/pi/pimatic-app/node_modules/knex/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/home/pi/pimatic-app/node_modules/knex/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/pi/pimatic-app/node_modules/knex/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/pimatic-app/node_modules/knex/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by mwittig** [comment]
Hast Du schon versucht den Raspi mal zu rebooten?

**Comment by michaelberg79** [comment]
I tried something arround. There was some max temperatur rules pimatic tried to start at begining. this rules could not be executed because of fetching data from the cube (update). The cube is busy. Because of this, there is a long blocked time of pimatic while pimatic-max is trying to send the command.  Knex lost the connection too after pimatix-max gets timeouted. 

if you need some futher informations to fix this error please contact.
