### ISSUE TITLE
Cannot restart / Stop pimatic

### ISSUE THREAD

**Issue by hyp3rx** [pimatic/pimatic#880]
Hello,
today after update to 0.8.107 i cannot restart or stop the service:

sudo pimatic.js stop
sudo: pimatic.js: command not found

If running as SU i get the fallowing:

root@raspberrypi:/home/pi/pimatic-app/node_modules/pimatic# pimatic.js stop
bash: /usr/local/bin/pimatic.js: Permission denied

I´ve done nothing except the update of pimatic.

**Comment by sweebee** [comment]
I have the same issue with 0.9. npm link doesn't work anymore. So I have changed the auto start file:
```
nano /etc/init.d/pimatic
```
and changed it to:
```

#! /bin/sh
### BEGIN INIT INFO
# Provides:          pimatic
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: pimatic service
# Description:       pimatic home automation framework init.d script for debian systems.
### END INIT INFO

# Author: Oliver Schneider <oliverschneider89+sweetpi@gmail.com>
# Install:
# cp pimatic-init-d /etc/init.d/pimatic
# chmod +x /etc/init.d/pimatic
# chown root:root /etc/init.d/pimatic
# update-rc.d pimatic defaults
# Make sure the pimatic.js file is linked in one of the pathes in the PATH variable below.
# The node.js binary must be in the PATH, too.

PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/opt/node/bin

if [ "$1" = "start" ] || [ "$1" = "stop" ] || [ "$1" = "restart" ] || [ "$1" = "status" ] 
then
        node /home/pi/pimatic-app/node_modules/pimatic/pimatic.js $1
        exit "$?"
else 
        echo "Usage: service pimatic {start|stop|status|restart}" >&2
        exit 3
fi
```

**Comment by hyp3rx** [comment]
works ! thanks

**Comment by hyp3rx** [comment]
I was to fast... i can start it, but now after 10 sec. it stops.. 

pi@raspberrypi ~ $ sudo service pimatic status
Pidfile exists, but process is dead.

in pimatic-daemon.log
i only get:

14:10:30.343 2016-05-01 Sunday

any ideas ?

**Comment by sweebee** [comment]
Try:

```
Sudo node /home/pi/pimatic-app/node_modules/pimatic.js
```

So no start or restart. And check what happens.

**Comment by hyp3rx** [comment]
sudo node /home/pi/pimatic-app/node_modules/pimatic.js
module.js:338
    throw err;
          ^
Error: Cannot find module '/home/pi/pimatic-app/node_modules/pimatic.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by sweebee** [comment]
check my edit, forgot the pimatic folder

**Comment by hyp3rx** [comment]
ok so the debug start command has also changed...

Btw. it starts just normal ! Everything is ok ! But not as service !

**Comment by sweebee** [comment]
and if you demonize it this way:

```
Sudo node /home/pi/pimatic-app/node_modules/pimatic/pimatic.js start
```

**Comment by hyp3rx** [comment]
seems ok

sudo service pimatic status
Process running with pid 4477.

**Comment by quintz** [comment]
I've updated to 0.8.107 this morning too and now I also cannot start my pimatic server via daemon.

If I try 

`sudo pimatic.js start/status/stop`

then I'll get

`-bash: Sudo: command not found`

**Comment by leader21** [comment]
Try this. go to the node_modules/pimatic/ folder and use the command `sudo npm install`
This will reinstall pimatic and the dependencies

**Comment by quintz** [comment]
still the same unfortunately...
```
 sudo pimatic.js
19:13:58.986 2016-05-04 Wednesday

module.js:340
    throw err;
          ^
Error: Cannot find module 'lodash/object/assign'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic/node_modules/request-promise/lib/rp.js:5:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (/home/pi/pimatic-app/node_modules/pimatic/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic/lib/plugins.coffee:20:6)
    at Module._compile (module.js:456:26)
    at Object.compile (/home/pi/pimatic-app/node_modules/pimatic/coffee-cache.js:169:17)
    at Module.load (/home/pi/pimatic-app/node_modules/pimatic/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic/startup.coffee:21:15)
    at Module._compile (module.js:456:26)
    at Object.compile (/home/pi/pimatic-app/node_modules/pimatic/coffee-cache.js:169:17)
    at Module.load (/home/pi/pimatic-app/node_modules/pimatic/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at run (/home/pi/pimatic-app/node_modules/pimatic/pimatic.js:15:3)
    at Object.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic/pimatic.js:20:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

But noticed some unmet dependencies while I made npm install.

for example:

```
/home/pi/pimatic-app/node_modules/pimatic/node_modules/request-promise requires lodash@'^3.10.0' but will load
npm WARN unmet dependency /home/pi/pimatic-app/node_modules/pimatic/node_modules/lodash,
npm WARN unmet dependency which is version 2.4.1
```

**Comment by mwittig** [comment]
Should be resolved. Please re-open or create new issue ticket of problem remain
