### ISSUE TITLE
[0.9.x] Error: Can't set headers after they are sent

### ISSUE THREAD

**Issue by andig** [pimatic/pimatic#893]
This happens when connecting to frontend:

	pi@raspberrypi:~/pimatic $ sudo node pimatic.js
	13:58:54.670 2016-05-13 Friday
	13:59:03.889 [pimatic] Starting pimatic version 0.9.12
	13:59:07.541 [pimatic, npm] 2.15.1
	13:59:07.647 [pimatic] Loading plugin: "pimatic-cron" (0.8.8)
	13:59:08.471 [pimatic] Loading plugin: "pimatic-mobile-frontend" (0.9.4)
	13:59:09.768 [pimatic-cron] the time is: Fri May 13 2016 13:59:09 GMT+0000 (UTC)
	13:59:11.044 [pimatic-mobile-frontend] packing static assets
	13:59:11.734 [pimatic-mobile-frontend] packing static assets finished
	13:59:11.752 [pimatic-mobile-frontend] rendering html
	13:59:22.740 [pimatic-mobile-frontend] rendering html finished
	13:59:22.818 [pimatic] Listening for HTTP-request on port 8000...
	14:01:18.410 [pimatic-mobile-frontend] rendering theme: graphite/water
	coffee-cache: compiling coffee-script file "themes/graphite/water.coffee"...Done
	coffee-cache: compiling coffee-script file "themes/graphite/base.coffee"...Done
	14:01:19.329 [pimatic] Error on incoming http request to /socket.io/: Can't set headers after they are sent.
	Error: Can't set headers after they are sent.
	    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
	    at ServerResponse.header (/home/pi/pimatic/node_modules/pimatic/node_modules/express/lib/response.js:718:10)
	    at ServerResponse.send (/home/pi/pimatic/node_modules/pimatic/node_modules/express/lib/response.js:163:12)
	    at /home/pi/pimatic/node_modules/pimatic/lib/framework.coffee:436:27
	    at Layer.handle_error (/home/pi/pimatic/node_modules/pimatic/node_modules/express/lib/router/layer.js:71:5)
	    at trim_prefix (/home/pi/pimatic/node_modules/pimatic/node_modules/express/lib/router/index.js:310:13)
	    at /home/pi/pimatic/node_modules/pimatic/node_modules/express/lib/router/index.js:280:7
	    at Function.process_params (/home/pi/pimatic/node_modules/pimatic/node_modules/express/lib/router/index.js:330:12)
	    at next (/home/pi/pimatic/node_modules/pimatic/node_modules/express/lib/router/index.js:271:10)
	    at next (/home/pi/pimatic/node_modules/pimatic/node_modules/express/lib/router/route.js:121:14)
	    at next (/home/pi/pimatic/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
	    at next (/home/pi/pimatic/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
	    at next (/home/pi/pimatic/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
	    at next (/home/pi/pimatic/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
	    at next (/home/pi/pimatic/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)
	    at next (/home/pi/pimatic/node_modules/pimatic/node_modules/express/lib/router/route.js:125:14)

**Comment by mwittig** [comment]
Thanks for fileing this one. I also have seen this before.

**Comment by andig** [comment]
Only happened once though. Seems to be if pre-0.9 stuff is still on client side?
