### ISSUE TITLE
502

### ISSUE THREAD

**Issue by dennis071nl** [pimatic/pimatic#899]
After upgrade i cannot start unfortunately: 

Unhandled rejection Error: Error: Command execution failed with exit code 7 (Error: Command failed:)
    at Object.ensureErrorObject (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:261:20)
    at Promise._rejectCallback (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:469:22)
    at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:513:17)
    at Promise._settlePromiseAt (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:419:13)

Is there a simple solutuion for me??

**Comment by mwittig** [comment]
Which version of pimatic do you have currently installed? Did you try to reboot the Raspi?

**Comment by mwittig** [comment]
I assume this has been solved. Please re-open otherwise.
