### ISSUE TITLE
Error installing sqlite3: Cannot find module 'nopt'

### ISSUE THREAD

**Issue by schulzeh** [pimatic/pimatic#916]
Hello,
after entering sudo pimatic.js I get 
this message:
tested on Rasberry pi 2 model B
and Raspberry Ziro

```
pi@rpi2:~ $ sudo pimatic.js

18:12:08.922 2016-06-05 Sunday

18:12:33.015 [pimatic] Starting pimatic version 0.8.107

18:12:35.766 [pimatic] Installing database package sqlite3, this can take some minutes

18:12:42.391 [pimatic, npm] http GET https://registry.npmjs.org/sqlite3

18:12:44.175 [pimatic, npm] http 200 https://registry.npmjs.org/sqlite3

18:12:50.072 [pimatic, npm] http GET https://registry.npmjs.org/nan

18:12:52.063 [pimatic, npm] > sqlite3@3.1.4 install /home/pi/pimatic-app/node_modules/sqlite3

18:12:52.082 [pimatic, npm] > node-pre-gyp install --fallback-to-build

18:12:52.924 [pimatic, npm] module.js:340

18:12:52.942 [pimatic, npm]     throw err;

18:12:52.948 [pimatic, npm]           ^

18:12:52.978 [pimatic, npm] Error: Cannot find module 'nopt'

18:12:52.999 [pimatic, npm]     at Function.Module._resolveFilename (module.js:338:15)

18:12:53.006 [pimatic, npm]     at Function.Module._load (module.js:280:25)

18:12:53.023 [pimatic, npm]     at Module.require (module.js:364:17)

18:12:53.029 [pimatic, npm]     at require (module.js:380:17)

18:12:53.041 [pimatic, npm]     at Object.<anonymous> (/home/pi/pimatic-app/node_modules/sqlite3/node_modules/node-pre-gyp/lib/node-pre-gyp.js:14:12)

18:12:53.052 [pimatic, npm]     at Module._compile (module.js:456:26)

18:12:53.071 [pimatic, npm]     at Object.Module._extensions..js (module.js:474:10)

18:12:53.077 [pimatic, npm]     at Module.load (module.js:356:32)

18:12:53.088 [pimatic, npm]     at Function.Module._load (module.js:312:12)

18:12:53.101 [pimatic, npm]     at Module.require (module.js:364:17)

18:12:53.318 [pimatic, npm] ERR! sqlite3@3.1.4 install: `node-pre-gyp install --fallback-to-build`

18:12:53.333 [pimatic, npm] ERR! Exit status 8

18:12:53.351 [pimatic, npm] ERR! 

18:12:53.358 [pimatic, npm] ERR! Failed at the sqlite3@3.1.4 install script.

18:12:53.372 [pimatic, npm] ERR! This is most likely a problem with the sqlite3 package,

18:12:53.391 [pimatic, npm] ERR! not with npm itself.

18:12:53.398 [pimatic, npm] ERR! Tell the author that this fails on your system:

18:12:53.411 [pimatic, npm] ERR!     node-pre-gyp install --fallback-to-build

18:12:53.428 [pimatic, npm] ERR! You can get their info via:

18:12:53.434 [pimatic, npm] ERR!     npm owner ls sqlite3

18:12:53.452 [pimatic, npm] ERR! There is likely additional logging output above.

18:12:53.467 [pimatic, npm] ERR! System Linux 4.1.19+

18:12:53.474 [pimatic, npm] ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sqlite3"

18:12:53.492 [pimatic, npm] ERR! cwd /home/pi/pimatic-app

18:12:53.499 [pimatic, npm] ERR! node -v v0.10.24

18:12:53.521 [pimatic, npm] ERR! npm -v 1.3.21

18:12:53.528 [pimatic, npm] ERR! code ELIFECYCLE

18:12:53.574 [pimatic, npm] ERR! 

18:12:53.590 [pimatic, npm] ERR! Additional logging details can be found in:

18:12:53.612 [pimatic, npm] ERR!     /home/pi/pimatic-app/npm-debug.log

18:12:53.621 [pimatic, npm] ERR! not ok code 0

18:12:53.742 [pimatic] Startup error: Error: Error running "npm install sqlite3"

18:12:53.742 [pimatic]>    at ChildProcess.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic/lib/plugins.coffee:327:24)

18:12:53.742 [pimatic]>    at ChildProcess.EventEmitter.emit (events.js:98:17)

18:12:53.742 [pimatic]>    at maybeClose (child_process.js:735:16)

18:12:53.742 [pimatic]>    at Socket.<anonymous> (child_process.js:948:11)

18:12:53.742 [pimatic]>    at Socket.EventEmitter.emit (events.js:95:17)

18:12:53.742 [pimatic]>    at Pipe.close (net.js:466:12)

18:12:53.762 [pimatic] exiting...
```

**Comment by sweetpi** [comment]
Your log says you still use `npm -v 1.3.21` ?

Try: `sudo npm install npm@2 -g`

and do

```
sudo rm -rf /home/pi/pimatic-app/node_modules/sqlite3
```

before starting pimatic.

**Comment by sweetpi** [comment]
And maybe try the solution mentioned here: https://forum.pimatic.org/topic/1824/solved-error-installing-sqlite3

**Comment by sweetpi** [comment]
Seems to be a common problem?
https://github.com/mapbox/node-sqlite3/issues/655

**Comment by mwittig** [comment]
@sweetpi Yes, seems like it is packaging problem.  "I declared (the) dependency as well as bundledDependency to node-pre-gyp but before issuing npm publish I forgot to do npm install in my module local directory.". Found at <https://github.com/mapbox/node-pre-gyp/issues/67>. 

As far as I understand this, it has already bean fixed on master by commit https://github.com/mapbox/node-sqlite3/commit/9a038b503c89e83a8e45098df37764507de2b903

**Comment by schulzeh** [comment]
Hello,
now I ues this:

sudo npm install nopt
sudo npm install npmlog
sudo npm install semver
sudo npm install rimraf
and
sudo npm install sqlite3@3.1.3 --unsafe-perm

from this site
https://forum.pimatic.org/topic/1824/solved-error-installing-sqlite3
and now it works.
Thank you for the fast help!
Holger

**Comment by mwittig** [comment]
Apparently, the issue only occurs with node 0.10. See last post at mapbox/node-sqlite3#655
