### ISSUE TITLE
All plugin installations fail on fresh 0.9 install

### ISSUE THREAD

**Issue by Kamaluk** [pimatic/pimatic#935]
my fresh pimatic installation on the Pi Zero fails to install the DHT-Plugin

```
node-dht-sensor.target.mk:86:
 
recipe for target 'Release/obj.target/node-dht-sensor/node-dht-sensor.o' failed
make: *** [Release/obj.target/node-dht-sensor/node-dht-sensor.o] Error 1
make: Leaving directory '/home/pi/node_modules/pimatic-dht-sensors/node_modules/node-dht-sensor/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.11+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/node_modules/pimatic-dht-sensors/node_modules/node-dht-sensor
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Linux 4.4.11+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pimatic-dht-sensors"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE

npm ERR! node-dht-sensor@0.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-dht-sensor@0.0.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-dht-sensor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-dht-sensor
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls node-dht-sensor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log
```

**Comment by Kamaluk** [comment]
the same error happens with my Raspberry Pi 3 and a fresh install!

**Comment by Kamaluk** [comment]
Now if I try to install for example homeduino - it also doesn't work

Maybe it has something to do with this:

```
npm WARN peerDependencies The peer dependency pimatic@0.9.* included from pimati                              c-homeduino will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerD                              ependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it                               explicitly.
```

**Comment by Kamaluk** [comment]
The homeduino installation also fails

```
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.4.5"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/.node-gyp"
make: Entering directory '/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/build'
make: *** No rule to make target '../.node-gyp/4.4.5/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.11-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/build/Release/node-v46-linux-arm/serialport.node" "--module_name=serialport" "--module_path=/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/build/Release/node-v46-linux-arm"
gyp ERR! cwd /home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/build/Release/node-v46-linux-arm/serialport.node --module_name=serialport --module_path=/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/build/Release/node-v46-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 4.4.11-v7+
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport
node-pre-gyp ERR! node -v v4.4.5
node-pre-gyp ERR! node-pre-gyp -v v0.6.18
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/build/Release/node-v46-linux-arm/serialport.node --module_name=serialport --module_path=/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/build/Release/node-v46-linux-arm' (1)
npm ERR! Linux 4.4.11-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pimatic-homeduino"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE

npm ERR! serialport@2.0.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serialport@2.0.6 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs serialport
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/pimatic-app/npm-debug.log

```

**Comment by Kamaluk** [comment]
The installation of homeduino worked without the sudo

`npm install pimatic-pluginname`

**Comment by mwittig** [comment]
If you use the web frontend to install plugin this should work without problems. If you install from the command line for whatever reason this should like as follows for the common case:

```bash
sudo npm install pimatic-pluginname --unsafe-perm
