### ISSUE TITLE
[0.9] Too many event handlers registered with VariableManager events

### ISSUE THREAD

**Issue by mwittig** [pimatic/pimatic#955]
Seems like there are too many event handlers registered with VariableManager events. I think we need to review this careefully.

See also: https://forum.pimatic.org/topic/2081/missing-property-allowedorigin

```
10:53:52.844 [pimatic] info: New device “Beweging N 2”…
(node) warning: possible EventEmitter memory leak detected. 101 variableRemoved listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
at VariableManager.addListener (events.js:239:17)
at VariablePredicateHandler.PredicateHandler.dependOnVariable (/home/pi/pimatic-app/node_modules/pimatic/lib/predicates.coffee:63:23)
at VariablePredicateHandler.setup (/home/pi/pimatic-app/node_modules/pimatic/lib/predicates.coffee:625:10)
at /home/pi/pimatic-app/node_modules/pimatic/lib/rules.coffee:590:21
at RuleManager._addPredicateChangeListener (/home/pi/pimatic-app/node_modules/pimatic/lib/rules.coffee:587:9)
at /home/pi/pimatic-app/node_modules/pimatic/lib/rules.coffee:711:10
at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:504:31)
at Promise._settlePromise (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:561:18)
at Promise._settlePromiseCtx (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:598:10)
at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:143:12)
at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:148:10)
at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:17:14)
at processImmediate [as _immediateCallback] (timers.js:383:17)
10:54:42.164 [pimatic-mobile-frontend] info: packing static assets

**Comment by WimUtTwente** [comment]
Currently I am using 90 devices and 102 rules.

**Comment by mwittig** [comment]
OK, thanks. Seems like you're using a lot of variables as part of your rules :) Currently we have a limit of 100 event listeners per event source and it seems like you have more than 100 variable usages, e.g. some like "when $myDevice.attribute > 0 then ...". Before we increase the limit I think we need to check:
- if multiple registrations occur from the same origin (this may be a bug)
- give it  some thought about whether or not we need a different concept for the interaction between the Rule and Variables Managers

**Comment by bstrebel** [comment]
Run into the same warning with 110 devices and 100 rules. How can I increase the limit?

**Comment by mwittig** [comment]
Sorry, it is not configurable at the moment.

**Comment by mwittig** [comment]
From the [docs](https://nodejs.org/api/events.html#events_eventemitter_defaultmaxlisteners):
"Note, that this is not a hard limit. The EventEmitter instance will allow more listeners to be added but will output a trace warning to stderr indicating that a "possible EventEmitter memory leak" has been detected.".  

I'll look into this soon.

**Comment by bstrebel** [comment]
Thanks for the clarification. It would be great to have the limit either configurable or something like "self-adjusting" according to the number of devices and rules found in config.json

**Comment by bstrebel** [comment]
Just updated to 0.9.34 and checked the new "defaultMaxListeners" settings: works like a charm. Thanks!

**Comment by mwittig** [comment]
You're welcome :) I am closing this now

**Comment by WimUtTwente** [comment]
Just updated to 0.9.34  with "defaultMaxListeners" : 300 
no more error messages on startup verdwer everything works normal,
Thanks!
