### ISSUE TITLE
[pimatic-hue-zll] PayloadTooLargeError

### ISSUE THREAD

**Issue by Timvdv** [pimatic/pimatic#973]
Not 100% sure if this has something to do with a HueZLL device but it does trigger the bug. The plugin functions like it should only thing is that the layout is broken.

- Install the plugin -> everything seems to work
- add a device -> everything breaks

The thing is most people on the forum don't have this so it might be a local issue.

Used the default way to add a device

```
    {
      "id": "hue_color",
      "class": "HueZLLExtendedColorLight",
      "hueId": 1,
    },
```

My error log:

```
22:21:49.566 [pimatic] error: Error on incoming http request to /client-error: too many parameters
22:21:49.568 [pimatic] debug: PayloadTooLargeError: too many parameters
22:21:49.568 [pimatic] debug:>    at queryparse (/home/tim/pimatic-dev/node_modules/body-parser/lib/types/urlencoded.js:144:13)
22:21:49.568 [pimatic] debug:>    at parse (/home/tim/pimatic-dev/node_modules/body-parser/lib/types/urlencoded.js:75:9)
22:21:49.568 [pimatic] debug:>    at /home/tim/pimatic-dev/node_modules/body-parser/lib/read.js:116:18
22:21:49.568 [pimatic] debug:>    at invokeCallback (/home/tim/pimatic-dev/node_modules/raw-body/index.js:262:16)
22:21:49.568 [pimatic] debug:>    at done (/home/tim/pimatic-dev/node_modules/raw-body/index.js:251:7)
22:21:49.568 [pimatic] debug:>    at IncomingMessage.onEnd (/home/tim/pimatic-dev/node_modules/raw-body/index.js:308:7)
22:21:49.568 [pimatic] debug:>    at emitNone (events.js:80:13)
22:21:49.568 [pimatic] debug:>    at IncomingMessage.emit (events.js:179:7)
22:21:49.568 [pimatic] debug:>    at endReadableNT (_stream_readable.js:913:12)
22:21:49.568 [pimatic] debug:>    at _combinedTickCallback (internal/process/next_tick.js:74:11)
22:21:49.568 [pimatic] debug:>    at process._tickCallback (internal/process/next_tick.js:98:9)
22:21:56.400 [pimatic] error: Error on incoming http request to /client-error: too many parameters
22:21:56.405 [pimatic] debug: PayloadTooLargeError: too many parameters
22:21:56.405 [pimatic] debug:>    at queryparse (/home/tim/pimatic-dev/node_modules/body-parser/lib/types/urlencoded.js:144:13)
22:21:56.405 [pimatic] debug:>    at parse (/home/tim/pimatic-dev/node_modules/body-parser/lib/types/urlencoded.js:75:9)
22:21:56.405 [pimatic] debug:>    at /home/tim/pimatic-dev/node_modules/body-parser/lib/read.js:116:18
22:21:56.405 [pimatic] debug:>    at invokeCallback (/home/tim/pimatic-dev/node_modules/raw-body/index.js:262:16)
22:21:56.405 [pimatic] debug:>    at done (/home/tim/pimatic-dev/node_modules/raw-body/index.js:251:7)
22:21:56.405 [pimatic] debug:>    at IncomingMessage.onEnd (/home/tim/pimatic-dev/node_modules/raw-body/index.js:308:7)
22:21:56.405 [pimatic] debug:>    at emitNone (events.js:80:13)
22:21:56.405 [pimatic] debug:>    at IncomingMessage.emit (events.js:179:7)
22:21:56.405 [pimatic] debug:>    at endReadableNT (_stream_readable.js:913:12)
22:21:56.405 [pimatic] debug:>    at _combinedTickCallback (internal/process/next_tick.js:74:11)
22:21:56.405 [pimatic] debug:>    at process._tickCallback (internal/process/next_tick.js:98:9)
22:22:09.407 [pimatic-hue-zll] debug: Changing light 1 state: {"on":false}
22:22:10.495 [pimatic-hue-zll] debug: Changing light 1 state: {"on":true}
22:22:12.130 [pimatic-hue-zll] debug: Changing light 1 state: {"on":true,"bri":55}
22:22:12.935 [pimatic-hue-zll] debug: Changing light 1 state: {"on":true,"bri":205}
```

And how it looks in the front-end
![schermafbeelding 2016-09-06 om 22 28 33](https://cloud.githubusercontent.com/assets/979227/18289847/6ac18c00-7481-11e6-8b8c-08c706fea5ae.png)

**Comment by mwittig** [comment]
Can you please also check the Web Console (e.g. <Crtl><Shift>i on Chrome) of the Browser for errors?

**Comment by sweebee** [comment]
This has nothing to do with the huezll, after last update of pimatic i got the same. Cleaning the cash helped for me.

**Comment by Timvdv** [comment]
@sweebee the mobile-front-end cache? because I did that already and it had no effect

**Comment by Timvdv** [comment]
Okay, solved the issue by completely reinstalling Pimatic. So it was probably caching like you said. But still weird.

I'll close this for now.
