### ISSUE TITLE
[pimatic-kodi] Uncaught exception

### ISSUE THREAD

**Issue by mwittig** [pimatic/pimatic#975]
See https://forum.pimatic.org/topic/2176/bug-in-kodi-plugin-for-0-9

Error handlings needs to be improved,
```
error [pimatic]: A uncaught exception occured: SyntaxError: Unexpected token �
at Object.parse (native)
at Schema.handleResponse (/home/pi/pimatic-app/node_modules/pimatic-kodi/node_modules/xbmc-ws/node_modules/jrpc-schema/lib/Schema.js:59:17)
at emitTwo (events.js:87:13)
at WebSocket.emit (events.js:172:7)
at Receiver.self._receiver.ontext (/home/pi/pimatic-app/node_modules/pimatic-kodi/node_modules/xbmc-ws/node_modules/ws/lib/WebSocket.js:682:10)
at Receiver.opcodes.1.finish (/home/pi/pimatic-app/node_modules/pimatic-kodi/node_modules/xbmc-ws/node_modules/ws/lib/Receiver.js:391:14)
at Receiver.expectHandler (/home/pi/pimatic-app/node_modules/pimatic-kodi/node_modules/xbmc-ws/node_modules/ws/lib/Receiver.js:378:31)
at Receiver.add (/home/pi/pimatic-app/node_modules/pimatic-kodi/node_modules/xbmc-ws/node_modules/ws/lib/Receiver.js:87:24)
at Socket.firstHandler (/home/pi/pimatic-app/node_modules/pimatic-kodi/node_modules/xbmc-ws/node_modules/ws/lib/WebSocket.js:663:22)
at emitOne (events.js:77:13)
at Socket.emit (events.js:169:7)
at Socket.emit (/home/pi/pimatic-app/node_modules/pimatic/startup.coffee:63:24)
at readableAddChunk (_stream_readable.js:153:18)
at Socket.Readable.push (_stream_readable.js:111:10)
at TCP.onread (net.js:531:20)

**Comment by mwittig** [comment]
The plugin also uses completly outdated forks of `node-xbmc-ws` and `node-jrpc-schema`. The forks had been created to promisify parts of the code. I don't think this is good approach. The promisification should be done at the plugin level!
