### ISSUE TITLE
error [pimatic]: A uncaught exception occured: TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by ccvh** [pimatic/pimatic#991]
Not sure if posted before, but the 3 issues when i tried to search showed different "bugs" ...

Complete log:
`error [pimatic]: A uncaught exception occured: TypeError: Cannot read property 'then' of undefined
    at Request.onResponse [as _callback] (/home/pi/pimatic-app/node_modules/pimatic-plex/node_modules/plex-api/lib/api.js:114:17)
    at Request.self.callback (/home/pi/pimatic-app/node_modules/pimatic-plex/node_modules/plex-api/node_modules/request/request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-plex/node_modules/plex-api/node_modules/request/request.js:1048:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-plex/node_modules/plex-api/node_modules/request/request.js:969:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
 This is most probably a bug in pimatic or in a module, please report it!`

**Comment by mwittig** [comment]
This is possible related to issue #988 
Which version of Plex do you have installed?

**Comment by ccvh** [comment]
I'm currently running Server Version 1.1.4.2757 (most latest i think) - and the plex plugin is installed, but not currently running (could'nt get it configured properly - or it's not supported since the last few updates?)

**Comment by mwittig** [comment]
@ccvh Do you know a free plex player I can use? Unfortunately, all players offered by the plex project seem to paid for version except for web player. However, when I use the web player I can see the title played in pimatic, but I can control the player, e.g. stop. I have also tried Windows Media Player, but this still does not seem to work as various reported before.

**Comment by ccvh** [comment]
@mwittig the Android Version is free (limited to 1 minute of playback..), probably that's enough? The only player that's totally free without buying a new device (like ps4, xb1,...)
Hope that helps. If I can do anything, just let me know

**Comment by mwittig** [comment]
@ccvh Thanks. 1min playback will do for testing.
